#!/usr/bin/env bash

set -e

elem_type=HEX8
N=5

SFEM_ELEMENT_REFINE_LEVEL=`grep "refine_level" input.yaml | awk '{print $2}'`
export BOX_MESH_EXTRA_OPTIONS="--tx=-0.5 --ty=-0.5 --tz=-0.5"
../../../../data/benchmarks/meshes/create_box_ss_mesh.sh $N $SFEM_ELEMENT_REFINE_LEVEL  
box_mesh.py obstacle_mesh -x 2 -y 4 -z 4 --cell_type=TET4 --width=2 --height=4 --depth=4 --tx=-1 --ty=-2 --tz=-2

skin obstacle_mesh obstacle_mesh/skin

mkdir -p obstacle
echo "# Generated by setup.sh" > obstacle/meta.yaml
echo "surface: ../mesh/surface/left" >> obstacle/meta.yaml
echo "sdf: sdf" >> obstacle/meta.yaml
echo "rpath: true" >> obstacle/meta.yaml

margin=0.5
hmax=0.01
mkdir -p obstacle/sdf
mesh_to_sdf.py obstacle_mesh/skin obstacle/sdf/sdf.float32.raw --hmax=$hmax --margin=$margin
raw_to_xdmf.py obstacle/sdf/sdf.float32.raw
cp obstacle/sdf/metadata_sdf.float32.yml obstacle/sdf/meta.yaml 

