import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import numpy as np

from codegen.framework.mlir import (
    MLIR_OPTIMIZATION_PLANS,
    MLIROptimizationStrategy,
    MatrixFreeEBEMLIRLowering,
    TensorProductLaplaceFormBatchedGPULowering,
    TensorProductLaplaceFormEBEGPULowering,
    TensorProductLaplaceFormEBEMetalLowering,
    TensorProductLaplaceFormGPULowering,
    TensorProductLaplaceFormMetalLowering,
    TensorProductLaplaceReferenceEvaluator,
    TensorProductSumFactorMLIRLowering,
    TensorProductSumFactorReferenceEvaluator,
    ThreadedEBEExecutor,
    build_inverted_topology,
    pad_to_vector_width,
    reference_ebe_residual,
    tensor_product_laplace_form_ir_from_material,
    tensor_product_sum_factor_ir_from_material,
)


class MatrixFreeEBEMLIRTest(unittest.TestCase):
    def test_model_is_sourced_from_generated_linear_elasticity_plan(self):
        lowering = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        )
        model = lowering.model

        self.assertEqual(model.material_name, "linear_elasticity")
        self.assertEqual(model.kernel_kind, "energy_soa")
        self.assertEqual(model.element_type, "TET4")
        self.assertEqual(model.mesh_kernel_name, "linear_elasticity_tet4")
        self.assertEqual(model.local_apply_name, "linear_elasticity_d3_simplex_apply")
        self.assertEqual(model.mesh_phases, ("geometry", "local_call", "scatter"))
        self.assertEqual(model.expression_names, ("objective", "gradient", "apply"))
        self.assertEqual(model.dim, 3)
        self.assertEqual(model.n_shape, 4)
        self.assertEqual(model.n_qp, 1)
        self.assertEqual(model.vector_size, 8)
        self.assertEqual(model.parameters, ("lmbda", "mu"))
        self.assertEqual(model.quadrature_weights, (1.0 / 6.0,))
        self.assertEqual(model.reference_gradients[:3], (-1.0, -1.0, -1.0))
        self.assertIn("trial_grad0", str(model.apply_material_expressions[0]))

    def test_opencl_spirv_module_is_valid_and_uses_opencl_kernel_model(self):
        opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).opencl(max_elements=8, max_nodes=9, max_node_degree=8)
        ir_module = opencl.build_spirv_opencl_module()
        spirv_module = list(ir_module.body.operations)[0]
        self.assertEqual(spirv_module.name, "spirv.module")
        self.assertEqual(
            str(spirv_module.attributes["sfem.codegen.local_apply"]),
            '"linear_elasticity_d3_simplex_apply"',
        )

        module = opencl.render_spirv_opencl_module()

        self.assertIn("spirv.module Logical OpenCL", module)
        self.assertIn('spirv.EntryPoint "Kernel" @linear_elasticity_tet4_opencl_map', module)
        self.assertIn('spirv.EntryPoint "Kernel" @linear_elasticity_tet4_opencl_reduce', module)
        self.assertIn("CrossWorkgroup", module)
        self.assertIn('sfem.codegen.local_apply = "linear_elasticity_d3_simplex_apply"', module)
        self.assertIn('sfem.opencl.memory_model = "OpenCL"', module)

        self._run_mlir_opt(module)

    def test_opencl_lowering_supports_named_mlir_optimization_strategies(self):
        for strategy in MLIROptimizationStrategy:
            opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
                element="TET4",
                vector_size=8,
            ).opencl(
                max_elements=8,
                max_nodes=9,
                max_node_degree=8,
                optimization_strategy=strategy,
            )
            self.assertEqual(opencl.optimization_plan, MLIR_OPTIMIZATION_PLANS[strategy])
            try:
                optimized_module = opencl.optimize_spirv_opencl_module()
                optimized_op = opencl.render_optimized_spirv_module_op()
            except FileNotFoundError as exc:
                self.skipTest(str(exc))

            self.assertIn("spirv.module Logical OpenCL", optimized_module)
            self.assertTrue(optimized_op.startswith("spirv.module"))

    def test_opencl_c_source_is_emitted_from_kernel_model_for_apple_runtime(self):
        opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).opencl(max_elements=8, max_nodes=9, max_node_degree=8)

        source = opencl.lower_to_opencl_c_source()

        self.assertIn("Generated by MatrixFreeOpenCLMLIRLowering", source)
        self.assertIn("__kernel void tet4_le_map", source)
        self.assertIn("__kernel void tet4_le_reduce", source)
        self.assertIn("const float rg[12]", source)
        self.assertIn("stress[0] =", source)
        self.assertIn("grad[0]", source)
        self.assertIn("lmbda", source)
        self.assertIn("mu", source)

    def test_pymlir_package_is_detected_from_repo_venv(self):
        opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity().opencl()
        availability = opencl.pymlir_availability()

        self.assertTrue(availability.available, availability.reason)
        self.assertEqual(availability.module_name, "mlir")

    def test_openmp_mlir_lowers_and_runs_with_mlir_runner(self):
        openmp = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).openmp(max_elements=8, max_nodes=9, max_node_degree=8)

        scf_module = openmp.render_scf_module()
        self.assertIn("scf.parallel", scf_module)
        self.assertIn("scf.for", scf_module)
        self.assertIn("iter_args", scf_module)
        self.assertIn("memref<9xindex>", scf_module)
        self.assertIn("memref<72xindex>", scf_module)
        self.assertIn("memref<96xf32>", scf_module)
        self.assertIn("linear_elasticity_tet4_mlir_apply_openmp", scf_module)

        try:
            result = openmp.run_with_mlir_runner()
        except FileNotFoundError as exc:
            self.skipTest(str(exc))

        self.assertTrue(result.success, result.stderr)
        self.assertEqual(result.entry_result, 0)
        self.assertIn("omp.parallel", result.openmp_module)
        self.assertIn("omp.wsloop", result.openmp_module)

    def test_openmp_lowering_supports_named_mlir_optimization_strategies(self):
        for strategy in MLIROptimizationStrategy:
            openmp = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
                element="TET4",
                vector_size=8,
            ).openmp(
                max_elements=8,
                max_nodes=9,
                max_node_degree=8,
                optimization_strategy=strategy,
            )
            self.assertEqual(openmp.optimization_plan, MLIR_OPTIMIZATION_PLANS[strategy])
            try:
                optimized = openmp.optimize_kernel_scf_module()
                llvm_module = openmp.lower_kernel_to_llvm_module()
            except FileNotFoundError as exc:
                self.skipTest(str(exc))

            self.assertIn("func.func", optimized)
            self.assertIn("llvm.func", llvm_module)

    def test_inspection_artifacts_are_written_for_openmp_and_opencl(self):
        lowering = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        )
        with tempfile.TemporaryDirectory() as tmp:
            tmp = Path(tmp)
            openmp = lowering.openmp(max_elements=8, max_nodes=9, max_node_degree=8)
            opencl = lowering.opencl(max_elements=8, max_nodes=9, max_node_degree=8)
            try:
                openmp_artifacts = openmp.write_inspection_artifacts(tmp / "openmp")
                opencl_artifacts = opencl.write_inspection_artifacts(tmp / "opencl")
            except FileNotFoundError as exc:
                self.skipTest(str(exc))

            scf_mlir = openmp_artifacts.file_for_suffix(".scf.mlir").read_text()
            openmp_mlir = openmp_artifacts.file_for_suffix(".openmp.mlir").read_text()
            llvm_mlir = openmp_artifacts.file_for_suffix(".llvm.mlir").read_text()
            llvm_ir = openmp_artifacts.file_for_suffix(".ll").read_text()
            emitc_mlir = openmp_artifacts.file_for_suffix(".emitc.mlir").read_text()
            c_source = openmp_artifacts.file_for_suffix(".c").read_text()
            spirv_module = opencl_artifacts.file_for_suffix(".spirv.module.mlir").read_text()
            spirv_op = opencl_artifacts.file_for_suffix(".spirv.mlir").read_text()
            opencl_c_source = opencl_artifacts.file_for_suffix(".cl").read_text()
            spirv_binary_size = opencl_artifacts.file_for_suffix(".spv").stat().st_size

        self.assertIn("scf.parallel", scf_mlir)
        self.assertIn("omp.parallel", openmp_mlir)
        self.assertIn("llvm.func", llvm_mlir)
        self.assertIn("define", llvm_ir)
        self.assertIn("emitc.func", emitc_mlir)
        self.assertIn("!emitc.ptr<f32>", emitc_mlir)
        self.assertIn("#include <stdint.h>", c_source)
        self.assertIn("linear_elasticity_tet4_mlir_apply_openmp_c", c_source)
        self.assertIn("spirv.module Logical OpenCL", spirv_module)
        self.assertTrue(spirv_op.startswith("spirv.module"))
        self.assertIn("__kernel void tet4_le_map", opencl_c_source)
        self.assertGreater(spirv_binary_size, 0)

    def test_threaded_two_pass_executor_matches_callback_reference_without_atomics(self):
        model = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).model
        connectivity = np.array(
            [
                [0, 1, 2, 4],
                [1, 3, 2, 4],
                [1, 5, 3, 4],
                [3, 5, 6, 4],
                [0, 2, 7, 4],
                [2, 8, 7, 4],
                [2, 3, 8, 4],
                [3, 6, 8, 4],
            ],
            dtype=np.intp,
        )
        current = np.zeros((9, 3), dtype=np.float32)
        direction = np.arange(27, dtype=np.float32).reshape(9, 3)
        inverted = build_inverted_topology(connectivity, num_nodes=current.shape[0])
        executor = ThreadedEBEExecutor(
            model,
            max_workers=4,
            synchronize_workers=True,
        )

        def local_apply(elem, local_node, component, node, current, direction, parameters):
            scale = np.float32(parameters["mu"] + parameters["lmbda"])
            return np.float32(scale * direction[node, component])

        parameters = {"mu": np.float32(2.0), "lmbda": np.float32(3.0)}
        result = executor.run(current, direction, connectivity, local_apply, parameters, inverted)

        np.testing.assert_array_equal(
            result.residual,
            reference_ebe_residual(model, current, direction, connectivity, local_apply, parameters),
        )
        self.assertEqual(result.padded_scratch_components, 16)
        self.assertGreaterEqual(result.map_worker_count, 2)
        self.assertGreaterEqual(result.reduce_worker_count, 2)

    def test_inverted_topology_and_padding_are_explicit(self):
        connectivity = np.array([[0, 1, 2], [2, 1, 3]], dtype=np.intp)
        inverted = build_inverted_topology(connectivity, num_nodes=4)

        np.testing.assert_array_equal(inverted.node_degree, np.array([1, 2, 2, 1]))
        self.assertEqual(inverted.node_to_element_map.shape, (4, 2))
        self.assertEqual(inverted.node_to_local_idx[2, 0], 2)
        self.assertEqual(inverted.node_to_local_idx[2, 1], 0)
        self.assertEqual(pad_to_vector_width(3, 8), 8)
        self.assertEqual(pad_to_vector_width(16, 8), 16)

    def test_laplace_hex8_tensor_product_sum_factor_ir_is_form_sourced(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
        )

        self.assertEqual(ir.material_name, "laplace")
        self.assertEqual(ir.element_type, "HEX8")
        self.assertEqual(ir.dim, 3)
        self.assertEqual(ir.n_shape, 8)
        self.assertEqual(ir.n_qp, 8)
        self.assertEqual(ir.n_shape_1d, 2)
        self.assertEqual(ir.n_qp_1d, 2)
        self.assertEqual(len(ir.shape_values_1d), 4)
        self.assertEqual(len(ir.shape_gradients_1d), 4)
        self.assertEqual(len(ir.weights_1d), 2)
        self.assertEqual(len(ir.field_gradient_stages), 9)
        self.assertEqual(len(ir.test_gradient_stages), 9)

        first = ir.field_gradient_stages[0]
        self.assertEqual(first.name, "field_gradient_d0_axis0")
        self.assertEqual(first.basis, "grad_1d")
        self.assertEqual(first.lhs_tensor_type, "tensor<2x2xf32>")
        self.assertEqual(first.rhs_tensor_type, "tensor<2x4xf32>")
        self.assertEqual(first.result_tensor_type, "tensor<2x4xf32>")

        last = ir.test_gradient_stages[-1]
        self.assertEqual(last.name, "test_gradient_d2_axis0")
        self.assertEqual(last.basis, "shape_1d_t")
        self.assertEqual(last.lhs_tensor_type, "tensor<2x2xf32>")
        self.assertEqual(last.result_tensor_type, "tensor<2x4xf32>")

    def test_laplace_sum_factor_ir_rejects_non_laplace_form_source(self):
        from codegen.framework.materials.linear_elasticity import material

        with self.assertRaisesRegex(ValueError, "laplace form only"):
            tensor_product_sum_factor_ir_from_material(
                material,
                element="HEX8",
                vector_size=8,
            )

    def test_laplace_hex8_sum_factor_reference_pipeline_matches_direct_tensor_product(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
        )
        form_ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
        )
        evaluator = TensorProductSumFactorReferenceEvaluator(ir)
        u = tuple(0.5 + 0.03125 * (i + 1) for i in range(ir.n_shape))

        for derivative in range(ir.dim):
            field = evaluator.field_gradient(u, derivative)
            direct_field = evaluator.direct_field_gradient(u, derivative)
            self.assertLessEqual(max(abs(a - b) for a, b in zip(field, direct_field)), 1.0e-12)

            q_values = tuple(0.25 + 0.015625 * (derivative + 1) * (i + 1) for i in range(ir.n_qp))
            test = evaluator.test_contraction(q_values, derivative)
            direct_test = evaluator.direct_test_contraction(q_values, derivative)
            self.assertLessEqual(max(abs(a - b) for a, b in zip(test, direct_test)), 1.0e-12)

        residual = evaluator.apply_laplace_local(u)
        direct_residual = evaluator.direct_laplace_local(u, kappa=form_ir.parameter_default)
        self.assertLessEqual(max(abs(a - b) for a, b in zip(residual, direct_residual)), 1.0e-12)

    def test_laplace_hex8_quadrature_mismatch_sum_factor_reference_matches_direct_tensor_product(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
            quadrature_order=3,
        )
        form_ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
            quadrature_order=3,
        )
        evaluator = TensorProductSumFactorReferenceEvaluator(ir)
        u = tuple(0.5 + 0.03125 * (i + 1) for i in range(ir.n_shape))

        self.assertEqual(ir.n_shape_1d, 2)
        self.assertEqual(ir.n_qp_1d, 3)
        for derivative in range(ir.dim):
            field = evaluator.field_gradient(u, derivative)
            direct_field = evaluator.direct_field_gradient(u, derivative)
            self.assertEqual(len(field), ir.n_qp)
            self.assertLessEqual(max(abs(a - b) for a, b in zip(field, direct_field)), 1.0e-12)

        residual = evaluator.apply_laplace_local(u)
        direct_residual = evaluator.direct_laplace_local(u, kappa=form_ir.parameter_default)
        self.assertLessEqual(max(abs(a - b) for a, b in zip(residual, direct_residual)), 1.0e-12)

    def test_laplace_quad4_sum_factor_linalg_mlir_validates(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_linalg_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_generic_gpu"', module)
        self.assertIn("linalg.matmul", module)
        self.assertEqual(module.count("linalg.matmul"), 8)
        self.assertIn("@sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0", module)
        self.assertIn("@sfem_laplace_quad4_sum_factor_test_gradient_d1_axis0", module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_sum_factor_vector_mlir_validates_for_matrix_unit_boundary(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_vector_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_vector"', module)
        self.assertEqual(module.count("= vector.matrix_multiply"), 8)
        self.assertIn("@sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_vector", module)
        self.assertIn("vector<4xf32>", module)
        self.assertIn("lhs_rows = 2 : i32", module)
        self.assertIn("lhs_columns = 2 : i32", module)
        self.assertIn("rhs_columns = 2 : i32", module)
        self.assertIn('sfem.vector.matrix_multiply = "flattened"', module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_sum_factor_matrix_unit_mlir_uses_padded_tile_dimensions(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_matrix_unit_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit"', module)
        self.assertIn("sfem.matrix_unit.tile_size = 8 : i64", module)
        self.assertEqual(module.count("= vector.matrix_multiply"), 8)
        self.assertIn("@sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_matrix_unit", module)
        self.assertIn("vector<64xf32>", module)
        self.assertIn("lhs_rows = 8 : i32", module)
        self.assertIn("lhs_columns = 8 : i32", module)
        self.assertIn("rhs_columns = 8 : i32", module)
        self.assertIn("sfem.matrix_unit.raw_lhs_rows = 2 : i64", module)
        self.assertIn('sfem.vector.matrix_multiply = "padded"', module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_sum_factor_matrix_unit_memref_mlir_packs_raw_buffers(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_matrix_unit_memref_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_memref"', module)
        self.assertIn("@sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_matrix_unit_memref", module)
        self.assertIn("memref<2x2xf32>", module)
        self.assertIn("vector.transfer_read", module)
        self.assertIn("vector.shape_cast", module)
        self.assertIn("vector.matrix_multiply", module)
        self.assertIn("vector.transfer_write", module)
        self.assertIn("vector<8x8xf32>", module)
        self.assertIn("vector<64xf32>", module)
        self.assertIn("lhs_rows = 8 : i32", module)
        self.assertIn("lhs_columns = 8 : i32", module)
        self.assertIn("rhs_columns = 8 : i32", module)
        self.assertIn('sfem.vector.matrix_multiply = "padded_memref"', module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_sum_factor_matrix_unit_pipeline_chains_stage_functions(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_matrix_unit_pipeline_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_pipeline"', module)
        self.assertIn("@sfem_laplace_quad4_sum_factor_field_gradient_d0_matrix_unit_pipeline", module)
        self.assertIn("@sfem_laplace_quad4_sum_factor_test_gradient_d1_matrix_unit_pipeline", module)
        self.assertIn("@sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_matrix_unit_memref", module)
        self.assertEqual(module.count("= vector.matrix_multiply"), 8)
        self.assertEqual(module.count("func.call @"), 8)
        self.assertEqual(module.count("memref.alloc"), 8)
        self.assertEqual(module.count("memref.dealloc"), 8)
        self.assertIn("%bridge1 = memref.alloc()", module)
        self.assertIn("memref.load %scratch0", module)
        self.assertIn("memref.store %bridge", module)
        self.assertIn('sfem.vector.matrix_multiply = "padded_memref_pipeline"', module)
        self.assertIn("func.call @sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_matrix_unit_memref", module)
        self.assertIn("func.call @sfem_laplace_quad4_sum_factor_field_gradient_d0_axis1_matrix_unit_memref", module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_sum_factor_gpu_mlir_validates_without_hot_loop_branches(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_gpu_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_gpu"', module)
        self.assertIn("gpu.module @sfem_laplace_quad4_sum_factor_gpu_kernels", module)
        self.assertEqual(module.count("gpu.launch_func"), 8)
        self.assertEqual(module.count("gpu.func @"), 8)
        self.assertIn("threads in (%threads_x, %threads_y, %c1)", module)
        self.assertIn("scf.for %k = %c0 to %contract_extent", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_hex8_sum_factor_gpu_mlir_carries_all_3d_stages(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_gpu_module()

        self.assertEqual(module.count("gpu.launch_func"), 18)
        self.assertEqual(module.count("gpu.func @"), 18)
        self.assertIn("@sfem_laplace_hex8_sum_factor_field_gradient_d2_axis2_kernel", module)
        self.assertIn("@sfem_laplace_hex8_sum_factor_test_gradient_d2_axis0_kernel", module)
        self.assertIn("memref<2x4xf32>", module)

        self._run_mlir_opt(module)

    def test_laplace_hex8_quadrature_mismatch_matrix_unit_pipeline_bridges_stage_views(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
            quadrature_order=3,
        )
        self.assertEqual(ir.n_shape_1d, 2)
        self.assertEqual(ir.n_qp_1d, 3)

        lowering = TensorProductSumFactorMLIRLowering(ir)
        module = lowering.render_matrix_unit_pipeline_module()

        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_pipeline"', module)
        self.assertIn("%bridge1 = memref.alloc() : memref<2x6xf32>", module)
        self.assertIn("%bridge2 = memref.alloc() : memref<2x9xf32>", module)
        self.assertIn("memref.load %scratch0", module)
        self.assertIn("memref.store %bridge", module)
        self.assertEqual(module.count("= vector.matrix_multiply"), 18)
        self.assertEqual(module.count("func.call @"), 18)
        self.assertEqual(module.count("memref.alloc"), 24)
        self.assertNotIn("memref.reinterpret_cast", module)

        self._run_mlir_opt(module)

    def test_laplace_hex27_high_order_sum_factor_gpu_and_metal_sources_validate(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX27",
            vector_size=8,
        )
        self.assertEqual(ir.n_shape_1d, 3)
        self.assertEqual(ir.n_qp_1d, 3)
        self.assertEqual(ir.n_shape, 27)
        self.assertEqual(ir.n_qp, 27)
        self.assertEqual(len(ir.field_gradient_stages), 9)
        self.assertEqual(len(ir.test_gradient_stages), 9)

        first = ir.field_gradient_stages[0]
        self.assertEqual(first.lhs_tensor_type, "tensor<3x3xf32>")
        self.assertEqual(first.rhs_tensor_type, "tensor<3x9xf32>")
        self.assertEqual(first.result_tensor_type, "tensor<3x9xf32>")

        lowering = TensorProductSumFactorMLIRLowering(ir)
        linalg_pipeline_module = lowering.render_linalg_pipeline_module()
        self.assertEqual(linalg_pipeline_module.count("linalg.matmul"), 18)
        self.assertEqual(linalg_pipeline_module.count("func.call @"), 18)
        self.assertEqual(linalg_pipeline_module.count("linalg.generic"), 12)
        self.assertIn('sfem.lowering = "tensor_product_sum_factor_linalg_pipeline"', linalg_pipeline_module)
        self.assertIn("@sfem_laplace_hex27_sum_factor_field_gradient_d2_linalg_pipeline", linalg_pipeline_module)
        self.assertIn("@sfem_laplace_hex27_sum_factor_test_gradient_d2_linalg_pipeline", linalg_pipeline_module)
        self._run_mlir_opt(linalg_pipeline_module)

        vector_module = lowering.render_vector_module()
        self.assertEqual(vector_module.count("= vector.matrix_multiply"), 18)
        self.assertIn("vector<9xf32>", vector_module)
        self.assertIn("vector<27xf32>", vector_module)
        self.assertIn("lhs_rows = 3 : i32", vector_module)
        self.assertIn("rhs_columns = 9 : i32", vector_module)
        self._run_mlir_opt(vector_module)

        matrix_unit_module = lowering.render_matrix_unit_module()
        self.assertEqual(matrix_unit_module.count("= vector.matrix_multiply"), 18)
        self.assertIn("sfem.matrix_unit.tile_size = 8 : i64", matrix_unit_module)
        self.assertIn("vector<64xf32>", matrix_unit_module)
        self.assertIn("vector<128xf32>", matrix_unit_module)
        self.assertIn("lhs_rows = 8 : i32", matrix_unit_module)
        self.assertIn("lhs_columns = 8 : i32", matrix_unit_module)
        self.assertIn("rhs_columns = 16 : i32", matrix_unit_module)
        self.assertIn("sfem.matrix_unit.raw_lhs_rows = 3 : i64", matrix_unit_module)
        self.assertIn("sfem.matrix_unit.raw_rhs_columns = 9 : i64", matrix_unit_module)
        self._run_mlir_opt(matrix_unit_module)

        matrix_unit_memref_module = lowering.render_matrix_unit_memref_module()
        self.assertEqual(matrix_unit_memref_module.count("= vector.matrix_multiply"), 18)
        self.assertIn("memref<3x3xf32>", matrix_unit_memref_module)
        self.assertIn("memref<3x9xf32>", matrix_unit_memref_module)
        self.assertIn("vector.transfer_read", matrix_unit_memref_module)
        self.assertIn("vector.transfer_write", matrix_unit_memref_module)
        self.assertIn("vector<8x16xf32>", matrix_unit_memref_module)
        self.assertIn("rhs_columns = 16 : i32", matrix_unit_memref_module)
        self.assertIn("sfem.matrix_unit.raw_rhs_columns = 9 : i64", matrix_unit_memref_module)
        self._run_mlir_opt(matrix_unit_memref_module)

        matrix_unit_pipeline_module = lowering.render_matrix_unit_pipeline_module()
        self.assertEqual(matrix_unit_pipeline_module.count("= vector.matrix_multiply"), 18)
        self.assertEqual(matrix_unit_pipeline_module.count("func.call @"), 18)
        self.assertEqual(matrix_unit_pipeline_module.count("memref.alloc"), 24)
        self.assertIn("@sfem_laplace_hex27_sum_factor_field_gradient_d2_matrix_unit_pipeline", matrix_unit_pipeline_module)
        self.assertIn("@sfem_laplace_hex27_sum_factor_test_gradient_d2_matrix_unit_pipeline", matrix_unit_pipeline_module)
        self.assertIn("vector<8x16xf32>", matrix_unit_pipeline_module)
        self.assertIn("rhs_columns = 16 : i32", matrix_unit_pipeline_module)
        self._run_mlir_opt(matrix_unit_pipeline_module)

        gpu_module = lowering.render_gpu_module()
        self.assertEqual(gpu_module.count("gpu.launch_func"), 18)
        self.assertEqual(gpu_module.count("gpu.func @"), 18)
        self.assertIn("memref<3x9xf32>", gpu_module)
        self.assertIn("arith.constant 3 : index", gpu_module)
        self.assertNotIn("scf.if", gpu_module)
        self._run_mlir_opt(gpu_module)

        metal_source = lowering.render_metal_source()
        self.assertEqual(metal_source.count("kernel void"), 18)
        self.assertIn("for (uint k = 0; k < 3; ++k)", metal_source)
        self.assertIn("basis[row * 3 + k] * operand[k * 9 + col]", metal_source)
        self.assertNotIn("if (", metal_source)

    def test_laplace_quad4_sum_factor_metal_source_is_branch_free(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        source = lowering.render_metal_source()

        self.assertIn("#include <metal_stdlib>", source)
        self.assertIn("kernel void sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_metal", source)
        self.assertEqual(source.count("kernel void"), 8)
        self.assertIn("[[thread_position_in_grid]]", source)
        self.assertIn("#pragma unroll", source)
        self.assertIn("for (uint k = 0; k < 2; ++k)", source)
        self.assertNotIn("if (", source)

    def test_laplace_sum_factor_inspection_artifacts_are_written(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        with tempfile.TemporaryDirectory() as tmp:
            artifacts = lowering.write_inspection_artifacts(tmp)

            linalg_module = artifacts.file_for_suffix(".linalg.mlir").read_text()
            linalg_pipeline_module = artifacts.file_for_suffix(".linalg_pipeline.mlir").read_text()
            vector_module = artifacts.file_for_suffix(".vector.mlir").read_text()
            matrix_unit_module = artifacts.file_for_suffix(".matrix_unit.mlir").read_text()
            matrix_unit_memref_module = artifacts.file_for_suffix(".matrix_unit_memref.mlir").read_text()
            matrix_unit_pipeline_module = artifacts.file_for_suffix(".matrix_unit_pipeline.mlir").read_text()
            gpu_module = artifacts.file_for_suffix(".gpu.mlir").read_text()
            metal_source = artifacts.file_for_suffix(".metal").read_text()
            harness = artifacts.file_for_suffix(".metal_smoke.mm").read_text()

        self.assertIn("linalg.matmul", linalg_module)
        self.assertIn('sfem.lowering = "tensor_product_sum_factor_linalg_pipeline"', linalg_pipeline_module)
        self.assertIn("func.call @", linalg_pipeline_module)
        self.assertIn("linalg.generic", linalg_pipeline_module)
        self.assertIn("vector.matrix_multiply", vector_module)
        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit"', matrix_unit_module)
        self.assertIn("sfem.matrix_unit.tile_size = 8 : i64", matrix_unit_module)
        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_memref"', matrix_unit_memref_module)
        self.assertIn("vector.transfer_read", matrix_unit_memref_module)
        self.assertIn("vector.transfer_write", matrix_unit_memref_module)
        self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_pipeline"', matrix_unit_pipeline_module)
        self.assertIn("func.call @", matrix_unit_pipeline_module)
        self.assertIn("memref.alloc", matrix_unit_pipeline_module)
        self.assertIn('sfem.lowering = "tensor_product_sum_factor_gpu"', gpu_module)
        self.assertIn("gpu.launch_func", gpu_module)
        self.assertIn("kernel void sfem_laplace_quad4_sum_factor_field_gradient_d0_axis0_metal", metal_source)
        self.assertIn("newLibraryWithSource", harness)
        self.assertNotIn("scf.if", gpu_module)
        self.assertNotIn("arith.cmpi", gpu_module)
        self.assertNotIn("if (", metal_source)

        self._run_mlir_opt(linalg_module)
        self._run_mlir_opt(linalg_pipeline_module)
        self._run_mlir_opt(vector_module)
        self._run_mlir_opt(matrix_unit_module)
        self._run_mlir_opt(matrix_unit_memref_module)
        self._run_mlir_opt(matrix_unit_pipeline_module)
        self._run_mlir_opt(gpu_module)

    def test_laplace_quad4_sum_factor_runs_on_metal_when_device_is_available(self):
        from codegen.framework.materials.laplace import material

        clang = shutil.which("xcrun")
        if clang is None:
            self.skipTest("xcrun is not available for Metal runtime test")

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        with tempfile.TemporaryDirectory() as tmp:
            result = lowering.run_metal_smoke_test(tmp)

        self.assertTrue(result.harness_path.name.endswith("_metal_smoke.mm"))
        if not result.compiled:
            self.fail(result.compile_stderr)
        if result.no_default_device:
            self.skipTest("Metal runtime has no default MTLDevice")
        self.assertTrue(result.success, result.run_stderr)

    def test_laplace_quad4_form_ir_emits_fused_tensor_product_metal_apply(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        self.assertEqual(ir.to_dict()["form"], "laplace")
        self.assertEqual(ir.parameter_name, "kappa")
        self.assertEqual(ir.parameter_default, 1.0)
        self.assertEqual(ir.sum_factor.element_type, "QUAD4")

        lowering = TensorProductLaplaceFormMetalLowering(ir)
        source = lowering.render_metal_source()
        self.assertIn("kernel void sfem_laplace_quad4_sum_factor_laplace_apply_metal", source)
        self.assertIn("constant float sfem_shape_1d[4]", source)
        self.assertIn("constant float sfem_grad_1d[4]", source)
        self.assertIn("constant float sfem_weight_1d[2]", source)
        self.assertIn("constant float &kappa [[buffer(2)]]", source)
        self.assertIn("for (uint qy = 0; qy < 2; ++qy)", source)
        self.assertIn("for (uint sx = 0; sx < 2; ++sx)", source)
        self.assertIn("test_gx * grad_u_x + test_gy * grad_u_y", source)
        self.assertNotIn("if (", source)

        harness = lowering.render_metal_smoke_test_harness()
        self.assertIn("reference_apply", harness)
        self.assertIn("std::fabs(result[i] - expected[i])", harness)
        self.assertIn("newLibraryWithSource", harness)

    def test_laplace_quad4_form_ir_emits_fused_tensor_product_gpu_mlir(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormGPULowering(ir)
        module = lowering.render_gpu_module()

        self.assertIn('sfem.lowering = "tensor_product_laplace_form_gpu"', module)
        self.assertIn('sfem.form = "laplace"', module)
        self.assertIn('sfem.parameter = "kappa"', module)
        self.assertEqual(module.count("gpu.launch_func"), 1)
        self.assertEqual(module.count("gpu.func @"), 1)
        self.assertIn("memref<4xf32>", module)
        self.assertIn("memref<1xf32>", module)
        self.assertIn("scf.for %qy", module)
        self.assertIn("scf.for %sx", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_reference_evaluator_checks_local_and_ebe_semantics(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        evaluator = TensorProductLaplaceReferenceEvaluator(ir)

        constant = evaluator.apply_local((1.0, 1.0, 1.0, 1.0))
        self.assertLessEqual(max(abs(value) for value in constant), 1.0e-6)

        connectivity = ((0, 1, 3, 2), (1, 4, 5, 3))
        node_degree = (1, 2, 1, 2, 1, 1)
        node_to_element_map = ((0, 0), (0, 1), (0, 0), (0, 1), (1, 0), (1, 0))
        node_to_local_idx = ((0, 0), (1, 0), (3, 0), (2, 3), (1, 0), (2, 0))
        u = tuple(0.5 + 0.03125 * (i + 1) for i in range(6))
        element_out, out = evaluator.apply_ebe(
            connectivity,
            u,
            node_degree,
            node_to_element_map,
            node_to_local_idx,
        )

        self.assertEqual(len(element_out), 2)
        self.assertEqual(len(element_out[0]), 4)
        self.assertAlmostEqual(out[0], element_out[0][0])
        self.assertAlmostEqual(out[1], element_out[0][1] + element_out[1][0])
        self.assertAlmostEqual(out[3], element_out[0][2] + element_out[1][3])

    def test_laplace_form_inspection_artifacts_are_written_for_generic_gpu_and_metal(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormGPULowering(ir)
        with tempfile.TemporaryDirectory() as tmp:
            artifacts = lowering.write_inspection_artifacts(tmp)

            gpu_module = artifacts.file_for_suffix(".gpu.mlir").read_text()
            metal_source = artifacts.file_for_suffix(".metal").read_text()
            harness = artifacts.file_for_suffix(".metal_smoke.mm").read_text()

        self.assertIn('sfem.lowering = "tensor_product_laplace_form_gpu"', gpu_module)
        self.assertIn("gpu.func @sfem_laplace_quad4_sum_factor_laplace_apply_kernel", gpu_module)
        self.assertIn("kernel void sfem_laplace_quad4_sum_factor_laplace_apply_metal", metal_source)
        self.assertIn("reference_apply", harness)
        self.assertIn("std::fabs(result[i] - expected[i])", harness)
        self.assertNotIn("scf.if", gpu_module)
        self.assertNotIn("arith.cmpi", gpu_module)
        self.assertNotIn("if (", metal_source)

        self._run_mlir_opt(gpu_module)

    def test_laplace_quad4_form_ir_emits_batched_ebe_gpu_map(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormBatchedGPULowering(
            ir,
            max_elements=8,
            max_nodes=17,
        )
        module = lowering.render_gpu_module()

        self.assertIn('sfem.lowering = "tensor_product_laplace_ebe_gpu_map"', module)
        self.assertIn('sfem.mesh_phase = "ebe_map"', module)
        self.assertIn("memref<8x4xindex>", module)
        self.assertIn("memref<17xf32>", module)
        self.assertIn("memref<8x4xf32>", module)
        self.assertIn("%elem = gpu.block_id x", module)
        self.assertIn("blocks in (%blocks, %c1, %c1)", module)
        self.assertIn("threads in (%threads, %c1, %c1)", module)
        self.assertIn("%node = memref.load %connectivity[%elem, %trial]", module)
        self.assertIn("%coeff = memref.load %u[%node]", module)
        self.assertIn("memref.store %sum_y, %element_out[%elem, %row]", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_hex27_form_ir_emits_high_order_batched_ebe_gpu_map_artifact(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX27",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormBatchedGPULowering(
            ir,
            max_elements=4,
            max_nodes=64,
        )
        with tempfile.TemporaryDirectory() as tmp:
            artifacts = lowering.write_inspection_artifacts(tmp)
            module = artifacts.file_for_suffix(".ebe.gpu.mlir").read_text()

        self.assertIn("memref<4x27xindex>", module)
        self.assertIn("memref<64xf32>", module)
        self.assertIn("memref<4x27xf32>", module)
        self.assertIn("arith.constant 27 : index", module)
        self.assertIn("scf.for %qz", module)
        self.assertIn("scf.for %sz", module)
        self.assertIn("%node = memref.load %connectivity[%elem, %trial]", module)
        self.assertIn("memref.store %sum_z, %element_out[%elem, %row]", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_form_ir_emits_full_ebe_gpu_map_reduce(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEGPULowering(
            ir,
            max_elements=8,
            max_nodes=17,
            max_node_degree=4,
        )
        module = lowering.render_gpu_module()

        self.assertIn('sfem.lowering = "tensor_product_laplace_ebe_gpu"', module)
        self.assertIn('sfem.mesh_phases = "ebe_map,ebe_reduce"', module)
        self.assertEqual(module.count("gpu.launch_func"), 2)
        self.assertIn("@sfem_laplace_quad4_sum_factor_laplace_apply_ebe_map_kernel", module)
        self.assertIn("@sfem_laplace_quad4_sum_factor_laplace_apply_ebe_reduce_kernel", module)
        self.assertIn("memref<8x4xindex>", module)
        self.assertIn("memref<8x4xf32>", module)
        self.assertIn("memref<17xindex>", module)
        self.assertIn("memref<17x4xindex>", module)
        self.assertIn("memref<17xf32>", module)
        self.assertIn("%node = gpu.thread_id x", module)
        self.assertIn("%degree = memref.load %node_degree[%node]", module)
        self.assertIn("scf.for %i = %c0 to %degree", module)
        self.assertIn("%elem = memref.load %node_to_element_map[%node, %i]", module)
        self.assertIn("%local = memref.load %node_to_local_idx[%node, %i]", module)
        self.assertIn("%value = memref.load %element_out[%elem, %local]", module)
        self.assertIn("memref.store %sum, %out[%node]", module)
        self.assertNotIn("atomic", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_full_ebe_gpu_manifest_topology_tokens_are_present(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEGPULowering(
            ir,
            max_elements=8,
            max_nodes=17,
            max_node_degree=4,
        )
        with tempfile.TemporaryDirectory() as tmp:
            artifacts = lowering.write_inspection_artifacts(tmp)
            module = artifacts.file_for_suffix(".ebe.full.gpu.mlir").read_text()

        self.assertIn('sfem.mesh_phases = "ebe_map,ebe_reduce"', module)
        self.assertGreater(module.count("_ebe_map_kernel"), 1)
        self.assertGreater(module.count("_ebe_reduce_kernel"), 1)
        self.assertIn("%node = gpu.thread_id x", module)
        self.assertIn("%elem = memref.load %node_to_element_map[%node, %i]", module)
        self.assertIn("%local = memref.load %node_to_local_idx[%node, %i]", module)
        self.assertIn("%value = memref.load %element_out[%elem, %local]", module)
        self.assertIn("memref.store %sum, %out[%node]", module)
        self.assertNotIn("atomic", module)

    def test_laplace_hex27_form_ir_emits_full_ebe_gpu_map_reduce_artifact(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX27",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEGPULowering(
            ir,
            max_elements=4,
            max_nodes=64,
            max_node_degree=8,
        )
        with tempfile.TemporaryDirectory() as tmp:
            artifacts = lowering.write_inspection_artifacts(tmp)
            module = artifacts.file_for_suffix(".ebe.full.gpu.mlir").read_text()

        self.assertIn("memref<4x27xindex>", module)
        self.assertIn("memref<4x27xf32>", module)
        self.assertIn("memref<64x8xindex>", module)
        self.assertIn("arith.constant 27 : index", module)
        self.assertIn("scf.for %qz", module)
        self.assertIn("scf.for %sz", module)
        self.assertIn("scf.for %i = %c0 to %degree", module)
        self.assertIn("memref.store %sum_z, %element_out[%elem, %row]", module)
        self.assertIn("memref.store %sum, %out[%node]", module)
        self.assertNotIn("atomic", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_quad4_form_ir_emits_ebe_metal_map_reduce_source_and_harness(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEMetalLowering(
            ir,
            max_elements=2,
            max_nodes=7,
            max_node_degree=2,
        )
        source = lowering.render_metal_source()

        self.assertIn("kernel void sfem_laplace_quad4_sum_factor_laplace_apply_ebe_map_metal", source)
        self.assertIn("kernel void sfem_laplace_quad4_sum_factor_laplace_apply_ebe_reduce_metal", source)
        self.assertIn("device const uint *connectivity [[buffer(0)]]", source)
        self.assertIn("device float *element_out [[buffer(2)]]", source)
        self.assertIn("const uint elem = tid.y;", source)
        self.assertIn("const uint node = connectivity[elem * 4 + trial];", source)
        self.assertIn("const float coeff = u[node];", source)
        self.assertIn("element_out[elem * 4 + row] = value;", source)
        self.assertIn("const uint degree = node_degree[node];", source)
        self.assertIn("const uint map_index = node * 2 + i;", source)
        self.assertIn("acc += element_out[elem * 4 + local];", source)
        self.assertNotIn("if (", source)

        harness = lowering.render_metal_smoke_test_harness()
        self.assertIn("reference_apply", harness)
        self.assertIn("expected_element", harness)
        self.assertIn("node_to_element_map", harness)
        self.assertIn("newFunctionWithName", harness)
        self.assertIn("dispatchThreads:MTLSizeMake(4, 2, 1)", harness)
        self.assertIn("dispatchThreads:MTLSizeMake(7, 1, 1)", harness)
        self.assertIn("std::fabs(result[i] - expected[i])", harness)

    def test_laplace_ebe_metal_inspection_artifacts_are_written(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEMetalLowering(
            ir,
            max_elements=2,
            max_nodes=6,
            max_node_degree=2,
        )
        with tempfile.TemporaryDirectory() as tmp:
            artifacts = lowering.write_inspection_artifacts(tmp)
            source = artifacts.file_for_suffix(".ebe.metal").read_text()
            harness = artifacts.file_for_suffix(".ebe_metal_smoke.mm").read_text()

        self.assertIn("ebe_map_metal", source)
        self.assertIn("ebe_reduce_metal", source)
        self.assertIn("expected_element", harness)

    def test_laplace_hex27_ebe_metal_smoke_harness_uses_high_order_fixture(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX27",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEMetalLowering(
            ir,
            max_elements=2,
            max_nodes=53,
            max_node_degree=2,
        )
        harness = lowering.render_metal_smoke_test_harness()

        self.assertIn("const unsigned connectivity[2 * 27]", harness)
        self.assertIn("const unsigned node_degree[53]", harness)
        self.assertIn("const unsigned node_to_element_map[53 * 2]", harness)
        self.assertIn("float local_u[27]", harness)
        self.assertIn("dispatchThreads:MTLSizeMake(27, 2, 1)", harness)
        self.assertIn("dispatchThreads:MTLSizeMake(53, 1, 1)", harness)
        self.assertIn("sfem_laplace_hex27_sum_factor_laplace_apply_ebe_map_metal", harness)
        self.assertIn("sfem_laplace_hex27_sum_factor_laplace_apply_ebe_reduce_metal", harness)

    def test_laplace_ebe_metal_runs_when_device_is_available(self):
        from codegen.framework.materials.laplace import material

        if shutil.which("xcrun") is None:
            self.skipTest("xcrun is not available for Metal runtime test")

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormEBEMetalLowering(
            ir,
            max_elements=2,
            max_nodes=6,
            max_node_degree=2,
        )
        with tempfile.TemporaryDirectory() as tmp:
            result = lowering.run_metal_smoke_test(tmp)

        self.assertTrue(result.harness_path.name.endswith("_ebe_metal_smoke.mm"))
        if not result.compiled:
            self.fail(result.compile_stderr)
        if result.no_default_device:
            self.skipTest("Metal runtime has no default MTLDevice")
        self.assertTrue(result.success, result.run_stderr)

    def test_tensor_product_laplace_artifact_driver_emits_manifest_and_valid_mlir(self):
        script = Path("python/codegen/framework/mlir/scripts/tensor_product_laplace_artifacts.py")
        env = dict(os.environ)
        pythonpath = env.get("PYTHONPATH")
        env["PYTHONPATH"] = "python" if not pythonpath else "python:" + pythonpath

        with tempfile.TemporaryDirectory() as tmp:
            command = [
                sys.executable,
                str(script),
                "--output-dir",
                tmp,
                "--element",
                "QUAD4",
                "--max-elements",
                "2",
                "--max-nodes",
                "6",
                "--max-node-degree",
                "2",
                "--verify-reference",
                "--verify-performance-shape",
                "--validate-mlir",
                "--probe-iree-metal",
                "--probe-metal-toolchain",
            ]
            result = subprocess.run(
                command,
                check=True,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
            )
            manifest_path = Path(result.stdout.strip().splitlines()[-1])
            manifest = json.loads(manifest_path.read_text())
            sum_factor_ir_path = next(
                Path(path) for path in manifest["artifacts"]["sfem_ir"] if path.endswith(".sum_factor.ir.json")
            )
            form_ir_path = next(
                Path(path) for path in manifest["artifacts"]["sfem_ir"] if path.endswith(".laplace_form.ir.json")
            )
            sum_factor_ir = json.loads(sum_factor_ir_path.read_text())
            form_ir = json.loads(form_ir_path.read_text())

        self.assertEqual(manifest["material"], "laplace")
        self.assertEqual(manifest["element"], "QUAD4")
        self.assertEqual(manifest["n_shape"], 4)
        self.assertIn("sfem_ir", manifest["artifacts"])
        self.assertIn("sum_factor", manifest["artifacts"])
        self.assertIn("ebe_full", manifest["artifacts"])
        self.assertIn("ebe_metal", manifest["artifacts"])
        self.assertTrue(any(path.endswith(".sum_factor.ir.json") for path in manifest["artifacts"]["sfem_ir"]))
        self.assertTrue(any(path.endswith(".laplace_form.ir.json") for path in manifest["artifacts"]["sfem_ir"]))
        self.assertTrue(any(path.endswith(".linalg_pipeline.mlir") for path in manifest["artifacts"]["sum_factor"]))
        self.assertTrue(any(path.endswith(".vector.mlir") for path in manifest["artifacts"]["sum_factor"]))
        self.assertTrue(any(path.endswith(".matrix_unit.mlir") for path in manifest["artifacts"]["sum_factor"]))
        self.assertTrue(any(path.endswith(".matrix_unit_memref.mlir") for path in manifest["artifacts"]["sum_factor"]))
        self.assertTrue(any(path.endswith(".matrix_unit_pipeline.mlir") for path in manifest["artifacts"]["sum_factor"]))
        self.assertTrue(any(path.endswith(".ebe.full.gpu.mlir") for path in manifest["artifacts"]["ebe_full"]))
        self.assertTrue(any(path.endswith(".ebe.metal") for path in manifest["artifacts"]["ebe_metal"]))
        self.assertTrue(any(path.endswith(".ebe_metal_smoke.mm") for path in manifest["artifacts"]["ebe_metal"]))
        self.assertEqual(sum_factor_ir["element_type"], "QUAD4")
        self.assertEqual(sum_factor_ir["n_shape_1d"], 2)
        self.assertEqual(sum_factor_ir["n_qp_1d"], 2)
        self.assertEqual(len(sum_factor_ir["field_gradient_stages"]), 4)
        self.assertEqual(len(sum_factor_ir["test_gradient_stages"]), 4)
        self.assertEqual(form_ir["form"], "laplace")
        self.assertEqual(form_ir["parameter_name"], "kappa")
        self.assertEqual(len(manifest["reference_verification"]), 2)
        sum_factor_reference = next(
            item for item in manifest["reference_verification"] if item["name"] == "tensor_product_sum_factor_pipeline_reference"
        )
        laplace_reference = next(
            item for item in manifest["reference_verification"] if item["name"] == "tensor_product_laplace_cpu_reference"
        )
        self.assertTrue(sum_factor_reference["ok"], sum_factor_reference)
        self.assertLessEqual(sum_factor_reference["max_field_gradient_diff"], 1.0e-6)
        self.assertLessEqual(sum_factor_reference["max_test_contraction_diff"], 1.0e-6)
        self.assertLessEqual(sum_factor_reference["max_laplace_residual_diff"], 1.0e-6)
        self.assertTrue(laplace_reference["ok"], laplace_reference)
        self.assertLessEqual(laplace_reference["max_abs_constant_residual"], 1.0e-5)
        self.assertTrue(manifest["performance_shape"])
        self.assertTrue(all(item["ok"] for item in manifest["performance_shape"]), manifest["performance_shape"])
        self.assertTrue(any(item["name"] == "linalg_matmul" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "linalg_pipeline_calls" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "linalg_pipeline_bridges" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "vector_matrix_multiply" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "matrix_unit_vector_matrix_multiply" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "matrix_unit_memref_transfer_read" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "matrix_unit_memref_transfer_write" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "matrix_unit_pipeline_calls" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "matrix_unit_pipeline_scratch" for item in manifest["performance_shape"]))
        self.assertTrue(any(item["name"] == "matrix_unit_alignment" for item in manifest["performance_shape"]))
        ebe_topology = next(
            item for item in manifest["performance_shape"] if item["name"] == "ebe_gpu_topology"
        )
        self.assertTrue(ebe_topology["ok"], ebe_topology)
        self.assertEqual(ebe_topology["missing_tokens"], [])
        self.assertEqual(ebe_topology["found_tokens"], [])
        self.assertEqual(len(manifest["iree_metal"]), 1)
        self.assertEqual(manifest["iree_metal"][0]["name"], "sum_factor_linalg_pipeline_to_metal_vmfb")
        if shutil.which("iree-compile") is None:
            self.assertTrue(manifest["iree_metal"][0]["skipped"])
            self.assertIn("iree-compile is not available", manifest["iree_metal"][0]["reason"])
        else:
            self.assertTrue(manifest["iree_metal"][0]["ok"], manifest["iree_metal"][0])
            self.assertTrue(manifest["iree_metal"][0]["output_vmfb"].endswith(".linalg_pipeline.metal.vmfb"))
        self.assertTrue(manifest["metal_toolchain"])
        if shutil.which("xcrun") is None:
            self.assertTrue(all(item["skipped"] for item in manifest["metal_toolchain"]))
        else:
            self.assertTrue(all("returncode" in item for item in manifest["metal_toolchain"]))
        self.assertTrue(manifest["mlir_validation"])
        self.assertTrue(all(item["ok"] for item in manifest["mlir_validation"]), manifest["mlir_validation"])

    def test_tensor_product_laplace_artifact_driver_handles_quadrature_mismatch_pipeline_views(self):
        script = Path("python/codegen/framework/mlir/scripts/tensor_product_laplace_artifacts.py")
        env = dict(os.environ)
        pythonpath = env.get("PYTHONPATH")
        env["PYTHONPATH"] = "python" if not pythonpath else "python:" + pythonpath

        with tempfile.TemporaryDirectory() as tmp:
            command = [
                sys.executable,
                str(script),
                "--output-dir",
                tmp,
                "--element",
                "HEX8",
                "--quadrature-order",
                "3",
                "--max-elements",
                "1",
                "--max-nodes",
                "8",
                "--max-node-degree",
                "1",
                "--verify-reference",
                "--verify-performance-shape",
                "--validate-mlir",
            ]
            result = subprocess.run(
                command,
                check=True,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
            )
            manifest_path = Path(result.stdout.strip().splitlines()[-1])
            manifest = json.loads(manifest_path.read_text())
            pipeline_path = next(
                Path(path)
                for path in manifest["artifacts"]["sum_factor"]
                if path.endswith(".matrix_unit_pipeline.mlir")
            )
            pipeline_module = pipeline_path.read_text()

        self.assertEqual(manifest["element"], "HEX8")
        self.assertEqual(manifest["quadrature_order"], 3)
        self.assertEqual(manifest["n_shape_1d"], 2)
        self.assertEqual(manifest["n_qp_1d"], 3)
        self.assertIn("%bridge1 = memref.alloc() : memref<2x6xf32>", pipeline_module)
        self.assertIn("%bridge2 = memref.alloc() : memref<2x9xf32>", pipeline_module)
        self.assertIn("memref.load %scratch0", pipeline_module)
        self.assertIn("memref.store %bridge", pipeline_module)
        self.assertNotIn("memref.reinterpret_cast", pipeline_module)
        sum_factor_reference = next(
            item for item in manifest["reference_verification"] if item["name"] == "tensor_product_sum_factor_pipeline_reference"
        )
        self.assertLessEqual(sum_factor_reference["max_field_gradient_diff"], 1.0e-6)
        self.assertLessEqual(sum_factor_reference["max_laplace_residual_diff"], 1.0e-6)
        self.assertTrue(all(item["ok"] for item in manifest["reference_verification"]), manifest["reference_verification"])
        self.assertTrue(all(item["ok"] for item in manifest["performance_shape"]), manifest["performance_shape"])
        self.assertTrue(all(item["ok"] for item in manifest["mlir_validation"]), manifest["mlir_validation"])

    def test_laplace_hex27_form_ir_emits_high_order_fused_metal_apply(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX27",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormMetalLowering(ir)
        source = lowering.render_metal_source()

        self.assertEqual(ir.sum_factor.n_shape_1d, 3)
        self.assertEqual(ir.sum_factor.n_qp_1d, 3)
        self.assertIn("constant float sfem_shape_1d[9]", source)
        self.assertIn("constant float sfem_grad_1d[9]", source)
        self.assertIn("constant float sfem_weight_1d[3]", source)
        self.assertIn("for (uint qz = 0; qz < 3; ++qz)", source)
        self.assertIn("for (uint sx = 0; sx < 3; ++sx)", source)
        self.assertIn("test_gx * grad_u_x + test_gy * grad_u_y + test_gz * grad_u_z", source)
        self.assertNotIn("if (", source)

    def test_laplace_hex27_form_ir_emits_high_order_fused_gpu_mlir(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="HEX27",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormGPULowering(ir)
        module = lowering.render_gpu_module()

        self.assertEqual(module.count("gpu.launch_func"), 1)
        self.assertEqual(module.count("gpu.func @"), 1)
        self.assertIn("memref<27xf32>", module)
        self.assertIn("memref<9xf32>", module)
        self.assertIn("memref<3xf32>", module)
        self.assertIn("arith.constant 27 : index", module)
        self.assertIn("scf.for %qz", module)
        self.assertIn("scf.for %sz", module)
        self.assertNotIn("scf.if", module)
        self.assertNotIn("arith.cmpi", module)

        self._run_mlir_opt(module)

    def test_laplace_form_apply_runs_on_metal_when_device_is_available(self):
        from codegen.framework.materials.laplace import material

        if shutil.which("xcrun") is None:
            self.skipTest("xcrun is not available for Metal runtime test")

        ir = tensor_product_laplace_form_ir_from_material(
            material,
            element="QUAD4",
            vector_size=8,
        )
        lowering = TensorProductLaplaceFormMetalLowering(ir)
        with tempfile.TemporaryDirectory() as tmp:
            result = lowering.run_metal_smoke_test(tmp)

        self.assertTrue(result.harness_path.name.endswith("_metal_smoke.mm"))
        if not result.compiled:
            self.fail(result.compile_stderr)
        if result.no_default_device:
            self.skipTest("Metal runtime has no default MTLDevice")
        self.assertTrue(result.success, result.run_stderr)

    def test_laplace_sum_factor_lowering_exposes_iree_metal_command(self):
        from codegen.framework.materials.laplace import material

        ir = tensor_product_sum_factor_ir_from_material(
            material,
            element="HEX8",
            vector_size=8,
        )
        lowering = TensorProductSumFactorMLIRLowering(ir)
        command = lowering.iree_metal_compile_command(
            "laplace_hex8.linalg.mlir",
            "laplace_hex8.metal.vmfb",
        )

        self.assertEqual(command[0], "iree-compile")
        self.assertIn("--iree-hal-target-backends=metal-spirv", command)
        self.assertIn("--iree-metal-compile-to-metallib=false", command)
        self.assertEqual(command[-1], "laplace_hex8.metal.vmfb")

        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(FileNotFoundError):
                lowering.compile_with_iree_metal(tmp, iree_compile="/does/not/exist/iree-compile")
            output_dir = Path(tmp)
            default_input = output_dir / ("%s.linalg_pipeline.mlir" % ir.function_prefix)
            default_output = output_dir / ("%s.linalg_pipeline.metal.vmfb" % ir.function_prefix)
            pipeline_input = output_dir / ("%s.matrix_unit_pipeline.mlir" % ir.function_prefix)
            pipeline_output = output_dir / ("%s.matrix_unit_pipeline.metal.vmfb" % ir.function_prefix)
            memref_input = output_dir / ("%s.matrix_unit_memref.mlir" % ir.function_prefix)
            memref_output = output_dir / ("%s.matrix_unit_memref.metal.vmfb" % ir.function_prefix)
            matrix_input = output_dir / ("%s.matrix_unit.mlir" % ir.function_prefix)
            matrix_output = output_dir / ("%s.matrix_unit.metal.vmfb" % ir.function_prefix)
            raw_input = output_dir / ("%s.linalg.mlir" % ir.function_prefix)
            raw_output = output_dir / ("%s.linalg.metal.vmfb" % ir.function_prefix)
            self.assertTrue(default_input.exists())
            self.assertIn('sfem.lowering = "tensor_product_sum_factor_linalg_pipeline"', default_input.read_text())
            self.assertTrue(str(default_output).endswith(".linalg_pipeline.metal.vmfb"))
            with self.assertRaises(FileNotFoundError):
                lowering.compile_with_iree_metal(
                    tmp,
                    iree_compile="/does/not/exist/iree-compile",
                    input_kind="matrix_unit_pipeline",
                )
            self.assertTrue(pipeline_input.exists())
            self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_pipeline"', pipeline_input.read_text())
            self.assertTrue(str(pipeline_output).endswith(".matrix_unit_pipeline.metal.vmfb"))
            with self.assertRaises(FileNotFoundError):
                lowering.compile_with_iree_metal(
                    tmp,
                    iree_compile="/does/not/exist/iree-compile",
                    input_kind="matrix_unit_memref",
                )
            self.assertTrue(memref_input.exists())
            self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit_memref"', memref_input.read_text())
            self.assertTrue(str(memref_output).endswith(".matrix_unit_memref.metal.vmfb"))
            with self.assertRaises(FileNotFoundError):
                lowering.compile_with_iree_metal(
                    tmp,
                    iree_compile="/does/not/exist/iree-compile",
                    input_kind="matrix_unit",
                )
            self.assertTrue(matrix_input.exists())
            self.assertIn('sfem.lowering = "tensor_product_sum_factor_matrix_unit"', matrix_input.read_text())
            self.assertTrue(str(matrix_output).endswith(".matrix_unit.metal.vmfb"))
            with self.assertRaises(FileNotFoundError):
                lowering.compile_with_iree_metal(
                    tmp,
                    iree_compile="/does/not/exist/iree-compile",
                    input_kind="linalg",
                )
            self.assertTrue(raw_input.exists())
            self.assertIn('sfem.lowering = "tensor_product_sum_factor_generic_gpu"', raw_input.read_text())
            self.assertTrue(str(raw_output).endswith(".linalg.metal.vmfb"))

        if shutil.which("iree-compile") is None:
            self.skipTest("iree-compile is not available for Apple Metal integration test")
        with tempfile.TemporaryDirectory() as tmp:
            output_vmfb, result = lowering.compile_with_iree_metal(tmp)
        self.assertTrue(output_vmfb.name.endswith(".linalg_pipeline.metal.vmfb"))
        self.assertEqual(result.returncode, 0)

    def _run_mlir_opt(self, module, *passes):
        mlir_opt = shutil.which("mlir-opt")
        if mlir_opt is None and shutil.which("/opt/homebrew/opt/llvm/bin/mlir-opt"):
            mlir_opt = "/opt/homebrew/opt/llvm/bin/mlir-opt"
        if mlir_opt is None:
            self.skipTest("mlir-opt is not available")

        with tempfile.NamedTemporaryFile("w", suffix=".mlir") as src:
            src.write(module)
            src.flush()
            command = [mlir_opt, src.name, "--verify-diagnostics", *passes]
            result = subprocess.run(
                command,
                check=True,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        return result.stdout


if __name__ == "__main__":
    unittest.main()
