import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

import numpy as np

from codegen.framework.mlir import (
    MLIR_OPTIMIZATION_PLANS,
    MLIROptimizationStrategy,
    MatrixFreeEBEMLIRLowering,
    ThreadedEBEExecutor,
    build_inverted_topology,
    pad_to_vector_width,
    reference_ebe_residual,
)


class MatrixFreeEBEMLIRTest(unittest.TestCase):
    def test_model_is_sourced_from_generated_linear_elasticity_plan(self):
        lowering = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        )
        model = lowering.model

        self.assertEqual(model.material_name, "linear_elasticity")
        self.assertEqual(model.kernel_kind, "energy_soa")
        self.assertEqual(model.element_type, "TET4")
        self.assertEqual(model.mesh_kernel_name, "linear_elasticity_tet4")
        self.assertEqual(model.local_apply_name, "linear_elasticity_d3_simplex_apply")
        self.assertEqual(model.mesh_phases, ("geometry", "local_call", "scatter"))
        self.assertEqual(model.expression_names, ("objective", "gradient", "apply"))
        self.assertEqual(model.dim, 3)
        self.assertEqual(model.n_shape, 4)
        self.assertEqual(model.n_qp, 1)
        self.assertEqual(model.vector_size, 8)
        self.assertEqual(model.parameters, ("lmbda", "mu"))
        self.assertEqual(model.quadrature_weights, (1.0 / 6.0,))
        self.assertEqual(model.reference_gradients[:3], (-1.0, -1.0, -1.0))
        self.assertIn("trial_grad0", str(model.apply_material_expressions[0]))

    def test_opencl_spirv_module_is_valid_and_uses_opencl_kernel_model(self):
        opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).opencl(max_elements=8, max_nodes=9, max_node_degree=8)
        ir_module = opencl.build_spirv_opencl_module()
        spirv_module = list(ir_module.body.operations)[0]
        self.assertEqual(spirv_module.name, "spirv.module")
        self.assertEqual(
            str(spirv_module.attributes["sfem.codegen.local_apply"]),
            '"linear_elasticity_d3_simplex_apply"',
        )

        module = opencl.render_spirv_opencl_module()

        self.assertIn("spirv.module Logical OpenCL", module)
        self.assertIn('spirv.EntryPoint "Kernel" @linear_elasticity_tet4_opencl_map', module)
        self.assertIn('spirv.EntryPoint "Kernel" @linear_elasticity_tet4_opencl_reduce', module)
        self.assertIn("CrossWorkgroup", module)
        self.assertIn('sfem.codegen.local_apply = "linear_elasticity_d3_simplex_apply"', module)
        self.assertIn('sfem.opencl.memory_model = "OpenCL"', module)

        self._run_mlir_opt(module)

    def test_opencl_lowering_supports_named_mlir_optimization_strategies(self):
        for strategy in MLIROptimizationStrategy:
            opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
                element="TET4",
                vector_size=8,
            ).opencl(
                max_elements=8,
                max_nodes=9,
                max_node_degree=8,
                optimization_strategy=strategy,
            )
            self.assertEqual(opencl.optimization_plan, MLIR_OPTIMIZATION_PLANS[strategy])
            try:
                optimized_module = opencl.optimize_spirv_opencl_module()
                optimized_op = opencl.render_optimized_spirv_module_op()
            except FileNotFoundError as exc:
                self.skipTest(str(exc))

            self.assertIn("spirv.module Logical OpenCL", optimized_module)
            self.assertTrue(optimized_op.startswith("spirv.module"))

    def test_opencl_c_source_is_emitted_from_kernel_model_for_apple_runtime(self):
        opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).opencl(max_elements=8, max_nodes=9, max_node_degree=8)

        source = opencl.lower_to_opencl_c_source()

        self.assertIn("Generated by MatrixFreeOpenCLMLIRLowering", source)
        self.assertIn("__kernel void tet4_le_map", source)
        self.assertIn("__kernel void tet4_le_reduce", source)
        self.assertIn("const float rg[12]", source)
        self.assertIn("stress[0] =", source)
        self.assertIn("grad[0]", source)
        self.assertIn("lmbda", source)
        self.assertIn("mu", source)

    def test_pymlir_package_is_detected_from_repo_venv(self):
        opencl = MatrixFreeEBEMLIRLowering.from_linear_elasticity().opencl()
        availability = opencl.pymlir_availability()

        self.assertTrue(availability.available, availability.reason)
        self.assertEqual(availability.module_name, "mlir")

    def test_openmp_mlir_lowers_and_runs_with_mlir_runner(self):
        openmp = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).openmp(max_elements=8, max_nodes=9, max_node_degree=8)

        scf_module = openmp.render_scf_module()
        self.assertIn("scf.parallel", scf_module)
        self.assertIn("scf.for", scf_module)
        self.assertIn("iter_args", scf_module)
        self.assertIn("memref<9xindex>", scf_module)
        self.assertIn("memref<72xindex>", scf_module)
        self.assertIn("memref<96xf32>", scf_module)
        self.assertIn("linear_elasticity_tet4_mlir_apply_openmp", scf_module)

        try:
            result = openmp.run_with_mlir_runner()
        except FileNotFoundError as exc:
            self.skipTest(str(exc))

        self.assertTrue(result.success, result.stderr)
        self.assertEqual(result.entry_result, 0)
        self.assertIn("omp.parallel", result.openmp_module)
        self.assertIn("omp.wsloop", result.openmp_module)

    def test_openmp_lowering_supports_named_mlir_optimization_strategies(self):
        for strategy in MLIROptimizationStrategy:
            openmp = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
                element="TET4",
                vector_size=8,
            ).openmp(
                max_elements=8,
                max_nodes=9,
                max_node_degree=8,
                optimization_strategy=strategy,
            )
            self.assertEqual(openmp.optimization_plan, MLIR_OPTIMIZATION_PLANS[strategy])
            try:
                optimized = openmp.optimize_kernel_scf_module()
                llvm_module = openmp.lower_kernel_to_llvm_module()
            except FileNotFoundError as exc:
                self.skipTest(str(exc))

            self.assertIn("func.func", optimized)
            self.assertIn("llvm.func", llvm_module)

    def test_inspection_artifacts_are_written_for_openmp_and_opencl(self):
        lowering = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        )
        with tempfile.TemporaryDirectory() as tmp:
            tmp = Path(tmp)
            openmp = lowering.openmp(max_elements=8, max_nodes=9, max_node_degree=8)
            opencl = lowering.opencl(max_elements=8, max_nodes=9, max_node_degree=8)
            try:
                openmp_artifacts = openmp.write_inspection_artifacts(tmp / "openmp")
                opencl_artifacts = opencl.write_inspection_artifacts(tmp / "opencl")
            except FileNotFoundError as exc:
                self.skipTest(str(exc))

            scf_mlir = openmp_artifacts.file_for_suffix(".scf.mlir").read_text()
            openmp_mlir = openmp_artifacts.file_for_suffix(".openmp.mlir").read_text()
            llvm_mlir = openmp_artifacts.file_for_suffix(".llvm.mlir").read_text()
            llvm_ir = openmp_artifacts.file_for_suffix(".ll").read_text()
            emitc_mlir = openmp_artifacts.file_for_suffix(".emitc.mlir").read_text()
            c_source = openmp_artifacts.file_for_suffix(".c").read_text()
            spirv_module = opencl_artifacts.file_for_suffix(".spirv.module.mlir").read_text()
            spirv_op = opencl_artifacts.file_for_suffix(".spirv.mlir").read_text()
            opencl_c_source = opencl_artifacts.file_for_suffix(".cl").read_text()
            spirv_binary_size = opencl_artifacts.file_for_suffix(".spv").stat().st_size

        self.assertIn("scf.parallel", scf_mlir)
        self.assertIn("omp.parallel", openmp_mlir)
        self.assertIn("llvm.func", llvm_mlir)
        self.assertIn("define", llvm_ir)
        self.assertIn("emitc.func", emitc_mlir)
        self.assertIn("!emitc.ptr<f32>", emitc_mlir)
        self.assertIn("#include <stdint.h>", c_source)
        self.assertIn("linear_elasticity_tet4_mlir_apply_openmp_c", c_source)
        self.assertIn("spirv.module Logical OpenCL", spirv_module)
        self.assertTrue(spirv_op.startswith("spirv.module"))
        self.assertIn("__kernel void tet4_le_map", opencl_c_source)
        self.assertGreater(spirv_binary_size, 0)

    def test_threaded_two_pass_executor_matches_callback_reference_without_atomics(self):
        model = MatrixFreeEBEMLIRLowering.from_linear_elasticity(
            element="TET4",
            vector_size=8,
        ).model
        connectivity = np.array(
            [
                [0, 1, 2, 4],
                [1, 3, 2, 4],
                [1, 5, 3, 4],
                [3, 5, 6, 4],
                [0, 2, 7, 4],
                [2, 8, 7, 4],
                [2, 3, 8, 4],
                [3, 6, 8, 4],
            ],
            dtype=np.intp,
        )
        current = np.zeros((9, 3), dtype=np.float32)
        direction = np.arange(27, dtype=np.float32).reshape(9, 3)
        inverted = build_inverted_topology(connectivity, num_nodes=current.shape[0])
        executor = ThreadedEBEExecutor(
            model,
            max_workers=4,
            synchronize_workers=True,
        )

        def local_apply(elem, local_node, component, node, current, direction, parameters):
            scale = np.float32(parameters["mu"] + parameters["lmbda"])
            return np.float32(scale * direction[node, component])

        parameters = {"mu": np.float32(2.0), "lmbda": np.float32(3.0)}
        result = executor.run(current, direction, connectivity, local_apply, parameters, inverted)

        np.testing.assert_array_equal(
            result.residual,
            reference_ebe_residual(model, current, direction, connectivity, local_apply, parameters),
        )
        self.assertEqual(result.padded_scratch_components, 16)
        self.assertGreaterEqual(result.map_worker_count, 2)
        self.assertGreaterEqual(result.reduce_worker_count, 2)

    def test_inverted_topology_and_padding_are_explicit(self):
        connectivity = np.array([[0, 1, 2], [2, 1, 3]], dtype=np.intp)
        inverted = build_inverted_topology(connectivity, num_nodes=4)

        np.testing.assert_array_equal(inverted.node_degree, np.array([1, 2, 2, 1]))
        self.assertEqual(inverted.node_to_element_map.shape, (4, 2))
        self.assertEqual(inverted.node_to_local_idx[2, 0], 2)
        self.assertEqual(inverted.node_to_local_idx[2, 1], 0)
        self.assertEqual(pad_to_vector_width(3, 8), 8)
        self.assertEqual(pad_to_vector_width(16, 8), 16)

    def _run_mlir_opt(self, module, *passes):
        mlir_opt = shutil.which("mlir-opt")
        if mlir_opt is None and shutil.which("/opt/homebrew/opt/llvm/bin/mlir-opt"):
            mlir_opt = "/opt/homebrew/opt/llvm/bin/mlir-opt"
        if mlir_opt is None:
            self.skipTest("mlir-opt is not available")

        with tempfile.NamedTemporaryFile("w", suffix=".mlir") as src:
            src.write(module)
            src.flush()
            command = [mlir_opt, src.name, "--verify-diagnostics", *passes]
            result = subprocess.run(
                command,
                check=True,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        return result.stdout


if __name__ == "__main__":
    unittest.main()
