#include <fstream>
#include "sfem_test.hpp"
#include "sfem_FunctionSpace.hpp"
#include "smesh_mesh.hpp"
#include "sfem_Sideset.hpp"
#include "sfem_Communicator.hpp"
#include "sfem_glob.hpp"

// int test_sideset_block_id() {
//     MPI_Comm comm = MPI_COMM_WORLD;
//     auto mesh = sfem::Mesh::create_hex8_cube(sfem::Communicator::wrap(comm), 2, 2, 2);
//     auto space = sfem::FunctionSpace::create(mesh, 1);
    
//     // Test creating sideset with block ID
//     auto parent = sfem::create_host_buffer<element_idx_t>(4);
//     auto lfi = sfem::create_host_buffer<int16_t>(4);
    
//     // Initialize with some test data
//     for (int i = 0; i < 4; i++) {
//         parent->data()[i] = i;
//         lfi->data()[i] = i % 2;
//     }
    
//     auto sideset = sfem::Sideset::create(sfem::Communicator::wrap(comm), parent, lfi, 1);
    
//     SFEM_TEST_ASSERT(sideset->block_id() == 1);
//     SFEM_TEST_ASSERT(sideset->has_block_id());
//     SFEM_TEST_ASSERT(sideset->size() == 4);
    
//     return SFEM_TEST_SUCCESS;
// }

// int test_sideset_default_block_id() {
//     MPI_Comm comm = MPI_COMM_WORLD;
//     auto mesh = sfem::Mesh::create_hex8_cube(sfem::Communicator::wrap(comm), 2, 2, 2);
//     auto space = sfem::FunctionSpace::create(mesh, 1);
    
//     // Test creating sideset with default block ID (should be 0)
//     auto parent = sfem::create_host_buffer<element_idx_t>(4);
//     auto lfi = sfem::create_host_buffer<int16_t>(4);
    
//     auto sideset = sfem::Sideset::create(sfem::Communicator::wrap(comm), parent, lfi);  // No block_id specified
    
//     SFEM_TEST_ASSERT(sideset->block_id() == 0);
//     SFEM_TEST_ASSERT(sideset->has_block_id());
    
//     return SFEM_TEST_SUCCESS;
// }

// int test_sideset_file_io() {
//     MPI_Comm comm = MPI_COMM_WORLD;
    
//     // Test writing and reading sideset with block ID
//     auto parent = sfem::create_host_buffer<element_idx_t>(4);
//     auto lfi = sfem::create_host_buffer<int16_t>(4);
    
//     // Initialize with test data
//     for (int i = 0; i < 4; i++) {
//         parent->data()[i] = i;
//         lfi->data()[i] = i % 2;
//     }
    
//     auto sideset = sfem::Sideset::create(sfem::Communicator::wrap(comm), parent, lfi, 2);
    
//     // Write to temporary directory
//     std::string temp_dir = "/tmp/test_sideset_block";
//     int result = sideset->write(temp_dir.c_str());
//     SFEM_TEST_ASSERT(result == SFEM_SUCCESS);
    
//     // Read back
//     auto sideset_read = sfem::Sideset::create_from_file(sfem::Communicator::wrap(comm), temp_dir.c_str());
//     SFEM_TEST_ASSERT(sideset_read != nullptr);
//     SFEM_TEST_ASSERT(sideset_read->block_id() == 2);
//     SFEM_TEST_ASSERT(sideset_read->size() == 4);
    
//     return SFEM_TEST_SUCCESS;
// }

// int test_sideset_backward_compatibility() {
//     MPI_Comm comm = MPI_COMM_WORLD;
    
//     // Test that old sideset files (without block_id) still work
//     auto parent = sfem::create_host_buffer<element_idx_t>(4);
//     auto lfi = sfem::create_host_buffer<int16_t>(4);
    
//     // Initialize with test data
//     for (int i = 0; i < 4; i++) {
//         parent->data()[i] = i;
//         lfi->data()[i] = i % 2;
//     }
    
//     auto sideset = sfem::Sideset::create(sfem::Communicator::wrap(comm), parent, lfi, 0);  // block_id = 0
    
//     // Write without block_id file (simulate old format)
//     std::string temp_dir = "/tmp/test_sideset_old";
//     sfem::create_directory(temp_dir.c_str());
    
//     // Write only parent and lfi files (old format)
//     std::string parent_path = temp_dir + "/parent.raw";
//     array_write(comm, parent_path.c_str(), SFEM_MPI_ELEMENT_IDX_T,
//                 parent->data(), parent->size(), parent->size());
    
//     std::string lfi_path = temp_dir + "/lfi.int16.raw";
//     array_write(comm, lfi_path.c_str(), MPI_SHORT, lfi->data(), lfi->size(), lfi->size());
    
//     std::ofstream os(temp_dir + "/meta.yaml");
//     if (os.good()) {
//         os << "# Automatically generated by sfem_Sideset.cpp\n";
//         os << "parent: parent.raw\n";
//         os << "lfi: lfi.int16.raw\n";
//         os << "rpath: true\n";
//     }
//     os.close();
    
//     // Read back (should default to block_id = 0)
//     auto sideset_read = sfem::Sideset::create_from_file(sfem::Communicator::wrap(comm), temp_dir.c_str());
//     SFEM_TEST_ASSERT(sideset_read != nullptr);
//     SFEM_TEST_ASSERT(sideset_read->block_id() == 0);  // Should default to 0
//     SFEM_TEST_ASSERT(sideset_read->size() == 4);
    
//     return SFEM_TEST_SUCCESS;
// }

int main(int argc, char *argv[]) {
    SFEM_UNIT_TEST_INIT(argc, argv);
    
    // SFEM_RUN_TEST(test_sideset_block_id);
    // SFEM_RUN_TEST(test_sideset_default_block_id);
    // SFEM_RUN_TEST(test_sideset_file_io);
    // SFEM_RUN_TEST(test_sideset_backward_compatibility);
    
    SFEM_UNIT_TEST_FINALIZE();
    return SFEM_UNIT_TEST_ERR();
} 