# CMake generated Testfile for 
# Source directory: /Users/haoyuyang/Documents/thesis/sfem_github/sfem
# Build directory: /Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ssquad4_interpolate_test]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/ssquad4_interpolate_test")
set_tests_properties([=[ssquad4_interpolate_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sshex8_interpolate_test]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sshex8_interpolate_test")
set_tests_properties([=[sshex8_interpolate_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_StencilTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_StencilTest")
set_tests_properties([=[sfem_StencilTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sshex8_mesh_test]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sshex8_mesh_test")
set_tests_properties([=[sshex8_mesh_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_CantileverKVTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_CantileverKVTest")
set_tests_properties([=[sfem_CantileverKVTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_CantileverTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_CantileverTest")
set_tests_properties([=[sfem_CantileverTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_DirichletConditionsTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_DirichletConditionsTest")
set_tests_properties([=[sfem_DirichletConditionsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_GalerkinAssemblyTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_GalerkinAssemblyTest")
set_tests_properties([=[sfem_GalerkinAssemblyTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_MeshBlocksTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_MeshBlocksTest")
set_tests_properties([=[sfem_MeshBlocksTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_MultiBlockFunctionSpaceTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_MultiBlockFunctionSpaceTest")
set_tests_properties([=[sfem_MultiBlockFunctionSpaceTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_MultiBlockOpTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_MultiBlockOpTest")
set_tests_properties([=[sfem_MultiBlockOpTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_NewmarkKVTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_NewmarkKVTest")
set_tests_properties([=[sfem_NewmarkKVTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_NewmarkTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_NewmarkTest")
set_tests_properties([=[sfem_NewmarkTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_PoissonTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_PoissonTest")
set_tests_properties([=[sfem_PoissonTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_SemiStructuredMeshTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_SemiStructuredMeshTest")
set_tests_properties([=[sfem_SemiStructuredMeshTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_TimedepNeumannKVTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_TimedepNeumannKVTest")
set_tests_properties([=[sfem_TimedepNeumannKVTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_TimedepNeumannTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_TimedepNeumannTest")
set_tests_properties([=[sfem_TimedepNeumannTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_MGSDFContactTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_MGSDFContactTest")
set_tests_properties([=[sfem_MGSDFContactTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_SSGMGTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_SSGMGTest")
set_tests_properties([=[sfem_SSGMGTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_SSMGTraceSpaceOperationTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_SSMGTraceSpaceOperationTest")
set_tests_properties([=[sfem_SSMGTraceSpaceOperationTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
add_test([=[sfem_AMGTest]=] "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/build_release/sfem_AMGTest")
set_tests_properties([=[sfem_AMGTest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;363;add_test;/Users/haoyuyang/Documents/thesis/sfem_github/sfem/CMakeLists.txt;0;")
