"""The gate that compares the shipped tree with the generator.

`frontend/ops/generated` is globbed into libsfem by `CMakeLists.txt` and is
never regenerated by the build, so it is what actually ships.  Nothing compared
it against the generators until `check-tree`: `verify` and `check` both ask
whether the generator still agrees with a record of itself, which cannot detect
a tree that simply stopped being regenerated.

These tests do not run the generators -- that takes minutes and CI already does
it.  They pin the two things that decide whether the gate means anything: that
the tree it defaults to is the one the build compiles, and that the comparison
reports drift rather than tolerating it.  The `UNGENERATED_TREE_PATHS` list is
the gate's only blind spot, so it is pinned too; an entry silently added there
would hide exactly the class of drift the gate exists to catch.
"""

import os
import tempfile
import unittest

from codegen.framework.tools.codegen_snapshot import (
    MATERIALS,
    UNGENERATED_TREE_PATHS,
    compare,
    shipped_tree,
    snapshot_root,
)


class ShippedTreeTest(unittest.TestCase):
    def test_the_default_tree_is_the_one_cmake_compiles(self):
        tree = shipped_tree()
        self.assertTrue(os.path.isdir(tree), "%s is not a directory" % tree)
        self.assertEqual(os.path.basename(tree), "generated")
        self.assertTrue(tree.endswith(os.path.join("frontend", "ops", "generated")))

    def test_the_tree_is_named_generated_so_headers_hoist(self):
        """`sfem.gen` hoists the shared headers by the output directory's name.

        A comparison run against a differently named directory would regenerate
        a different tree and report drift that is an artefact of the path.
        """
        self.assertEqual(os.path.basename(snapshot_root("/anywhere")), "generated")

    def test_every_material_the_script_runs_is_captured(self):
        """The snapshot and `regenerate_all.sh` must describe the same set.

        They disagreed once: the snapshot drove `poro_elasticity` by module name
        into a directory of that name, while the generator wrote
        `poro_hyperelasticity`, so 68 paths could never match.
        """
        script = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "generators",
            "regenerate_all.sh",
        )
        with open(script, encoding="utf-8") as handle:
            text = handle.read()
        for material in MATERIALS:
            with self.subTest(material=material):
                self.assertIn("generators.%s" % material, text)


class DriftIsReportedTest(unittest.TestCase):
    """`compare` is what makes the gate bite, so it is what is worth pinning."""

    def _tree(self, files):
        root = tempfile.mkdtemp()
        for relative, content in files.items():
            path = os.path.join(root, relative)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(content)
        return root

    def test_identical_trees_report_nothing(self):
        files = {"a/one.cpp": "int one();\n", "two.hpp": "int two();\n"}
        added, removed, changed = compare(self._tree(files), self._tree(files))
        self.assertEqual((added, removed, changed), ([], [], []))

    def test_a_changed_file_is_reported(self):
        reference = self._tree({"a/one.cpp": "int one();\n"})
        candidate = self._tree({"a/one.cpp": "int one(void);\n"})
        _added, _removed, changed = compare(reference, candidate)
        self.assertEqual(changed, [os.path.join("a", "one.cpp")])

    def test_a_file_only_in_the_tree_is_reported_as_removed(self):
        """This is the shape a stale tree takes: it has what the generator dropped."""
        reference = self._tree({"a/one.cpp": "x\n", "stale.cpp": "y\n"})
        candidate = self._tree({"a/one.cpp": "x\n"})
        _added, removed, _changed = compare(reference, candidate)
        self.assertEqual(removed, ["stale.cpp"])

    def test_a_file_only_in_the_generation_is_reported_as_added(self):
        reference = self._tree({"a/one.cpp": "x\n"})
        candidate = self._tree({"a/one.cpp": "x\n", "fresh.cpp": "y\n"})
        added, _removed, _changed = compare(reference, candidate)
        self.assertEqual(added, ["fresh.cpp"])


class BlindSpotTest(unittest.TestCase):
    def test_the_exempt_list_is_only_what_no_generator_writes(self):
        """Four CUDA headers and the registration unit, and nothing else.

        `generators.cuda` runs only under `SFEM_GENERATE_CUDA=1` and
        `generators.op_registration` is manifest-driven and hand-edited, so a
        plain regeneration produces neither.  Every other path in the tree is
        checked, and this list must not grow to make a failure go away.
        """
        self.assertEqual(
            sorted(UNGENERATED_TREE_PATHS),
            [
                "geometry_kernels.cuh",
                "kernel_diagnostics.cuh",
                "kernel_math.cuh",
                "sfem_generated_ops_registration.cpp",
                "sfem_generated_ops_registration.hpp",
                "tensor_product_kernels.cuh",
            ],
        )

    def test_the_exempt_files_are_all_at_the_tree_root(self):
        """A nested exemption would excuse a whole material's worth of drift."""
        for relative in UNGENERATED_TREE_PATHS:
            with self.subTest(path=relative):
                self.assertNotIn("/", relative)


if __name__ == "__main__":
    unittest.main()
