#!/usr/bin/env python3
"""Emit cvfem_ns_mms_case.hpp: the Farrell/Mitchell/Wechsung manufactured solution
(SISC 41(5) eq. 5.2) and the body force that drives it.

Generated rather than hand-written: f_y alone is a degree-13 polynomial with 35 terms
before CSE, which is precisely the size at which transcription errors stop being visible
by eye and start looking like a discretisation defect.

    venv/bin/python spikes/cvfem/python/gen_mms_case.py \
        > spikes/cvfem/src/cases/cvfem_ns_mms_case.hpp
"""
import argparse
import sys
from pathlib import Path

import sympy as sp

# The generated header is a committed artifact that nothing regenerated or diffed, so it
# could drift from this script unnoticed. --check closes that: it regenerates in memory and
# compares, writing nothing. The two SymPy synthesizers already work this way.
_OUT = []
def emit_out(text):
    _OUT.append(text)


x, y, z, rho, mu, Re = sp.symbols('x y z rho mu Re', real=True)

u1 = sp.Rational(1, 4) * (x - 2)**2 * x**2 * y * (y**2 - 2)
u2 = -sp.Rational(1, 4) * x * (x**2 - 3*x + 2) * y**2 * (y**2 - 4)
u3 = sp.Integer(0)

pt = (x*y*(3*x**4 - 15*x**3 + 10*x**2*y**2 - 30*x*(y**2 - 2) + 20*(y**2 - 2))) / (5*Re) \
     - sp.Rational(1, 128) * (x - 2)**4 * x**4 * y**2 * (y**4 - 2*y**2 + 8)
p = pt + sp.Rational(1408, 33075) - 8/(5*Re)

u = [u1, u2, u3]
X = [x, y, z]

assert sp.simplify(sum(sp.diff(u[i], X[i]) for i in range(3))) == 0, "u must be divergence free"

# Our momentum operator is  rho (u.grad)u - mu lap(u) + grad p = f.
f = []
for i in range(3):
    conv = sum(u[j] * sp.diff(u[i], X[j]) for j in range(3))
    lap = sum(sp.diff(u[i], v, 2) for v in X)
    f.append(sp.simplify(rho * conv - mu * lap + sp.diff(p, X[i])))
assert f[2] == 0, "z-momentum forcing must vanish"

def emit(name, args, outs, exprs):
    sub, red = sp.cse(exprs, optimizations='basic')
    body = []
    for s, e in sub:
        body.append(f"        const T {s} = {sp.ccode(e)};")
    for o, e in zip(outs, red):
        body.append(f"        {o} = {sp.ccode(e)};")
    return (f"    template <typename T>\n    inline void {name}({args}) {{\n"
            + "\n".join(body) + "\n    }\n")

emit_out("""#pragma once

// The manufactured solution of Farrell, Mitchell & Wechsung, SIAM J. Sci. Comput. 41(5),
// A3073-A3096 (arXiv:1810.03315), equation 5.2, and the body force that drives it.
//
// GENERATED by spikes/cvfem/gen_mms_case.py -- edit that, not this.
//
// Templated on the scalar type on purpose: cvfem_ns_channel_case.hpp, which includes this,
// is deliberately free of the kernel headers' file-scope scalar_t so that it can sit next to
// either the solver core or the benchmark layouts. Using scalar_t here would break that.
//
// The velocity is a 2D field on [0,2]^2 extended as u = (u1(x,y), u2(x,y), 0); the pressure
// is unchanged in z. Two properties are asserted at generation time rather than assumed:
// div(u) == 0 exactly, and the z-momentum forcing vanishes identically.
//
// Parameter mapping. Their momentum equation is (u.grad)u - (1/Re) lap(u) + grad p = f;
// ours is rho (u.grad)u - mu lap(u) + grad p = f. Call these with rho = 1 and mu = 1/Re and
// their pressure formula is our exact pressure with no rescaling. Re is passed separately
// because the manufactured pressure genuinely depends on it -- evaluating p at a nominal Re
// while the operator runs at another silently corrupts the measured pressure convergence.
//
// The domain is not free: the pressure gauge constant 1408/33075 - 8/(5 Re) makes p exactly
// zero-mean over [0,2]^2 and nowhere else.
//
// Cross-check worth knowing: u1(x, y=2) = x^2 (2-x)^2, which is exactly the regularized
// lid profile of the same paper's cavity in the x-direction.

#include <cmath>

namespace cvfem_mms {
""")
emit_out(emit("velocity",
           "const T x, const T y, const T /*z*/,\n"
           "                       T &ux, T &uy, T &uz",
           ["ux", "uy", "uz"], [u1, u2, u3]))
emit_out(emit("pressure",
           "const T x, const T y, const T /*z*/,\n"
           "                       const T Re, T &p",
           ["p"], [p]))
emit_out(emit("body_force",
           "const T x, const T y, const T /*z*/,\n"
           "                       const T rho, const T mu, const T Re,\n"
           "                       T &fx, T &fy, T &fz",
           ["fx", "fy", "fz"], [f[0], f[1], f[2]]))
emit_out("}  // namespace cvfem_mms")


def main() -> int:
    ap = argparse.ArgumentParser(description="Emit the CVFEM MMS case header.")
    ap.add_argument("--out", type=Path, default=None,
                    help="write here instead of stdout")
    ap.add_argument("--check", action="store_true",
                    help="compare against the committed header and write nothing; "
                         "exits non-zero if they differ")
    args = ap.parse_args()

    text = "\n".join(_OUT) + "\n"
    default = Path(__file__).resolve().parent.parent / "src" / "cases" / "cvfem_ns_mms_case.hpp"

    if args.check:
        target = args.out or default
        if not target.exists():
            print(f"{target}: MISSING", file=sys.stderr)
            return 1
        if target.read_text() == text:
            print(f"{target.name}: unchanged")
            return 0
        print(f"{target.name}: DIFFERS from the checked-in header", file=sys.stderr)
        return 1

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"{args.out.name}: {text.count(chr(10))} lines", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
