"""Numerical parity and throughput for the matrix-free apply kernels.

Every step of the layering work so far has been gated on generated source being
byte-identical, which settles performance by construction: identical text
compiles to identical kernels.  That gate stops applying the moment output
changes on purpose -- which is exactly what unifying the coupled and mixed
emitters, or giving the mixed path packed apply, is for.

This is the gate that replaces it.  It generates a material, compiles the real
operator with the real flags, drives every matrix-free apply variant over a
structured mesh, and reports two things:

    parity      do the variants agree?  The SoA and AoS kernels are the same
                mathematics over differently laid-out inputs and must agree to
                round-off.  The float variants must agree to float precision.
                A refactor that changes an answer is caught here.

    throughput  MDOF/s per variant, so a change that preserves the answer and
                loses speed is caught too.  Byte-identity could never have told
                these apart, because it forbids both.

Usage::

    python -m codegen.framework.tools.apply_bench --element HEX8 --refine 12

The mesh is a Cartesian grid of hexahedra, so the geometry is affine and the
isoparametric and affine kernels are expected to agree as well.  That is a real
check on the geometry paths rather than a convenience: a bug in the adjugate
routing shows up as the two disagreeing.
"""

import argparse
import os
import subprocess
import sys
import tempfile


ELEMENT_NODES = {"HEX8": 8}

#: Elements whose kernels are aliases forwarding to another element's, so both
#: have to be generated for the result to link.  KERNELS.md asks for exactly
#: this: "HEX8 kernels should just wrap PROTEUS_HEX8 versions".
ALIAS_TARGETS = {"HEX8": ("PROTEUS_HEX8",)}


def _required_elements(element):
    return (element,) + ALIAS_TARGETS.get(element, ())


def _repo_root():
    path = os.path.dirname(os.path.abspath(__file__))
    while True:
        if os.path.isdir(os.path.join(path, "base")) and os.path.isdir(
            os.path.join(path, "python")
        ):
            return path
        parent = os.path.dirname(path)
        if parent == path:
            raise RuntimeError("could not locate the SFEM repository root")
        path = parent


def _compiler():
    for candidate in ("mpic++", "mpicxx", "c++"):
        try:
            subprocess.run([candidate, "--version"], stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, check=True)
            return candidate
        except (OSError, subprocess.CalledProcessError):
            continue
    return None


def _include_flags(root, generated_dir, material, dim):
    dirs = [
        os.path.join(generated_dir, material, "d%d" % dim),
        os.path.join(generated_dir, material),
        generated_dir,
        os.path.join(root, "base"),
        os.path.join(root, "build"),
        os.path.join(root, "build", "external", "smesh"),
        os.path.join(root, "external", "smesh", "src"),
    ]
    # Generated kernels may include hand-written SFEM operator headers -- the
    # PROTEUS_HEX8 Laplacian wraps hex8_laplacian_inline_cpu.hpp, for instance.
    operators_root = os.path.join(root, "operators")
    if os.path.isdir(operators_root):
        dirs.append(operators_root)
        for current, subdirs, _files in os.walk(operators_root):
            subdirs[:] = [d for d in subdirs if d not in ("cuda", "CMakeFiles")]
            dirs.append(current)
    smesh_src = os.path.join(root, "external", "smesh", "src")
    if os.path.isdir(smesh_src):
        dirs.extend(
            os.path.join(smesh_src, name)
            for name in sorted(os.listdir(smesh_src))
            if os.path.isdir(os.path.join(smesh_src, name))
        )
    flags = []
    for directory in dirs:
        if os.path.isdir(directory):
            flags.append("-I" + directory)
    return flags


DRIVER = r"""
// Generated by codegen.framework.tools.apply_bench.
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "sfem_base.hpp"

extern "C" {
int @PREFIX@_jacobian_action_isoparametric_mesh_soa(
    const ptrdiff_t, const ptrdiff_t, idx_t **const, const geom_t *const *const,
    const double, const ptrdiff_t, const double *const, const ptrdiff_t, double *const);
int @PREFIX@_jacobian_action_isoparametric_mesh_soa_float(
    const ptrdiff_t, const ptrdiff_t, idx_t **const, const geom_t *const *const,
    const float, const ptrdiff_t, const float *const, const ptrdiff_t, float *const);
int @PREFIX@_jacobian_action_isoparametric_mesh_aos(
    const ptrdiff_t, const ptrdiff_t, idx_t **const, const geom_t *const *const,
    const double *const, const double *const, double *const);
int @PREFIX@_jacobian_action_isoparametric_mesh_aos_float(
    const ptrdiff_t, const ptrdiff_t, idx_t **const, const geom_t *const *const,
    const float *const, const float *const, float *const);
int @PREFIX@_jacobian_action_affine_mesh_soa(
    const ptrdiff_t, const ptrdiff_t, idx_t **const,
    const geom_t *const, const geom_t *const, const geom_t *const,
    const geom_t *const, const geom_t *const, const geom_t *const,
    const geom_t *const, const geom_t *const, const geom_t *const,
    const geom_t *const,
    const double, const ptrdiff_t, const double *const, const ptrdiff_t, double *const);
int @PREFIX@_jacobian_action_affine_mesh_soa_float(
    const ptrdiff_t, const ptrdiff_t, idx_t **const,
    const geom_t *const, const geom_t *const, const geom_t *const,
    const geom_t *const, const geom_t *const, const geom_t *const,
    const geom_t *const, const geom_t *const, const geom_t *const,
    const geom_t *const,
    const float, const ptrdiff_t, const float *const, const ptrdiff_t, float *const);
}

// A Cartesian grid of hexahedra: n cells per side, spacing h = 1/n.  The map is
// affine, so the affine and isoparametric kernels must agree -- which is what
// makes this mesh a test of the geometry routing rather than a convenience.
struct Mesh {
    ptrdiff_t nelements = 0, nnodes = 0;
    double h = 0.0;
    std::vector<std::vector<idx_t>> elements;
    std::vector<std::vector<geom_t>> points;
    std::vector<idx_t *> element_ptrs;
    std::vector<const geom_t *> point_ptrs;
    // Affine geometry, one value per element: adjugate(J) row-major, then det J.
    std::vector<std::vector<geom_t>> adjugate;   // 9 streams
    std::vector<geom_t> determinant;             // 1 stream
};

static Mesh build_grid(int n) {
    Mesh m;
    const int nn = n + 1;
    m.h = 1.0 / (double)n;
    m.nnodes = (ptrdiff_t)nn * nn * nn;
    m.nelements = (ptrdiff_t)n * n * n;
    m.elements.assign(8, std::vector<idx_t>(m.nelements));
    m.points.assign(3, std::vector<geom_t>(m.nnodes));
    auto nid = [&](int i, int j, int k) { return (idx_t)((k * nn + j) * nn + i); };
    for (int k = 0; k < nn; ++k)
        for (int j = 0; j < nn; ++j)
            for (int i = 0; i < nn; ++i) {
                const idx_t id = nid(i, j, k);
                m.points[0][id] = (geom_t)(i * m.h);
                m.points[1][id] = (geom_t)(j * m.h);
                m.points[2][id] = (geom_t)(k * m.h);
            }
    ptrdiff_t e = 0;
    for (int k = 0; k < n; ++k)
        for (int j = 0; j < n; ++j)
            for (int i = 0; i < n; ++i, ++e) {
                m.elements[0][e] = nid(i, j, k);
                m.elements[1][e] = nid(i + 1, j, k);
                m.elements[2][e] = nid(i + 1, j + 1, k);
                m.elements[3][e] = nid(i, j + 1, k);
                m.elements[4][e] = nid(i, j, k + 1);
                m.elements[5][e] = nid(i + 1, j, k + 1);
                m.elements[6][e] = nid(i + 1, j + 1, k + 1);
                m.elements[7][e] = nid(i, j + 1, k + 1);
            }
    for (auto &row : m.elements) m.element_ptrs.push_back(row.data());
    for (auto &row : m.points) m.point_ptrs.push_back(row.data());

    // J = diag(h, h, h)  =>  det J = h^3,  adj(J) = det(J) J^-1 = diag(h^2, h^2, h^2).
    m.adjugate.assign(9, std::vector<geom_t>(m.nelements, (geom_t)0));
    m.determinant.assign(m.nelements, (geom_t)(m.h * m.h * m.h));
    for (ptrdiff_t i = 0; i < m.nelements; ++i) {
        m.adjugate[0][i] = (geom_t)(m.h * m.h);
        m.adjugate[4][i] = (geom_t)(m.h * m.h);
        m.adjugate[8][i] = (geom_t)(m.h * m.h);
    }
    return m;
}

static double norm_inf(const std::vector<double> &a) {
    double worst = 0.0;
    for (double v : a) worst = std::fmax(worst, std::fabs(v));
    return worst;
}

static double rel_diff(const std::vector<double> &a, const std::vector<double> &b) {
    double worst = 0.0;
    for (size_t i = 0; i < a.size(); ++i) worst = std::fmax(worst, std::fabs(a[i] - b[i]));
    const double scale = norm_inf(a);
    return (scale > 0.0) ? worst / scale : worst;
}

// What limits agreement between two variants.  geom_t is float (see
// smesh_config.hpp), so *all* geometry -- coordinates, adjugates, determinants
// -- is single precision whatever the kernel's scalar type is.  Two kernels
// that derive the element metric differently therefore agree only to geometry
// precision, even when both compute in double.
enum class Tolerance {
    EXACT,      // same geometry path, same precision: must agree bit for bit
    GEOMETRY,   // different geometry path: limited by float geom_t
    FLOAT,      // single-precision kernel: limited by the accumulation
};

struct Result {
    const char *name;
    double seconds;
    std::vector<double> out;
    Tolerance tolerance;
};

static double tolerance_value(Tolerance t) {
    switch (t) {
        case Tolerance::EXACT: return 0.0;
        case Tolerance::GEOMETRY: return 1e-5;
        case Tolerance::FLOAT: return 1e-4;
    }
    return 0.0;
}

static const char *tolerance_name(Tolerance t) {
    switch (t) {
        case Tolerance::EXACT: return "exact";
        case Tolerance::GEOMETRY: return "geometry(float)";
        case Tolerance::FLOAT: return "float";
    }
    return "?";
}

int main(int argc, char **argv) {
    const int n = (argc > 1) ? std::atoi(argv[1]) : 12;
    const int repeats = (argc > 2) ? std::atoi(argv[2]) : 5;
    Mesh m = build_grid(n);

    std::vector<double> x(m.nnodes);
    for (ptrdiff_t i = 0; i < m.nnodes; ++i) x[i] = std::sin(0.7 * (double)i) + 0.25;
    std::vector<float> xf(x.begin(), x.end());
    const double kappa = 1.3;
    const double parameters[1] = {kappa};
    const float parameters_f[1] = {(float)kappa};

    std::vector<Result> results;

    auto run_double = [&](const char *name, Tolerance tol, auto &&fn) {
        std::vector<double> out(m.nnodes, 0.0);
        double best = 1e300;
        for (int r = 0; r < repeats; ++r) {
            std::fill(out.begin(), out.end(), 0.0);
            const auto t0 = std::chrono::steady_clock::now();
            const int status = fn(out);
            const auto t1 = std::chrono::steady_clock::now();
            if (status != 0) { std::printf("FAIL %s status=%d\n", name, status); std::exit(2); }
            best = std::fmin(best, std::chrono::duration<double>(t1 - t0).count());
        }
        results.push_back({name, best, out, tol});
    };

    auto run_float = [&](const char *name, Tolerance tol, auto &&fn) {
        std::vector<float> out(m.nnodes, 0.0f);
        double best = 1e300;
        for (int r = 0; r < repeats; ++r) {
            std::fill(out.begin(), out.end(), 0.0f);
            const auto t0 = std::chrono::steady_clock::now();
            const int status = fn(out);
            const auto t1 = std::chrono::steady_clock::now();
            if (status != 0) { std::printf("FAIL %s status=%d\n", name, status); std::exit(2); }
            best = std::fmin(best, std::chrono::duration<double>(t1 - t0).count());
        }
        results.push_back({name, best, std::vector<double>(out.begin(), out.end()), tol});
    };

    std::printf("mesh: %lld elements, %lld nodes, h = %.6f\n\n",
                (long long)m.nelements, (long long)m.nnodes, m.h);

    run_double("affine_mesh_soa", Tolerance::GEOMETRY, [&](std::vector<double> &o) {
        return @PREFIX@_jacobian_action_affine_mesh_soa(
            m.nelements, m.nnodes, m.element_ptrs.data(),
            m.adjugate[0].data(), m.adjugate[1].data(), m.adjugate[2].data(),
            m.adjugate[3].data(), m.adjugate[4].data(), m.adjugate[5].data(),
            m.adjugate[6].data(), m.adjugate[7].data(), m.adjugate[8].data(),
            m.determinant.data(), kappa, 1, x.data(), 1, o.data()); });

    run_double("isoparametric_mesh_soa", Tolerance::EXACT, [&](std::vector<double> &o) {
        return @PREFIX@_jacobian_action_isoparametric_mesh_soa(
            m.nelements, m.nnodes, m.element_ptrs.data(), m.point_ptrs.data(),
            kappa, 1, x.data(), 1, o.data()); });

    run_double("isoparametric_mesh_aos", Tolerance::EXACT, [&](std::vector<double> &o) {
        return @PREFIX@_jacobian_action_isoparametric_mesh_aos(
            m.nelements, m.nnodes, m.element_ptrs.data(), m.point_ptrs.data(),
            parameters, x.data(), o.data()); });

    run_float("affine_mesh_soa_float", Tolerance::FLOAT, [&](std::vector<float> &o) {
        return @PREFIX@_jacobian_action_affine_mesh_soa_float(
            m.nelements, m.nnodes, m.element_ptrs.data(),
            m.adjugate[0].data(), m.adjugate[1].data(), m.adjugate[2].data(),
            m.adjugate[3].data(), m.adjugate[4].data(), m.adjugate[5].data(),
            m.adjugate[6].data(), m.adjugate[7].data(), m.adjugate[8].data(),
            m.determinant.data(), (float)kappa, 1, xf.data(), 1, o.data()); });

    run_float("isoparametric_mesh_soa_float", Tolerance::FLOAT, [&](std::vector<float> &o) {
        return @PREFIX@_jacobian_action_isoparametric_mesh_soa_float(
            m.nelements, m.nnodes, m.element_ptrs.data(), m.point_ptrs.data(),
            (float)kappa, 1, xf.data(), 1, o.data()); });

    run_float("isoparametric_mesh_aos_float", Tolerance::FLOAT, [&](std::vector<float> &o) {
        return @PREFIX@_jacobian_action_isoparametric_mesh_aos_float(
            m.nelements, m.nnodes, m.element_ptrs.data(), m.point_ptrs.data(),
            parameters_f, xf.data(), o.data()); });

    std::printf("throughput\n");
    for (const Result &r : results)
        std::printf("  %-34s %9.3f ms   %8.1f MDOF/s\n",
                    r.name, r.seconds * 1e3, (double)m.nnodes / r.seconds / 1e6);

    // Parity: every variant against the double isoparametric SoA reference.
    const Result *ref = nullptr;
    for (const Result &r : results) if (std::string(r.name) == "isoparametric_mesh_soa") ref = &r;
    std::printf("\nparity against isoparametric_mesh_soa\n");
    int failures = 0;
    for (const Result &r : results) {
        if (&r == ref) continue;
        const double rel = rel_diff(ref->out, r.out);
        const double tol = tolerance_value(r.tolerance);
        const bool ok = (r.tolerance == Tolerance::EXACT) ? (rel == 0.0) : (rel < tol);
        if (!ok) ++failures;
        std::printf("  %-34s rel = %.3e   %-16s %s\n",
                    r.name, rel, tolerance_name(r.tolerance), ok ? "ok" : "FAILED");
    }
    // Cross-variant parity cannot see a change that moves every variant the same
    // way -- perturb the material and all six shift together.  This digest is the
    // absolute check: it pins the answer itself, so a refactor that changes the
    // mathematics uniformly is still caught.
    double l2 = 0.0, l1 = 0.0;
    for (double v : ref->out) { l2 += v * v; l1 += std::fabs(v); }
    std::printf("\ndigest of isoparametric_mesh_soa: l2 = %.12e  l1 = %.12e\n",
                std::sqrt(l2), l1);

    if (failures) { std::printf("\nPARITY FAILED (%d)\n", failures); return 1; }
    std::printf("\nPARITY OK (%d variants)\n", (int)results.size());
    return 0;
}
"""


BASELINE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "apply_bench.json")

#: How far the recorded answer may move before it counts as a change.  The
#: geometry is single precision, so the digest is not reproducible to double
#: round-off across compilers; it is reproducible far tighter than any real
#: change to the mathematics.
DIGEST_TOLERANCE = 1e-9


def _check_digest(args, output):
    """Compare the reference kernel's answer against the recorded baseline.

    Cross-variant parity is blind to a change that moves every variant the same
    way -- perturbing the material shifts all six together and parity still
    passes, which is exactly what the negative test showed.  This pins the
    answer itself.
    """
    import json
    import re

    match = re.search(r"digest of isoparametric_mesh_soa: l2 = ([-\d.e+]+)\s+l1 = ([-\d.e+]+)", output)
    if not match:
        sys.stderr.write("no digest in the benchmark output\n")
        return 1
    digest = {"l2": float(match.group(1)), "l1": float(match.group(2))}
    key = "%s/%s/refine=%d" % (args.material, args.element, args.refine)

    baselines = {}
    if os.path.isfile(BASELINE_PATH):
        with open(BASELINE_PATH, encoding="utf-8") as handle:
            baselines = json.load(handle)

    if args.record or key not in baselines:
        baselines[key] = digest
        with open(BASELINE_PATH, "w", encoding="utf-8") as handle:
            json.dump(baselines, handle, indent=2, sort_keys=True)
            handle.write("\n")
        print("recorded baseline for %s" % key)
        return 0

    expected = baselines[key]
    worst = 0.0
    for name in ("l2", "l1"):
        scale = abs(expected[name]) or 1.0
        worst = max(worst, abs(digest[name] - expected[name]) / scale)
    if worst < DIGEST_TOLERANCE:
        print("digest matches the recorded baseline (rel = %.2e)" % worst)
        return 0
    sys.stderr.write(
        "digest moved for %s: relative change %.3e exceeds %.0e\n"
        "  recorded %r\n  measured %r\n"
        "the apply kernels no longer compute the same answer; if that is "
        "intended, re-record with --record\n"
        % (key, worst, DIGEST_TOLERANCE, expected, digest)
    )
    return 1


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--material", default="laplace")
    parser.add_argument("--element", default="HEX8", choices=sorted(ELEMENT_NODES))
    parser.add_argument("--refine", type=int, default=12, help="cells per side")
    parser.add_argument("--repeats", type=int, default=5)
    parser.add_argument("--keep", action="store_true", help="keep the build directory")
    parser.add_argument("--record", action="store_true",
                        help="re-record the answer baseline for this case")
    args = parser.parse_args(argv)

    compiler = _compiler()
    if compiler is None:
        sys.stderr.write("no C++ compiler available\n")
        return 2

    root = _repo_root()
    workdir = tempfile.mkdtemp(prefix="sfem_apply_bench_")
    generated = os.path.join(workdir, "generated")
    os.makedirs(generated)

    env = dict(os.environ)
    env["PYTHONPATH"] = os.path.join(root, "python") + os.pathsep + env.get("PYTHONPATH", "")
    completed = subprocess.run(
        [
            sys.executable, "-m",
            "codegen.framework.generators.%s" % args.material,
            "--out-dir", os.path.join(generated, args.material),
            *sum(
                (["--element", element] for element in _required_elements(args.element)),
                [],
            ),
        ],
        cwd=os.path.join(root, "python"), env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    if completed.returncode != 0:
        sys.stderr.write(completed.stdout.decode("utf-8", "replace"))
        return 1

    prefix = "%s_%s" % (args.material, args.element.lower())
    # HEX8 kernels are thin aliases that forward to the PROTEUS_HEX8 ones (see
    # KERNELS.md), so linking the requested element's operator alone leaves
    # every symbol undefined.  Link every operator the generator produced.
    operators = sorted(
        os.path.join(directory, name)
        for directory, _dirs, files in os.walk(generated)
        for name in files
        if name.endswith("_operator.cpp")
    )
    if not any(os.path.basename(path) == "%s_operator.cpp" % prefix for path in operators):
        sys.stderr.write("could not find the generated operator for %s\n" % prefix)
        return 1

    driver_path = os.path.join(workdir, "driver.cpp")
    with open(driver_path, "w", encoding="utf-8") as handle:
        handle.write(DRIVER.replace("@PREFIX@", prefix))

    binary = os.path.join(workdir, "apply_bench")
    flags = _include_flags(root, generated, args.material, 3)
    build = subprocess.run(
        [compiler, "-std=c++17", "-O3", "-march=native", "-fopenmp-simd",
         driver_path, *operators, *flags, "-o", binary],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    if build.returncode != 0:
        sys.stderr.write(build.stdout.decode("utf-8", "replace"))
        return 1

    print("material %s, element %s, %s -O3 -march=native" % (args.material, args.element, compiler))
    run = subprocess.run(
        [binary, str(args.refine), str(args.repeats)],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    output = run.stdout.decode("utf-8", "replace")
    print(output, end="")
    status = run.returncode or _check_digest(args, output)
    if not args.keep:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)
    else:
        print("build kept at %s" % workdir)
    return status


if __name__ == "__main__":
    sys.exit(main())
