"""Numerical parity and throughput for the matrix-free apply kernels.

Every step of the layering work so far has been gated on generated source being
byte-identical, which settles performance by construction: identical text
compiles to identical kernels.  That gate stops applying the moment output
changes on purpose -- which is exactly what unifying the coupled and mixed
emitters, or giving the mixed path packed apply, is for.

This is the gate that replaces it.  It generates a material, compiles the real
operator with the real flags, drives every matrix-free apply variant over a
structured mesh, and reports two things:

    parity      do the variants agree?  The SoA and AoS kernels are the same
                mathematics over differently laid-out inputs and must agree to
                round-off.  The float variants must agree to float precision.
                A refactor that changes an answer is caught here.

    throughput  MDOF/s per variant, so a change that preserves the answer and
                loses speed is caught too.  Byte-identity could never have told
                these apart, because it forbids both.

Usage::

    python -m codegen.framework.tools.apply_bench --element HEX8 --refine 12

The mesh is a Cartesian grid of hexahedra, so the geometry is affine and the
isoparametric and affine kernels are expected to agree as well.  That is a real
check on the geometry paths rather than a convenience: a bug in the adjugate
routing shows up as the two disagreeing.
"""

import argparse
import os
import subprocess
import sys
import tempfile


ELEMENT_NODES = {"HEX8": 8}

#: Elements whose kernels are aliases forwarding to another element's, so both
#: have to be generated for the result to link.  KERNELS.md asks for exactly
#: this: "HEX8 kernels should just wrap PROTEUS_HEX8 versions".
ALIAS_TARGETS = {"HEX8": ("PROTEUS_HEX8",)}


def _required_elements(element):
    return (element,) + ALIAS_TARGETS.get(element, ())


def _repo_root():
    path = os.path.dirname(os.path.abspath(__file__))
    while True:
        if os.path.isdir(os.path.join(path, "base")) and os.path.isdir(
            os.path.join(path, "python")
        ):
            return path
        parent = os.path.dirname(path)
        if parent == path:
            raise RuntimeError("could not locate the SFEM repository root")
        path = parent


def _compiler():
    for candidate in ("mpic++", "mpicxx", "c++"):
        try:
            subprocess.run([candidate, "--version"], stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, check=True)
            return candidate
        except (OSError, subprocess.CalledProcessError):
            continue
    return None


def _include_flags(root, generated_dir, material, dim):
    dirs = [
        os.path.join(generated_dir, material, "d%d" % dim),
        os.path.join(generated_dir, material),
        generated_dir,
        os.path.join(root, "base"),
        os.path.join(root, "build"),
        os.path.join(root, "build", "external", "smesh"),
        os.path.join(root, "external", "smesh", "src"),
    ]
    # Generated kernels may include hand-written SFEM operator headers -- the
    # PROTEUS_HEX8 Laplacian wraps hex8_laplacian_inline_cpu.hpp, for instance.
    operators_root = os.path.join(root, "operators")
    if os.path.isdir(operators_root):
        dirs.append(operators_root)
        for current, subdirs, _files in os.walk(operators_root):
            subdirs[:] = [d for d in subdirs if d not in ("cuda", "CMakeFiles")]
            dirs.append(current)
    smesh_src = os.path.join(root, "external", "smesh", "src")
    if os.path.isdir(smesh_src):
        dirs.extend(
            os.path.join(smesh_src, name)
            for name in sorted(os.listdir(smesh_src))
            if os.path.isdir(os.path.join(smesh_src, name))
        )
    flags = []
    for directory in dirs:
        if os.path.isdir(directory):
            flags.append("-I" + directory)
    return flags


DRIVER = r"""
// Generated by codegen.framework.tools.apply_bench.
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <vector>

#include "sfem_base.hpp"

extern "C" {
int @PREFIX@_jacobian_action_isoparametric_mesh_soa(
    const ptrdiff_t, const ptrdiff_t, idx_t **const, const geom_t *const *const,
    const double, const ptrdiff_t, const double *const, const ptrdiff_t, double *const);
int @PREFIX@_jacobian_action_isoparametric_mesh_aos(
    const ptrdiff_t, const ptrdiff_t, idx_t **const, const geom_t *const *const,
    const double *const, const double *const, double *const);
}

// A Cartesian grid of hexahedra: n cells per side, affine geometry.
struct Mesh {
    ptrdiff_t nelements = 0, nnodes = 0;
    std::vector<std::vector<idx_t>> elements;
    std::vector<std::vector<geom_t>> points;
    std::vector<idx_t *> element_ptrs;
    std::vector<const geom_t *> point_ptrs;
};

static Mesh build_grid(int n) {
    Mesh m;
    const int nn = n + 1;
    m.nnodes = (ptrdiff_t)nn * nn * nn;
    m.nelements = (ptrdiff_t)n * n * n;
    m.elements.assign(8, std::vector<idx_t>(m.nelements));
    m.points.assign(3, std::vector<geom_t>(m.nnodes));
    auto nid = [&](int i, int j, int k) { return (idx_t)((k * nn + j) * nn + i); };
    for (int k = 0; k < nn; ++k)
        for (int j = 0; j < nn; ++j)
            for (int i = 0; i < nn; ++i) {
                const idx_t id = nid(i, j, k);
                m.points[0][id] = (geom_t)i / (geom_t)n;
                m.points[1][id] = (geom_t)j / (geom_t)n;
                m.points[2][id] = (geom_t)k / (geom_t)n;
            }
    ptrdiff_t e = 0;
    for (int k = 0; k < n; ++k)
        for (int j = 0; j < n; ++j)
            for (int i = 0; i < n; ++i, ++e) {
                m.elements[0][e] = nid(i, j, k);
                m.elements[1][e] = nid(i + 1, j, k);
                m.elements[2][e] = nid(i + 1, j + 1, k);
                m.elements[3][e] = nid(i, j + 1, k);
                m.elements[4][e] = nid(i, j, k + 1);
                m.elements[5][e] = nid(i + 1, j, k + 1);
                m.elements[6][e] = nid(i + 1, j + 1, k + 1);
                m.elements[7][e] = nid(i, j + 1, k + 1);
            }
    for (auto &row : m.elements) m.element_ptrs.push_back(row.data());
    for (auto &row : m.points) m.point_ptrs.push_back(row.data());
    return m;
}

static double max_abs_diff(const std::vector<double> &a, const std::vector<double> &b) {
    double worst = 0.0;
    for (size_t i = 0; i < a.size(); ++i) worst = std::fmax(worst, std::fabs(a[i] - b[i]));
    return worst;
}

static double norm_inf(const std::vector<double> &a) {
    double worst = 0.0;
    for (double v : a) worst = std::fmax(worst, std::fabs(v));
    return worst;
}

int main(int argc, char **argv) {
    const int n = (argc > 1) ? std::atoi(argv[1]) : 12;
    const int repeats = (argc > 2) ? std::atoi(argv[2]) : 5;
    Mesh m = build_grid(n);

    std::vector<double> x(m.nnodes), out_soa(m.nnodes, 0.0), out_aos(m.nnodes, 0.0);
    for (ptrdiff_t i = 0; i < m.nnodes; ++i) x[i] = std::sin(0.7 * (double)i) + 0.25;
    const double kappa = 1.3;
    const double parameters[1] = {kappa};

    auto time_it = [&](const char *name, auto &&fn, std::vector<double> &out) {
        double best = 1e300;
        for (int r = 0; r < repeats; ++r) {
            std::fill(out.begin(), out.end(), 0.0);
            const auto t0 = std::chrono::steady_clock::now();
            const int status = fn();
            const auto t1 = std::chrono::steady_clock::now();
            if (status != 0) { std::printf("FAIL %s status=%d\n", name, status); std::exit(2); }
            best = std::fmin(best, std::chrono::duration<double>(t1 - t0).count());
        }
        const double mdofs = (double)m.nnodes / best / 1e6;
        std::printf("  %-46s %9.3f ms   %8.1f MDOF/s\n", name, best * 1e3, mdofs);
    };

    std::printf("mesh: %lld elements, %lld nodes\n", (long long)m.nelements, (long long)m.nnodes);
    time_it("jacobian_action_isoparametric_mesh_soa",
            [&] { return @PREFIX@_jacobian_action_isoparametric_mesh_soa(
                      m.nelements, m.nnodes, m.element_ptrs.data(), m.point_ptrs.data(),
                      kappa, 1, x.data(), 1, out_soa.data()); },
            out_soa);
    time_it("jacobian_action_isoparametric_mesh_aos",
            [&] { return @PREFIX@_jacobian_action_isoparametric_mesh_aos(
                      m.nelements, m.nnodes, m.element_ptrs.data(), m.point_ptrs.data(),
                      parameters, x.data(), out_aos.data()); },
            out_aos);

    const double scale = norm_inf(out_soa);
    const double diff = max_abs_diff(out_soa, out_aos);
    const double rel = (scale > 0.0) ? diff / scale : diff;
    std::printf("\nparity soa vs aos: max|diff| = %.3e   relative = %.3e\n", diff, rel);
    if (!(rel < 1e-12)) { std::printf("PARITY FAILED\n"); return 1; }
    std::printf("PARITY OK\n");
    return 0;
}
"""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--material", default="laplace")
    parser.add_argument("--element", default="HEX8", choices=sorted(ELEMENT_NODES))
    parser.add_argument("--refine", type=int, default=12, help="cells per side")
    parser.add_argument("--repeats", type=int, default=5)
    parser.add_argument("--keep", action="store_true", help="keep the build directory")
    args = parser.parse_args(argv)

    compiler = _compiler()
    if compiler is None:
        sys.stderr.write("no C++ compiler available\n")
        return 2

    root = _repo_root()
    workdir = tempfile.mkdtemp(prefix="sfem_apply_bench_")
    generated = os.path.join(workdir, "generated")
    os.makedirs(generated)

    env = dict(os.environ)
    env["PYTHONPATH"] = os.path.join(root, "python") + os.pathsep + env.get("PYTHONPATH", "")
    completed = subprocess.run(
        [
            sys.executable, "-m",
            "codegen.framework.generators.%s" % args.material,
            "--out-dir", os.path.join(generated, args.material),
            *sum(
                (["--element", element] for element in _required_elements(args.element)),
                [],
            ),
        ],
        cwd=os.path.join(root, "python"), env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    if completed.returncode != 0:
        sys.stderr.write(completed.stdout.decode("utf-8", "replace"))
        return 1

    prefix = "%s_%s" % (args.material, args.element.lower())
    # HEX8 kernels are thin aliases that forward to the PROTEUS_HEX8 ones (see
    # KERNELS.md), so linking the requested element's operator alone leaves
    # every symbol undefined.  Link every operator the generator produced.
    operators = sorted(
        os.path.join(directory, name)
        for directory, _dirs, files in os.walk(generated)
        for name in files
        if name.endswith("_operator.cpp")
    )
    if not any(os.path.basename(path) == "%s_operator.cpp" % prefix for path in operators):
        sys.stderr.write("could not find the generated operator for %s\n" % prefix)
        return 1

    driver_path = os.path.join(workdir, "driver.cpp")
    with open(driver_path, "w", encoding="utf-8") as handle:
        handle.write(DRIVER.replace("@PREFIX@", prefix))

    binary = os.path.join(workdir, "apply_bench")
    flags = _include_flags(root, generated, args.material, 3)
    build = subprocess.run(
        [compiler, "-std=c++17", "-O3", "-march=native", "-fopenmp-simd",
         driver_path, *operators, *flags, "-o", binary],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    if build.returncode != 0:
        sys.stderr.write(build.stdout.decode("utf-8", "replace"))
        return 1

    print("material %s, element %s, %s -O3 -march=native" % (args.material, args.element, compiler))
    run = subprocess.run([binary, str(args.refine), str(args.repeats)])
    if not args.keep:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)
    else:
        print("build kept at %s" % workdir)
    return run.returncode


if __name__ == "__main__":
    sys.exit(main())
