import sympy as sp
from sympy.codegen.ast import CodeBlock, For, String
from sympy.printing import ccode
from sympy.tensor.tensor import TensorHead, TensorIndexType, tensor_indices

# Dimension symbol kept symbolic so the tensor machinery can reason about extents.
N = sp.symbols('N', integer=True, positive=True)

# Tensor index type for an N-by-N matrix; dummy_fmt controls autogenerated summed indices.
matrix_space = TensorIndexType('matrix', dim=N, dummy_name='d')
i, j, k = tensor_indices('i j k', matrix_space)

# Tensor heads representing the matrices involved in GEMM.
A = TensorHead('A', [matrix_space, matrix_space])
B = TensorHead('B', [matrix_space, matrix_space])
C = TensorHead('C', [matrix_space, matrix_space])

# Einstein notation for matrix multiplication: C(i, j) = A(i, k) * B(-k, j).
gemm_rhs = A(i, k) * B(-k, j)

# SymPy canonicalises dummy indices (k -> d_0); restore the original symbol for readability.
indices = gemm_rhs.get_indices()
gemm_rhs = gemm_rhs.xreplace({indices[1]: k, indices[2]: -k})

# Present the Einstein form before lowering to loops.
print('Einstein form: {}'.format(sp.Eq(C(i, j), gemm_rhs)))

# Identify free (loop) and dummy (reduction) indices from the tensor expression.
free_indices = [idx for idx, pos in sorted(gemm_rhs.free, key=lambda item: item[1])]
all_indices = gemm_rhs.get_indices()
dummy_names = []
for first_pos, _ in gemm_rhs.dum:
    name = all_indices[first_pos].name
    if name not in dummy_names:
        dummy_names.append(name)

loop_symbols = {
    idx.name: sp.symbols(idx.name, integer=True)
    for idx in free_indices
}
loop_symbols.update({name: sp.symbols(name, integer=True) for name in dummy_names})

def fmt(name, *labels):
    return name + ''.join('[{}]'.format(label) for label in labels)

free_names = [idx.name for idx in free_indices]
reduction_names = dummy_names

if len(free_names) != 2 or len(reduction_names) != 1:
    raise ValueError('This example expects two free indices and a single reduction index.')

row_label, col_label = free_names
reduction_label = reduction_names[0]

init_stmt = String('{} = 0;'.format(fmt('C', row_label, col_label)))
update_stmt = String('{} += {}*{};'.format(
    fmt('C', row_label, col_label),
    fmt('A', row_label, reduction_label),
    fmt('B', reduction_label, col_label),
))

reduction_block = [update_stmt]
for name in reversed(reduction_names):
    reduction_block = [For(loop_symbols[name], sp.Range(N), reduction_block)]

loop_body = [init_stmt] + reduction_block
for name in reversed(free_names):
    loop_body = [For(loop_symbols[name], sp.Range(N), loop_body)]

print('C loops:')
print(ccode(CodeBlock(loop_body[0])))
