#pragma once

// The manufactured solution of Farrell, Mitchell & Wechsung, SIAM J. Sci. Comput. 41(5),
// A3073-A3096 (arXiv:1810.03315), equation 5.2, and the body force that drives it.
//
// GENERATED by spikes/cvfem/gen_mms_case.py -- edit that, not this.
//
// Templated on the scalar type on purpose: cvfem_ns_channel_case.hpp, which includes this,
// is deliberately free of the kernel headers' file-scope scalar_t so that it can sit next to
// either the solver core or the benchmark layouts. Using scalar_t here would break that.
//
// The velocity is a 2D field on [0,2]^2 extended as u = (u1(x,y), u2(x,y), 0); the pressure
// is unchanged in z. Two properties are asserted at generation time rather than assumed:
// div(u) == 0 exactly, and the z-momentum forcing vanishes identically.
//
// Parameter mapping. Their momentum equation is (u.grad)u - (1/Re) lap(u) + grad p = f;
// ours is rho (u.grad)u - mu lap(u) + grad p = f. Call these with rho = 1 and mu = 1/Re and
// their pressure formula is our exact pressure with no rescaling. Re is passed separately
// because the manufactured pressure genuinely depends on it -- evaluating p at a nominal Re
// while the operator runs at another silently corrupts the measured pressure convergence.
//
// The domain is not free: the pressure gauge constant 1408/33075 - 8/(5 Re) makes p exactly
// zero-mean over [0,2]^2 and nowhere else.
//
// Cross-check worth knowing: u1(x, y=2) = x^2 (2-x)^2, which is exactly the regularized
// lid profile of the same paper's cavity in the x-direction.

#include <cmath>

namespace cvfem_mms {

    template <typename T>
    inline void velocity(const T x, const T y, const T /*z*/,
                       T &ux, T &uy, T &uz) {
        const T x0 = pow(x, 2);
        const T x1 = pow(y, 2);
        ux = (1.0/4.0)*x0*y*pow(x - 2, 2)*(x1 - 2);
        uy = -1.0/4.0*x*x1*(x1 - 4)*(-3*x + x0 + 2);
        uz = 0;
    }

    template <typename T>
    inline void pressure(const T x, const T y, const T /*z*/,
                       const T Re, T &p) {
        const T x0 = 1.0/Re;
        const T x1 = pow(x, 4);
        const T x2 = pow(y, 2);
        p = (1.0/5.0)*x*x0*y*(-15*pow(x, 3) + 10*pow(x, 2)*x2 - 30*x*(x2 - 2) + 3*x1 + 20*x2 - 40) - 8.0/5.0*x0 - 1.0/128.0*x1*x2*pow(x - 2, 4)*(-2*x2 + pow(y, 4) + 8) + 1408.0/33075.0;
    }

    template <typename T>
    inline void body_force(const T x, const T y, const T /*z*/,
                       const T rho, const T mu, const T Re,
                       T &fx, T &fy, T &fz) {
        const T x0 = 1.0/Re;
        const T x1 = pow(x, 3);
        const T x2 = pow(x, 4);
        const T x3 = pow(y, 2);
        const T x4 = x3 - 2;
        const T x5 = x*x4;
        const T x6 = pow(x, 2);
        const T x7 = 20*x3;
        const T x8 = x - 2;
        const T x9 = pow(x8, 4);
        const T x10 = y*(-2*x3 + pow(y, 4) + 8);
        const T x11 = x10*x9;
        const T x12 = pow(x8, 2);
        const T x13 = 4*x8;
        const T x14 = x - 1;
        const T x15 = x3 - 4;
        const T x16 = 3*x3;
        const T x17 = -3*x + x6 + 2;
        const T x18 = x17*(x16 - 2);
        const T x19 = pow(y, 3);
        const T x20 = 2*x;
        fx = (1.0/160.0)*x0*y*(-5*Re*(16*mu*(3*x12*x6 + x4*(x*x13 + x12 + x6)) - 2*rho*x1*x12*y*(x13*x14*pow(x4, 2) - x15*x18) + x1*x11 + x10*x2*pow(x8, 3)) + 32*x*(x*x7 + 12*x1 - 30*x3 - 45*x6 + 60) - 480*x1 + 96*x2 + 320*x3*x6 + 640*x3 - 960*x5 - 1280);
        fy = x0*(-1.0/64.0*Re*(-32*mu*(x14*x15*x16 + x18*x20) + 4*rho*x15*x19*x4*x6*(x12*(x*(x20 - 3) + x17) - 4*pow(x17, 2)) + x11*x2 + 2*x19*x2*x9*(x3 - 1)) + 4*x*x17*x3 + (1.0/5.0)*x*(-15*x1 + 3*x2 + 10*x3*x6 - 30*x5 + x7 - 40));
        fz = 0;
    }

}  // namespace cvfem_mms
