#!/usr/bin/env bash

set -e

elem_type=HEX8

which box_mesh.py

N=20
box_mesh.py mesh -x $N -y $N -z $N --cell_type=$elem_type --tx=-0.5 --ty=-0.5 --tz=-0.5
box_mesh.py obstacle_mesh -x 2 -y 4 -z 4 --cell_type=TET4 --width=2 --height=2 --depth=2 --tx=-1 --ty=-1 --tz=-1

skin mesh mesh/skin
skin obstacle_mesh obstacle_mesh/skin

mkdir -p obstacle
echo "# Generated by setup.sh" > obstacle/meta.yaml
# echo "surface: ../mesh/surface/left" >> obstacle/meta.yaml
echo "surface: ../mesh/skin" >> obstacle/meta.yaml
echo "sdf: sdf" >> obstacle/meta.yaml
echo "rpath: true" >> obstacle/meta.yaml
echo "variational: false" >> obstacle/meta.yaml

margin=0.5
hmax=0.01
mkdir -p obstacle/sdf
mesh_to_sdf.py obstacle_mesh/skin obstacle/sdf/sdf.float32.raw --hmax=$hmax --margin=$margin
raw_to_xdmf.py obstacle/sdf/sdf.float32.raw
cp obstacle/sdf/metadata_sdf.float32.yml obstacle/sdf/meta.yaml 

