#!/usr/bin/env python3
"""Figures and tables built from the measurements (paper F5-F8, T1-T3).

Stdlib only, and every emitter carries a selftest, following the repository's report
generators: the Alps uenv has no numpy or matplotlib, so anything that cannot run where the
measurements are taken will go stale.

Inputs live in ../data and are copied verbatim from the job that produced them, so the job id
is part of the filename and a number in the paper can be traced back to a run. Nothing here
edits a measurement; it only reshapes one.

Usage:
    python3 perf_figures.py --out ../figures --tables ../tables
    python3 perf_figures.py --selftest
"""

import argparse
import collections
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

# One row of the determinism table. Anchored on the two "<d> distinct / <n> runs" cells so
# that an appended marker such as "(INCOMPLETE)" cannot shift the fields.
_DET_ROW = re.compile(
    r"^(atomic|packed|colored|store)\s+(\w+)\s+"
    r"(\d+)\s+distinct\s*/\s*(\d+)\s+runs\S*\s+"
    r"(\d+)\s+distinct\s*/\s*(\d+)\s+runs")

PREAMBLE = ("%% Generated by wip/paper/python/perf_figures.py -- do not edit.\n"
            "%% Regenerate with: make figures\n")


# ---------------------------------------------------------------------------------------------
# T2: reproducibility by layout
# ---------------------------------------------------------------------------------------------

def parse_determinism(path):
    """Read jobs/det_layout.sbatch's output.

    The job prints one row per (layout, operation) as "<d> distinct / <n> runs" for two
    questions: repeats at a fixed thread count, and one run at each of several thread counts.
    Returns [(layout, op, (d_a, n_a), (d_b, n_b))] plus the header facts, so the caption can
    state the problem size and the thread counts rather than have them typed in.
    """
    rows, meta = [], {}
    for line in open(path):
        s = line.strip()
        if s.startswith("### host"):
            # "### host nid006545  n=100  repeats=3 at 72t  thread sweep: 1 8 36 72"
            parts = s.split()
            meta["host"] = parts[2]
            for tok in parts:
                if tok.startswith("n="):
                    meta["n"] = tok[2:]
                if tok.startswith("repeats="):
                    meta["repeats"] = tok[len("repeats="):]
            if "thread sweep:" in s:
                meta["threads"] = s.split("thread sweep:")[1].strip()
            continue
        # layout op <d> distinct / <n> runs   <d> distinct / <n> runs
        #
        # Matched rather than split on whitespace: the job appends "(INCOMPLETE)" to a cell
        # whose runs did not all produce a fingerprint, which shifts every later field and
        # silently mis-parsed the row when this counted tokens.
        m = _DET_ROW.match(s)
        if m:
            rows.append((m.group(1), m.group(2),
                         (int(m.group(3)), int(m.group(4))),
                         (int(m.group(5)), int(m.group(6)))))
    return rows, meta


OP_NAME = {"res": "residual", "jac": "Jacobian action"}


def macros_determinism(rows, meta):
    """The facts the caption and prose quote, so no digit is typed twice."""
    out = [PREAMBLE]
    out.append(r"\newcommand{\detHost}{%s}" % meta.get("host", "?"))
    out.append(r"\newcommand{\detN}{%s}" % meta.get("n", "?"))
    out.append(r"\newcommand{\detRepeats}{%s}" % meta.get("repeats", "?"))
    out.append(r"\newcommand{\detThreads}{%s}" % meta.get("threads", "?").replace(" ", ", "))
    for layout, op, a, b in rows:
        key = (layout + op).capitalize()
        out.append(r"\newcommand{\det%sRep}{%d}" % (key, a[0]))
        out.append(r"\newcommand{\det%sThr}{%d}" % (key, b[0]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# T3: memory footprint
# ---------------------------------------------------------------------------------------------

# Widths the format fixes, named here so the arithmetic below can be read against the code.
PACK_IDX_BYTES = 2    # pack_idx_t is uint16_t; this is what bounds a pack's node count
GLOBAL_IDX_BYTES = 4  # idx_t in the flat connectivity and in the BSR column index
GEOM_BYTES = 4        # geom_t is float
NODES_PER_ELEM = 8    # HEX8
BLOCK = 4             # 4x4 blocks: three velocity components and pressure


def footprint_rows(csv_path):
    """Bytes per degree of freedom for the representations the paper compares.

    THIS IS NOT A TIMING, which is why it may be taken from an older campaign. Every quantity
    below is a deterministic function of the mesh size and the storage precision -- the row
    count, the block count, the index widths -- so it does not inherit the node-to-node
    variation that makes two campaigns' THROUGHPUTS incomparable. The distinction is worth
    making explicitly, because the rule against mixing campaigns is otherwise absolute.

    Counted on both sides: only what the apply must read to evaluate the operator. Solution
    and result vectors are excluded from both, since they are identical for every layout and
    including them would flatter the matrix.
    """
    rows = {}
    with open(csv_path) as fh:
        head = fh.readline().rstrip("\n").split(",")
        ix = {name: i for i, name in enumerate(head)}
        for line in fh:
            f = line.rstrip("\n").split(",")
            if len(f) != len(head) or f[ix["operation"]] != "bsr_apply":
                continue
            n = int(f[ix["cube_n"]])
            store = f[ix["bsr_storage"]]
            key = (n, store)
            if key in rows:
                continue
            dofs = int(f[ix["dofs"]])
            nodes = int(f[ix["nodes"]])
            elems = int(f[ix["elements"]])
            blocks = int(f[ix["bsr_nnz"]])
            vals = float(f[ix["bsr_values_MiB"]]) * 1024 * 1024
            # The matrix also carries its pattern: one column index per block, one row pointer
            # per block row. Omitting it would understate the matrix by ~3%.
            idx = blocks * GLOBAL_IDX_BYTES + (nodes + 1) * GLOBAL_IDX_BYTES
            # The matrix-free side reads the mesh: pack-local connectivity and coordinates.
            conn = elems * NODES_PER_ELEM * PACK_IDX_BYTES
            coords = nodes * 3 * GEOM_BYTES
            rows[key] = {
                "n": n, "store": store, "dofs": dofs,
                "bsr": (vals + idx) / dofs,
                "packed": (conn + coords) / dofs,
            }
    return [rows[k] for k in sorted(rows)]


def parse_meshfoot(path):
    """Read the bench's --mesh-footprint report: {pack_size: {array: bytes}} plus counts.

    This replaces an earlier arithmetic model of the same quantity, which is why there is no
    model left to compare against. The model had to guess the two numbers that decide the
    answer -- how many ghost entries the packs produce and how many rows the reduction graph
    has -- because neither has a closed form: they depend on how the pack boundaries happen to
    cut the mesh. It guessed both from the mean node count per pack and was wrong by about
    20%. The bench now reports every array's own nbytes(), so this parser reads measurements.
    """
    out, cur = {}, None
    for line in open(path):
        line = line.strip()
        if line.startswith("@@@ pack_size"):
            cur = int(line.split()[-1])
            out[cur] = {"arrays": {}}
        elif cur is None:
            continue
        elif line.startswith("### mesh footprint"):
            for k in ("n_nodes", "n_elements", "dofs"):
                m = re.search(k + r"=(\d+)", line)
                if m:
                    out[cur][k] = int(m.group(1))
        elif line.startswith("### n_packs"):
            for k in ("n_packs", "ghost_entries", "ghost_reduce_rows"):
                m = re.search(k + r"=(\d+)", line)
                if m:
                    out[cur][k] = int(m.group(1))
        else:
            f = line.split()
            if len(f) == 3 and ("." in f[0]) and f[1].isdigit():
                out[cur]["arrays"][f[0]] = int(f[1])
    return {k: v for k, v in out.items() if v.get("dofs") and v["arrays"]}


# The pack size the paper reports the footprint at: the shipped default, so the table describes
# the format as a user gets it. The alternative -- quoting the best-performing pack size -- would
# report a configuration nobody runs by default.
MESHFOOT_PACK = 1024
# The pack size the performance sweep favours, quoted alongside because the footprint improves
# in the same direction: bigger packs mean proportionally fewer ghosts.
MESHFOOT_PACK_BIG = 4096


def meshfoot_totals(mf, pack=MESHFOOT_PACK):
    """Three totals for the packed mesh's topology, because three different questions get asked.

    *as implemented* is every array the format allocates today. *working set* drops
    ``node_map``, the permutation between packed and unpacked numbering: the apply never reads
    it, and a solver whose fields live in packed numbering throughout does not either. *floor*
    additionally narrows the two reduction-graph offset arrays from 64 to 32 bits, which their
    own lengths permit with three orders of magnitude to spare -- the graph indexes fewer than a
    million entries and spends eight bytes per index doing it.

    All three are reported rather than the flattering one. The gap between the first and the
    third is not a property of the format; it is 64-bit offsets into a small array plus a
    permutation the operator does not read, and the paper says so.
    """
    d = mf.get(pack)
    if not d:
        return None
    a, dofs = d["arrays"], float(d["dofs"])
    impl = a["packed.topology_total"]
    node_map = a.get("packed.node_map", 0)
    # Halving the two offset arrays: ptrdiff_t -> a 32-bit count, which their lengths admit.
    reduce64 = a.get("packed.ghost_reduce_ptr", 0) + a.get("packed.ghost_reduce_idx", 0)
    std = a["standard.topology_total"]
    pts = a["shared.points"]
    working = impl - node_map
    floor = working - reduce64 // 2
    return {
        "pack": pack, "dofs": d["dofs"], "nodes": d["n_nodes"], "n_packs": d["n_packs"],
        "ghost_entries": d["ghost_entries"], "ghost_rows": d["ghost_reduce_rows"],
        "std": std / dofs, "pts": pts / dofs,
        "impl": impl / dofs, "working": working / dofs, "floor": floor / dofs,
        "node_map": node_map / dofs, "reduce_saving": (reduce64 // 2) / dofs,
        "conn": a["packed.elements"] / dofs,
        "r_impl": impl / std, "r_working": working / std, "r_floor": floor / std,
        "r_impl_pts": (impl + pts) / (std + pts),
        # The whole mesh, coordinates included. Reported separately because the coordinates are
        # byte-for-byte identical in both representations, so including them dilutes the ratio
        # without changing any quantity the format controls.
        "std_pts": (std + pts) / dofs, "impl_pts": (impl + pts) / dofs,
    }


def macros_meshfoot(mf):
    """Every footprint figure the prose quotes, at the default pack size and the larger one."""
    t = meshfoot_totals(mf)
    if not t:
        return None
    out = [PREAMBLE]
    for k, fmt in (("std", "%.2f"), ("impl", "%.2f"), ("working", "%.2f"), ("floor", "%.2f"),
                   ("node_map", "%.2f"), ("reduce_saving", "%.2f"), ("conn", "%.2f"),
                   ("std_pts", "%.1f"), ("impl_pts", "%.1f")):
        out.append(r"\newcommand{\fp%s}{%s}" % (k.title().replace("_", ""), fmt % t[k]))
    for k in ("r_impl", "r_working", "r_floor", "r_impl_pts"):
        out.append(r"\newcommand{\fp%sPct}{%.0f}"
                   % (k[2:].title().replace("_", ""), 100.0 * t[k]))
    out.append(r"\newcommand{\fpPack}{%d}" % t["pack"])
    out.append(r"\newcommand{\fpGhostPct}{%.0f}"
               % (100.0 * t["ghost_entries"] / float(t["nodes"])))
    big = meshfoot_totals(mf, MESHFOOT_PACK_BIG)
    if big:
        out.append(r"\newcommand{\fpPackBig}{%d}" % big["pack"])
        out.append(r"\newcommand{\fpFloorBigPct}{%.0f}" % (100.0 * big["r_floor"]))
        out.append(r"\newcommand{\fpImplBigPct}{%.0f}" % (100.0 * big["r_impl"]))
    return "\n".join(out) + "\n"


def table_footprint(rows, mesh=None, n=128):
    """T3. What each representation must read, per degree of freedom, at one size.

    One size rather than four: the per-dof figures move by under two per cent across the range,
    so repeating them four times spent a third of a column to say the same thing.

    ``mesh`` is the measured mesh footprint from meshfoot_totals(), not a model. The packed
    figure it contributes is the format AS IMPLEMENTED, including the two items the text then
    names as avoidable; putting the reduced figure here instead would quote the format at its
    best in the table and its worst in the prose.
    """
    at_n = [r for r in rows if r["_n"] == n and r["operation"] == "bsr_apply"]
    if not at_n:
        return None
    out = [PREAMBLE, r"\small", r"\begin{tabular}{@{}lrr@{}}", r"\toprule",
           r"representation & B/dof & vs.\ packed mesh \\", r"\midrule"]
    base = mesh["impl"] if mesh else None
    if mesh:
        out.append(r"packed mesh & %.1f & --- \\" % mesh["impl"])
        out.append(r"standard mesh & %.1f & $%.2f\times$ \\"
                   % (mesh["std"], mesh["std"] / base))
        out.append(r"\midrule")
    seen = set()
    for store in ("f32", "f64"):
        c = [r for r in at_n if r["bsr_storage"] == store]
        if not c or store in seen:
            continue
        seen.add(store)
        b = c[0]
        blocks, nodes = int(b["bsr_nnz"]), int(b["nodes"])
        vals = float(b["bsr_values_MiB"]) * 1024 * 1024
        idx = blocks * GLOBAL_IDX_BYTES + (nodes + 1) * GLOBAL_IDX_BYTES
        per = (vals + idx) / b["_dofs"]
        rel = (r"$%.0f\times$" % (per / base)) if base else "---"
        out.append(r"assembled matrix, \texttt{%s} & %.0f & %s \\" % (store, per, rel))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F6: thread scaling   (restored -- lost to an over-wide block replacement, see README)
# ---------------------------------------------------------------------------------------------

# What the scaling figure draws, in drawing order. The coloured sweep is measured and quoted in
# the text but is not drawn: it differs from the packed layout in one thing only, the barrier per
# colour, and that comparison belongs to the throughput section rather than to a scaling figure
# whose subject is the departure from ideal. The higher-order arm is the same operator through a
# limited deferred correction, so the pair says whether the scaling depends on the scheme.
SCALING_SERIES = (
    ("packed", "res",   "PackA", "*",       r"\texttt{packed}"),
    ("atomic", "res",   "PackD", "square*", r"\texttt{atomic}"),
    ("packed", "resho", "PackA", "o",       r"\texttt{packed}, higher order"),
    ("atomic", "resho", "PackD", "square",  r"\texttt{atomic}, higher order"),
)

LAYOUT_STYLE = {
    "packed":  ("PackA", "*"),
    "atomic":  ("PackD", "square*"),
    "colored": ("PackC", "triangle*"),
}


def parse_scaling(path):
    """Read jobs/thread_scaling.sbatch's table.

    Returns {(layout, op): [(threads, mdof)]} plus meta. Rows whose throughput is a dash are
    dropped rather than read as zero: a missing measurement must not become a point at the
    origin, which would bend a scaling curve toward superlinearity.
    """
    series, meta = {}, {}
    for line in open(path):
        t = line.strip()
        if t.startswith("### host"):
            parts = t.split()
            meta["host"] = parts[2]
            for tok in parts:
                if tok.startswith("n="):
                    meta["n"] = tok[2:]
            continue
        f = t.split()
        if len(f) >= 4 and f[0] in LAYOUT_STYLE and f[1] in ("res", "jac", "resho"):
            if f[3] == "-":
                continue
            try:
                thr, mdof = int(f[2]), float(f[3])
            except ValueError:
                continue
            series.setdefault((f[0], f[1]), []).append((thr, mdof))
            if len(f) > 4 and f[4] != "-":
                meta["packs"] = f[4]
    for k in series:
        series[k].sort()
    return series, meta


def fig_scaling(series, meta, op="res"):
    """F6. Throughput against thread count, log-log with an ideal line.

    Log-log because the content is the DEPARTURE from ideal, and on linear axes the low thread
    counts are invisible. Four curves: two layouts, each at first order and with the limited
    higher-order flux, so the figure answers whether the layout's scaling depends on the scheme
    as well as how each layout scales.
    """
    # The y limits are FIXED rather than left to pgfplots, because the ideal line's label has to be
    # rotated to the angle that line is actually drawn at, and that angle depends on how many
    # decades the axis spans. With the limits floating, the rotation could only ever be a guess --
    # which is what it was: a hard-coded 37 degrees against a line drawn at about 23.
    H_OVER_W = 0.55
    ys = [m for pts in series.values() for _t, m in pts]
    ymin, ymax = (min(ys) * 0.85, max(ys) * 1.2) if ys else (1.0, 10.0)
    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{loglogaxis}[",
           r"  width=\columnwidth, height=%.3f\columnwidth," % H_OVER_W,
           r"  xlabel={OpenMP threads}, ylabel={MDOF/s},",
           r"  log basis x=2, xtick={1,2,4,8,18,36,72}, xticklabels={1,2,4,8,18,36,72},",
           r"  ymin=%.4f, ymax=%.4f," % (ymin, ymax),
           r"  legend pos=north west, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    # The ideal line is anchored on the SLOWEST curve at one thread, so the reference is not
    # drawn from the layout being advocated.
    base = None
    for lay, o, _c, _m, _l in SCALING_SERIES:
        pts = series.get((lay, o))
        if pts and pts[0][0] == 1 and (base is None or pts[0][1] < base[1]):
            base = pts[0]
    if base:
        t0, m0 = base
        out.append(r"\addplot[black!45,dashed,no marks,forget plot] coordinates "
                   r"{(1,%.4f) (72,%.4f)};" % (m0, m0 * 72.0 / t0))
        # ON the line and anchored north, so the label hangs just under it, parallel, instead of
        # being set below it at a guessed height and rotated up across it. Everything measured
        # lies ABOVE this line -- it is anchored on the slowest curve at one thread -- so the
        # space underneath is empty and the label has it to itself.
        ang = math.degrees(math.atan2(H_OVER_W / math.log10(ymax / ymin),
                                      1.0 / math.log10(72.0)))
        xlab = 24.0
        out.append(r"\node[black!55,font=\tiny,rotate=%.1f,anchor=north,inner sep=2pt] "
                   r"at (axis cs:%.0f,%.2f) {ideal};" % (ang, xlab, m0 * xlab / t0))
    for lay, o, col, mark, lab in SCALING_SERIES:
        pts = series.get((lay, o))
        if not pts:
            continue
        out.append(r"\addplot[%s,mark=%s,mark size=1.4pt,thick] coordinates {%s};"
                   % (col, mark, " ".join("(%d,%.4f)" % q for q in pts)))
        out.append(r"\addlegendentry{%s}" % lab)
    out.append(r"\end{loglogaxis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def macros_scaling(series, meta):
    """Endpoints, speedups and efficiencies, so the prose quotes no typed digit."""
    out = [PREAMBLE]
    out.append(r"\newcommand{\scaleHost}{%s}" % meta.get("host", "?"))
    out.append(r"\newcommand{\scalePacks}{%s}" % meta.get("packs", "?"))
    # Packs per thread, which is the quantity the scaling and pack-size sections both reason
    # about. Derived here so the prose stops carrying it as a typed word.
    try:
        out.append(r"\newcommand{\scalePacksPerThread}{%.0f}"
                   % (int(meta["packs"]) / 72.0))
    except (KeyError, ValueError):
        pass
    names = {"res": "Res", "jac": "Jac", "resho": "Resho"}
    for (layout, op), pts in sorted(series.items()):
        d = dict(pts)
        if not d:
            continue
        one, nthr = d.get(1), max(d)
        top = d.get(nthr)
        if not one or not top:
            continue
        key = layout.capitalize() + names.get(op, op)
        out.append(r"\newcommand{\scale%sOne}{%.1f}" % (key, one))
        out.append(r"\newcommand{\scale%sTop}{%.0f}" % (key, top))
        out.append(r"\newcommand{\scale%sSpeedup}{%.1f}" % (key, top / one))
        out.append(r"\newcommand{\scale%sEff}{%.0f}" % (key, 100.0 * (top / one) / nthr))
    # The single-thread layout factor the prose quotes. It is a ratio of two numbers already
    # emitted above, so it moved with the measurements while the text kept the value it was
    # written with -- which is exactly the kind of number that must not be typed by hand.
    ones = {layout: dict(pts).get(1) for (layout, op), pts in series.items() if op == "res"}
    if ones.get("packed") and ones.get("atomic"):
        out.append(r"\newcommand{\scaleResLayoutOne}{%.1f}" % (ones["packed"] / ones["atomic"]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# M6: the machine's memory bound   (restored)
# ---------------------------------------------------------------------------------------------

def parse_stream(path):
    """Triad rate per thread count, in GB/s.

    STREAM reports MB/s in powers of ten, so the conversion is by 1000 and not 1024; getting
    that wrong overstates the bound by 7% and makes every roofline efficiency look worse.
    """
    rates, threads = {}, None
    for line in open(path):
        t = line.strip()
        if t.startswith("###") and "threads" in t:
            try:
                threads = int(t.split()[1])
            except (IndexError, ValueError):
                threads = None
            continue
        if t.startswith("Triad:") and threads is not None:
            rates[threads] = float(t.split()[1]) / 1000.0
    return rates


def macros_stream(rates):
    """The bound at the measured thread count, and the peak, which are not the same.

    Bandwidth saturates below the full socket, so the 72-thread figure -- the configuration
    every kernel here runs in -- is LOWER than the machine's best. Both are emitted and the
    paper quotes the one matching its configuration, not the flattering one.
    """
    if not rates:
        return PREAMBLE
    full = max(rates)
    best_t = max(rates, key=lambda k: rates[k])
    out = [PREAMBLE]
    out.append(r"\newcommand{\streamTriad}{%.0f}" % rates[full])
    out.append(r"\newcommand{\streamThreads}{%d}" % full)
    out.append(r"\newcommand{\streamPeak}{%.0f}" % rates[best_t])
    out.append(r"\newcommand{\streamPeakThreads}{%d}" % best_t)
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F5 / T1: throughput and the term-completeness ladder
# ---------------------------------------------------------------------------------------------

def read_campaign(path):
    """Rows of a layout-campaign CSV, as dicts, with the numeric fields converted.

    REFUSES A CSV SPANNING SEVERAL HOSTS. The tables below keep the best reading per
    configuration, so across two nodes a packed row and the atomic row it is divided by can come
    from different machines, which manufactures a layout ratio out of node-to-node variation
    (5-11% here). The campaign appends to its csv and the batch jobs once wrote into a fixed
    directory, so this is a situation that has actually arisen, not a hypothetical.
    """
    import csv as _csv
    with open(path) as fh:
        rows = list(_csv.DictReader(fh))
    hosts = sorted({r.get("host", "?") for r in rows})
    if len(hosts) > 1:
        raise ValueError("campaign spans %d hosts (%s); split it by host before plotting"
                         % (len(hosts), ", ".join(hosts)))
    out = []
    for r in rows:
        try:
            r["_n"] = int(r["cube_n"])
            r["_dofs"] = int(r["dofs"])
            r["_mdof"] = float(r["MDOF_s"])
        except (KeyError, ValueError):
            continue
        out.append(r)
    return out, (hosts[0] if hosts else "?")


def _bare(r):
    """The bare element kernel: no solver terms carried."""
    return (r.get("ran_rc") == "off" and r.get("ran_boundary") == "off"
            and r.get("transient") in ("0", "", None)
            and r.get("pgrad_per_apply") in ("0", "", None))


def best(rows, **eq):
    """Best observed rate among rows matching every keyword.

    Best rather than mean, because background load can only make a run slower -- the same
    convention the repository's own kernel report uses.
    """
    sel = [r for r in rows if all(r.get(k) == v for k, v in eq.items())]
    return max((r["_mdof"] for r in sel), default=None)


def fig_throughput(rows, host, op="residual"):
    """F5. Throughput against problem size for the three representations.

    The assembled matrix is drawn at both storage precisions because halving the value width is
    essentially the only lever a bandwidth-bound SpMV has, and it is the fairest version of the
    comparison.
    """
    sizes = sorted({r["_n"] for r in rows})
    series = []
    for layout, col, mark, lab in (("packed", "PackA", "*", r"packed"),
                                   ("atomic", "PackD", "square*", r"atomic")):
        pts = []
        for n in sizes:
            v = max((r["_mdof"] for r in rows
                     if r["operation"] == op and r["ran_layout"] == layout
                     and r["_n"] == n and _bare(r)), default=None)
            if v:
                pts.append((n, v))
        if pts:
            series.append((col, mark, lab, pts))
    for store, col, mark, lab in (("f64", "PackE", "triangle*", r"BSR SpMV \texttt{f64}"),
                                  ("f32", "PackC", "diamond*", r"BSR SpMV \texttt{f32}")):
        pts = []
        for n in sizes:
            v = max((r["_mdof"] for r in rows
                     if r["operation"] == "bsr_apply" and r["bsr_storage"] == store
                     and r["_n"] == n), default=None)
            if v:
                pts.append((n, v))
        if pts:
            series.append((col, mark, lab, pts))

    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{axis}[",
           r"  width=\columnwidth, height=0.55\columnwidth,",
           r"  xlabel={cube edge $n$}, ylabel={MDOF/s},",
           r"  xtick={%s}," % ",".join(str(n) for n in sizes),
           r"  ymin=0, legend pos=north east, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    for col, mark, lab, pts in series:
        out.append(r"\addplot[%s,mark=%s,mark size=1.6pt,thick] coordinates {%s};"
                   % (col, mark, " ".join("(%d,%.3f)" % p for p in pts)))
        out.append(r"\addlegendentry{%s}" % lab)
    out.append(r"\end{axis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


# The ladder, from bare element kernel to the operator a solver actually applies. Each rung adds
# ONE term, and both layouts pay for it, which is the whole reason the ladder is reported: a
# comparison made on the bare kernel overstates the margin a solver receives.
LADDER = [
    (r"element kernel", dict(ran_rc="off", ran_boundary="off", transient="0", pgrad_per_apply="0")),
    (r"${}+{}$ pressure--velocity coupling", dict(ran_rc="on", ran_boundary="off", transient="0", pgrad_per_apply="0")),
    (r"${}+{}$ boundary closure", dict(ran_rc="on", ran_boundary="on", transient="0", pgrad_per_apply="0")),
    (r"${}+{}$ transient term", dict(ran_rc="on", ran_boundary="on", transient="1", pgrad_per_apply="0")),
]


def ladder_ratios(rows, op="residual", n=128):
    """The first and last rungs of the completeness ladder, which the prose quotes."""
    at_n = [r for r in rows if r["_n"] == n and r["operation"] == op]
    got = []
    for _label, sel in LADDER:
        p = best(at_n, ran_layout="packed", **sel)
        a = best(at_n, ran_layout="atomic", **sel)
        if p is not None and a is not None:
            got.append(p / a)
    return (got[0], got[-1]) if got else (None, None)


def table_ladder(rows, op="residual", n=128):
    at_n = [r for r in rows if r["_n"] == n and r["operation"] == op]
    out = [PREAMBLE, r"\begin{tabular}{lrrr}", r"\toprule",
           r"terms carried & packed & atomic & ratio \\",
           r"& \multicolumn{2}{c}{MDOF/s} & \\",
           r"\midrule"]
    any_row = False
    for label, sel in LADDER:
        p = best(at_n, ran_layout="packed", **sel)
        a = best(at_n, ran_layout="atomic", **sel)
        if p is None or a is None:
            continue
        any_row = True
        out.append(r"%s & %.0f & %.0f & $%.2f\times$ \\" % (label, p, a, p / a))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n" if any_row else None


def macros_throughput(rows, host, n=128, provisional=False):
    """Provenance and the headline figures, as macros.

    \\campProvisional is the safeguard that matters. A campaign CSV whose filename does not
    carry the job id that produced it did not come from a run this paper commissioned -- it is
    a file copied in to develop the plotting against -- and the caption then says so in the
    figure itself, rather than leaving the reader, or the author six weeks later, to check.
    Numbers from such a file validate the pipeline; they are never the paper's.
    """
    out = [PREAMBLE]
    out.append(r"\newcommand{\campProvisional}{%d}" % (1 if provisional else 0))
    out.append(r"\newcommand{\campHost}{%s}" % host)
    out.append(r"\newcommand{\campN}{%d}" % n)
    at_n = [r for r in rows if r["_n"] == n]
    dofs = max((r["_dofs"] for r in at_n), default=0)
    out.append(r"\newcommand{\campDofs}{%d}" % dofs)
    # The share of the exact-Rhie--Chow Jacobian matvec spent reconstructing the DIRECTION's
    # nodal pressure gradient. This is the second pass of a two-pass operator and the driver
    # times it separately precisely so it cannot be attributed to the element kernel.
    qg = [r for r in at_n if r["operation"] == "jac_action" and r.get("exact_rc") == "1"
          and r.get("ran_layout") == "packed" and r.get("frac_qgrad")]
    if qg:
        try:
            out.append(r"\newcommand{\campQgradPct}{%.0f}"
                       % (100.0 * max(float(r["frac_qgrad"]) for r in qg)))
        except ValueError:
            pass
    pairs = [("ResPacked", dict(operation="residual", ran_layout="packed")),
             ("ResAtomic", dict(operation="residual", ran_layout="atomic")),
             ("JacPacked", dict(operation="jac_action", ran_layout="packed")),
             ("JacAtomic", dict(operation="jac_action", ran_layout="atomic"))]
    for name, sel in pairs:
        v = max((r["_mdof"] for r in at_n
                 if all(r.get(k) == val for k, val in sel.items()) and _bare(r)), default=None)
        if v:
            out.append(r"\newcommand{\camp%s}{%.0f}" % (name, v))
    for name, store in (("SpmvF", "f64"), ("SpmvS", "f32")):
        v = max((r["_mdof"] for r in at_n
                 if r["operation"] == "bsr_apply" and r["bsr_storage"] == store), default=None)
        if v:
            out.append(r"\newcommand{\camp%s}{%.0f}" % (name, v))
    # The completeness ladder's first and last rungs, so the prose can state the range without
    # a number being typed next to a table that already carries it.
    lo, hi = ladder_ratios(rows, n=n)
    if lo and hi:
        out.append(r"\newcommand{\ladderBare}{$%.2f\times$}" % lo)
        out.append(r"\newcommand{\ladderFull}{$%.2f\times$}" % hi)
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F7 / T4: pack size, the index-type ceiling, and spatial ordering
# ---------------------------------------------------------------------------------------------

def parse_packsize(path):
    """Read jobs/packsize_paper.sbatch: the sweep rows and the ordering rows.

    Returns (sweep, order, meta) where sweep[n] is a list of dicts with the pack size, the pack
    count, packs per thread, mean nodes per pack and both throughputs.
    """
    sweep, order, meta, section = {}, [], {}, None
    for line in open(path):
        s = line.strip()
        if s.startswith("### host"):
            meta["host"] = s.split()[2]
            continue
        if s.startswith("### pack-size sweep"):
            section = "sweep"; continue
        if s.startswith("### spatial ordering"):
            section = "order"; continue
        if s.startswith("#") or not s:
            continue
        f = s.split()
        if section == "sweep" and len(f) == 8 and f[0].isdigit():
            try:
                sweep.setdefault(int(f[0]), []).append({
                    "pack": int(f[1]), "packs": int(f[3]), "ppt": float(f[4]),
                    "mean": int(f[5]), "res": float(f[6]), "jac": float(f[7])})
            except ValueError:
                pass
        elif section == "order" and len(f) == 6 and f[0].isdigit():
            try:
                order.append({"n": int(f[0]), "pack": int(f[1]), "order": f[2],
                              "mean": int(f[3]), "res": float(f[4]), "jac": float(f[5])})
            except ValueError:
                pass
    return sweep, order, meta


def fig_packsize(sweep, meta):
    """F7. Throughput against pack size, one series per problem size.

    The x axis is packs per thread rather than the pack size itself. The pack size is the knob,
    but the quantity that explains the collapse is how many units of parallel work it leaves
    for the cores, and plotting the knob hides that the two problem sizes fail at the same
    place on this axis while failing at different pack sizes.
    """
    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{semilogxaxis}[",
           r"  width=\columnwidth, height=0.55\columnwidth,",
           r"  xlabel={packs per thread}, ylabel={MDOF/s},",
           r"  log basis x=2, ymin=0,",
           r"  legend pos=south east, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    cols = {64: ("PackC", "triangle*"), 128: ("PackA", "*")}
    for n in sorted(sweep):
        col, mark = cols.get(n, ("PackE", "square*"))
        pts = sorted((r["ppt"], r["jac"]) for r in sweep[n])
        out.append(r"\addplot[%s,mark=%s,mark size=1.6pt,thick] coordinates {%s};"
                   % (col, mark, " ".join("(%.2f,%.3f)" % p for p in pts)))
        out.append(r"\addlegendentry{$n=%d$}" % n)
    # One pack per thread: below this line a core can be left with nothing at all.
    out.append(r"\draw[black!50,dashed] (axis cs:1,0) -- (axis cs:1,\pgfkeysvalueof{/pgfplots/ymax});")
    out.append(r"\node[black!55,font=\scriptsize,anchor=south west,rotate=90] "
               r"at (axis cs:1,0) {\ one pack per thread};")
    out.append(r"\end{semilogxaxis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def table_ordering(order):
    """T4. Space-filling against lexicographic element order at one pack size."""
    if not order:
        return None
    out = [PREAMBLE, r"\begin{tabular}{rlrrr}", r"\toprule",
           r"$n$ & element order & nodes/pack & residual & Jacobian \\",
           r"& & & \multicolumn{2}{c}{MDOF/s} \\", r"\midrule"]
    for r in order:
        name = "space-filling" if r["order"] == "sfc" else "lexicographic"
        out.append(r"%d & %s & %d & %.0f & %.0f \\"
                   % (r["n"], name, r["mean"], r["res"], r["jac"]))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


# The packer's target, mirrored from cvfem_hex8_pack_common.hpp so the paper quotes the constant
# the code uses rather than a number typed beside it.
CVFEM_PACKS_PER_THREAD = 28


def macros_packsize(sweep, order, meta):
    out = [PREAMBLE]
    out.append(r"\newcommand{\packHost}{%s}" % meta.get("host", "?"))
    out.append(r"\newcommand{\packsPerThread}{%d}" % CVFEM_PACKS_PER_THREAD)
    for n, rows in sweep.items():
        tag = "Small" if n == min(sweep) else "Large"
        best = max(rows, key=lambda r: r["jac"])
        ceil = max(rows, key=lambda r: r["pack"])
        out.append(r"\newcommand{\pack%sN}{%d}" % (tag, n))
        out.append(r"\newcommand{\pack%sBest}{%d}" % (tag, best["pack"]))
        out.append(r"\newcommand{\pack%sBestJac}{%.0f}" % (tag, best["jac"]))
        out.append(r"\newcommand{\pack%sCeil}{%d}" % (tag, ceil["pack"]))
        out.append(r"\newcommand{\pack%sCeilJac}{%.0f}" % (tag, ceil["jac"]))
        out.append(r"\newcommand{\pack%sCeilPacks}{%d}" % (tag, ceil["packs"]))
        out.append(r"\newcommand{\pack%sCeilPpt}{%.1f}" % (tag, ceil["ppt"]))
        out.append(r"\newcommand{\pack%sCeilLoss}{%.1f}" % (tag, best["jac"] / ceil["jac"]))
    for r in order:
        if r["n"] == max(x["n"] for x in order):
            tag = "Sfc" if r["order"] == "sfc" else "Lex"
            out.append(r"\newcommand{\ord%sMean}{%d}" % (tag, r["mean"]))
            out.append(r"\newcommand{\ord%sJac}{%.0f}" % (tag, r["jac"]))
            out.append(r"\newcommand{\ord%sRes}{%.0f}" % (tag, r["res"]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F8: roofline
# ---------------------------------------------------------------------------------------------

# Compulsory traffic per degree of freedom for one matrix-free apply, in bytes.
#
# MODELLED, and used only where a measurement is unavailable; roofline_points prefers measured
# DRAM traffic when it is given some. An earlier version of this model was wrong in a way that
# mattered, and the correction moved the residual from the compute-bound to the memory-bound side
# of the ridge, so the itemisation below is deliberately explicit about what the kernel reads.
#
# Per element, once per apply:
#   * the cached affine geometry -- nine adjugate components and the determinant, `scalar_t`,
#     which is what gather_hex8_adj_soa reads. TEN DOUBLES PER ELEMENT, about 19.5 B/dof on a
#     hexahedral mesh, and the largest single term. The earlier model omitted it entirely and
#     counted nodal coordinates instead, which the bare affine kernel never touches: coordinates
#     are staged only when Rhie-Chow or the boundary closure is on.
#   * the connectivity, whose width is the layout's -- `pack_idx_t` (2 B) packed against the
#     global `idx_t` (4 B) flat. The earlier model applied the packed width to both layouts, so
#     the two points were drawn at identical intensity BY CONSTRUCTION and the paper then
#     reasoned from their being identical.
# Per node, once per apply:
#   * the input field read and the result written, N_FIELDS each.
#
# Still not counted: re-reads of a node's input by elements in other packs, and spill. Both raise
# traffic and lower intensity, so this remains a lower bound on traffic and an upper bound on
# intensity -- which is why the measured figures are preferred where they exist.
GEOM_SCALARS_PER_ELEM = 10      # 9 adjugate components + determinant
SCALAR_BYTES = 8
FIELDS_PER_NODE = 4


def compulsory_bytes_per_dof(nelems, nnodes, layout):
    idx_bytes = PACK_IDX_BYTES if layout in ("packed", "colored", "store") else GLOBAL_IDX_BYTES
    geom = GEOM_SCALARS_PER_ELEM * SCALAR_BYTES * nelems
    conn = NODES_PER_ELEM * idx_bytes * nelems
    vec = 2 * FIELDS_PER_NODE * SCALAR_BYTES * nnodes
    return (geom + conn + vec) / float(FIELDS_PER_NODE * nnodes)


def parse_dram(path):
    """Measured DRAM bytes per dof, from two SCF captures differenced across repeat count.

    The counters cover a whole process, so a single capture includes mesh setup, pack
    construction and warmup. Differencing two runs that differ ONLY in the number of timed
    applies cancels all of it exactly, which is why the file carries a pair of repeat counts
    rather than one. Format, one row per configuration:

        operation layout repeat_lo repeat_hi bytes_lo bytes_hi dofs
    """
    out = {}
    for line in open(path):
        f = line.split()
        if len(f) != 7 or f[0].startswith("#"):
            continue
        try:
            op, lay = f[0], f[1]
            r_lo, r_hi = int(f[2]), int(f[3])
            b_lo, b_hi = float(f[4]), float(f[5])
            dofs = int(f[6])
        except ValueError:
            continue
        if r_hi <= r_lo or dofs <= 0:
            continue
        out[(op, lay)] = (b_hi - b_lo) / float(r_hi - r_lo) / dofs
    return out


def roofline_points(rows, n=128, measured_bytes=None):
    """(label, intensity FLOP/byte, achieved GFLOP/s, measured?) for the representations compared.

    ``measured_bytes`` maps (operation, layout) to DRAM bytes per dof, from the Grace SCF
    counters differenced across two repeat counts so that setup and warmup cancel. Where a pair
    is present it is used; where it is absent the model above is, and the flag in the returned
    tuple records which, so the figure can distinguish them rather than implying one provenance.
    """
    measured_bytes = measured_bytes or {}
    at_n = [r for r in rows if r["_n"] == n]
    pts = []
    for op, lay, label in (("residual", "packed", "residual, packed"),
                           ("residual", "atomic", "residual, atomic"),
                           ("jac_action", "packed", "Jacobian, packed"),
                           ("jac_action", "atomic", "Jacobian, atomic")):
        cand = [r for r in at_n if r["operation"] == op and r["ran_layout"] == lay and _bare(r)]
        if not cand:
            continue
        b = max(cand, key=lambda r: r["_mdof"])
        try:
            gflops = float(b["GFLOP_s_model"])
            nelems, nnodes = int(b["elements"]), int(b["nodes"])
        except (KeyError, ValueError):
            continue
        if b["_mdof"] <= 0:
            continue
        flop_per_dof = gflops * 1e9 / (b["_mdof"] * 1e6)
        meas = measured_bytes.get((op, lay))
        byts = meas if meas else compulsory_bytes_per_dof(nelems, nnodes, lay)
        pts.append((label, flop_per_dof / byts, gflops, meas is not None))
    for store, label in (("f64", r"SpMV \texttt{f64}"), ("f32", r"SpMV \texttt{f32}")):
        cand = [r for r in at_n if r["operation"] == "bsr_apply" and r["bsr_storage"] == store]
        if not cand:
            continue
        b = max(cand, key=lambda r: r["_mdof"])
        try:
            blocks, dofs = int(b["bsr_nnz"]), b["_dofs"]
            vals = float(b["bsr_values_MiB"]) * 1024 * 1024
        except (KeyError, ValueError):
            continue
        flop = 2.0 * blocks * BLOCK * BLOCK
        meas = measured_bytes.get(("bsr_apply", store))
        if meas:
            byts_per_dof = meas
        else:
            byts_per_dof = (vals + blocks * GLOBAL_IDX_BYTES
                            + dofs * 2 * FIELDS_PER_NODE * SCALAR_BYTES / FIELDS_PER_NODE) / dofs
        pts.append((label, (flop / dofs) / byts_per_dof, b["_mdof"] * 1e6 * (flop / dofs) * 1e-9,
                    meas is not None))
    return pts


# Vendor figures for one Grace die, against which the measured roofs are reported. Quoted rather
# than derived, and cited in the paper where they appear.
SPEC_BW_GBS = 500.0
SPEC_PEAK_GFLOPS = 3550.0


def _roof(ai_lo, ai_hi, bw, peak):
    """The two segments of a roof: bandwidth-bound below the ridge, compute-bound above."""
    ridge = peak / bw
    return [(ai_lo, ai_lo * bw), (ridge, peak), (ai_hi, peak)]


def roofline_ho_points(rows, dram_ho, n=128):
    """The higher-order convective arms, on the same axes as the first-order operators.

    Traffic is measured once per layout and shared by the four schemes. They read the same
    arrays -- the mesh, the fields and the hoisted nodal velocity gradient -- and differ only
    in arithmetic applied to values already in registers, so a limiter moves a point to the
    right along the roofline and never changes what it moves. That is the claim the figure
    makes, and it is why one capture per layout is enough to place four points.

    Returns {layout: [(scheme label, intensity, GFLOP/s), ...]} ordered by intensity, which is
    also the order of increasing limiter arithmetic.
    """
    out = {}
    for lay, key in (("packed", ("residual-ho", "packed")), ("atomic", ("residual-ho", "atomic"))):
        byts = (dram_ho or {}).get(key)
        if not byts:
            continue
        pts = []
        for arm in ("ho_unlimited", "ho_clip", "ho_darwish_moukalled", "ho_venkatakrishnan"):
            r = next((r for r in rows if r.arm == arm and r.layout == lay), None)
            if r is None or not r.flops_elem or not r.elems:
                continue
            flop_per_dof = r.flops_elem * r.elems / float(r.dofs)
            pts.append((HO_NAME[arm], flop_per_dof / byts, r.mdof * 1e6 * flop_per_dof * 1e-9))
        if len(pts) >= 2:
            out[lay] = sorted(pts, key=lambda p: p[1])
    return out


def fig_roofline(pts, bandwidth_gbs, peak_gflops, ho=None,
                 spec_bw=SPEC_BW_GBS, spec_peak=SPEC_PEAK_GFLOPS):
    """F8. Measured and vendor roofs together, with the kernels placed on measured traffic.

    Both roofs are drawn because they answer different questions. The measured pair bounds what
    this node delivered to a benchmark under the same conditions as the kernels, and is the
    correct reference for an efficiency. The vendor pair bounds what the hardware is specified to
    do, and the gap between the two is itself information -- it is where a library GEMM and a
    triad stop short of nominal, which no kernel measured here can recover.

    The higher-order arms are drawn as a path per layout rather than as four more legend
    entries: what they show is a trajectory, one operator gaining arithmetic at fixed traffic,
    and a path says that where four scattered markers would not.
    """
    xmin, xmax = 0.15, 64.0
    # Head room above the vendor plateau, because its label goes above its own line and a
    # tighter ceiling clips the label against the axis frame rather than crossing the roof.
    ymin, ymax = 20.0, max(peak_gflops, spec_peak) * 2.6
    # Axis geometry, so an annotation can be laid ALONG a roof instead of across it. The sloped
    # segment has unit slope in decades, but the axis box is not square in decades per unit
    # length, so its drawn angle is not 45 degrees and a label rotated to 45 crosses the line it
    # is labelling. This is that angle.
    h_over_w = 0.50
    ang = math.degrees(math.atan2(h_over_w / math.log10(ymax / ymin),
                                  1.0 / math.log10(xmax / xmin)))
    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{loglogaxis}[",
           r"  width=\columnwidth, height=%.2f\columnwidth," % h_over_w,
           r"  xlabel={operational intensity [FLOP/byte]}, ylabel={GFLOP/s},",
           r"  xmin=%.2f, xmax=%.0f, ymin=%.0f, ymax=%.0f," % (xmin, xmax, ymin, ymax),
           # Below the axis, not inside it: with the higher-order paths the key needs eight
           # entries, and any corner large enough to hold them also holds a roof or a point.
           r"  legend cell align=left, legend columns=3,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt,",
           r"    at={(0.5,-0.34)}, anchor=north, column sep=6pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]

    def roof_plot(bw, peak, style, label, above):
        coords = " ".join("(%.3f,%.1f)" % c for c in _roof(xmin, xmax, bw, peak))
        out.append(r"\addplot[%s,no marks,forget plot] coordinates {%s};" % (style, coords))
        # Set against the right edge and clear of its own line: above it for the upper roof,
        # below it for the lower one, so neither label crosses a roof and neither is clipped.
        out.append(r"\node[black!55,font=\tiny,anchor=%s] at (axis cs:%.2f,%.1f) {%s};"
                   % ("south east" if above else "north east",
                      xmax * 0.97, peak * (1.13 if above else 0.88), label))

    # Vendor first, so the measured roof is drawn over it.
    roof_plot(spec_bw, spec_peak, "black!45,thick,densely dashed",
              r"spec %.2f TFLOP/s" % (spec_peak / 1000.0), True)
    roof_plot(bandwidth_gbs, peak_gflops, "black,thick",
              r"measured %.2f TFLOP/s" % (peak_gflops / 1000.0), False)
    # The bandwidth labels run ALONG their own sloped segment, at the drawn angle, and at two
    # well-separated intensities: the roofs are only a few per cent apart there, so two labels
    # at one place would sit on top of each other whatever the offset.
    out.append(r"\node[black!55,font=\tiny,anchor=south,rotate=%.1f] "
               r"at (axis cs:%.2f,%.1f) {spec %.0f GB/s};"
               % (ang, 0.42, 0.42 * spec_bw * 1.14, spec_bw))
    out.append(r"\node[black!70,font=\tiny,anchor=north,rotate=%.1f] "
               r"at (axis cs:%.2f,%.1f) {meas.\ %.0f GB/s};"
               % (ang, 2.2, 2.2 * bandwidth_gbs * 0.88, bandwidth_gbs))

    marks = ["*", "square*", "triangle*", "diamond*", "pentagon*", "otimes*"]
    cols = ["PackA", "PackD", "PackC", "PackE", "PackB", "PackF"]
    for i, (label, ai, gf, meas) in enumerate(pts):
        # A hollow marker says the intensity rests on the compulsory-traffic model rather than
        # on a DRAM capture. The distinction is the figure's own provenance and belongs in it.
        fill = "" if meas else ",fill=white"
        out.append(r"\addplot[%s,mark=%s,mark size=2.1pt,only marks,mark options={%s%s}] "
                   r"coordinates {(%.3f,%.1f)};"
                   % (cols[i % len(cols)], marks[i % len(marks)],
                      "draw=" + cols[i % len(cols)], fill or ",fill=" + cols[i % len(cols)],
                      ai, gf))
        out.append(r"\addlegendentry{%s}" % label)

    # COLOUR is the layout, SHAPE is the scheme. The four schemes used to share one marker and be
    # named by two floating labels on the packed path, which left the atomic path's schemes
    # anonymous and the middle two unnamed on both. Now each scheme carries its own shape and its
    # own legend entry, drawn in black there because the shape is what the entry is about.
    #
    # The shapes are deliberately none of the six the first-order points use: the unlimited
    # higher-order point sits beside its own layout's residual point, and sharing a shape with it
    # there would be exactly where the confusion lands. Filled, because a hollow marker already
    # means something else in this figure -- modelled rather than measured traffic.
    #
    # The schemes are drawn as POINTS, not joined. A line between them would assert a path
    # through intensities that nothing traverses: they are four separate operators measured
    # independently, and the ordering among them is a fact about their arithmetic, which the
    # legend states, not a trajectory.
    HO_MARKS = ["oplus*", "halfsquare*", "halfcircle*", "star"]
    ho_seen = []
    for lay, col in (("packed", "PackA"), ("atomic", "PackD")):
        path = (ho or {}).get(lay)
        if not path:
            continue
        for i, (name, ai, gf) in enumerate(path):
            mk = HO_MARKS[i % len(HO_MARKS)]
            out.append(r"\addplot[%s,mark=%s,mark size=2.0pt,only marks,forget plot,"
                       r"mark options={draw=%s,fill=%s}] coordinates {(%.3f,%.1f)};"
                       % (col, mk, col, col, ai, gf))
            if name not in ho_seen:
                ho_seen.append(name)
    # One legend entry per SCHEME, once, after the plots so the order reads with the path.
    for i, name in enumerate(ho_seen):
        out.append(r"\addlegendimage{black,mark=%s,mark size=2.0pt,only marks,"
                   r"mark options={draw=black,fill=black}}" % HO_MARKS[i % len(HO_MARKS)])
        out.append(r"\addlegendentry{%s}" % name)

    out.append(r"\end{loglogaxis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def macros_roofline_ho(ho, measured_bytes):
    """What the prose quotes about the higher-order arms' place on the roofline.

    The traffic ratio is the number that matters and it is not the expected one: the correction
    reads a nine-component nodal gradient the first-order sweep never touches, so it buys its
    extra arithmetic at roughly twice the DRAM traffic rather than at none.
    """
    out = []
    for lay, tag in (("packed", "Packed"), ("atomic", "Atomic")):
        b = (measured_bytes or {}).get(("residual-ho", lay))
        fo = (measured_bytes or {}).get(("residual", lay))
        if b:
            out.append(r"\newcommand{\hoBytes%s}{%.0f}" % (tag, b))
        if fo:
            out.append(r"\newcommand{\foBytes%s}{%.0f}" % (tag, fo))
        if b and fo:
            out.append(r"\newcommand{\hoBytesRatio%s}{%.2f}" % (tag, b / fo))
        path = (ho or {}).get(lay)
        if path:
            out.append(r"\newcommand{\hoAi%sLo}{%.1f}" % (tag, path[0][1]))
            out.append(r"\newcommand{\hoAi%sHi}{%.1f}" % (tag, path[-1][1]))
    return "\n".join(out) + "\n" if out else ""


def _macro_name(label):
    """A LaTeX-safe, UNIQUE macro suffix for a roofline label.

    LaTeX command names may not contain digits, so the obvious "strip non-alpha" rule maps
    "SpMV f64" and "SpMV f32" onto the same name and emits \\newcommand twice for it, which is
    an error. Digits are spelled out instead, which keeps the names distinct and readable.
    """
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    out = []
    for c in label.replace("\\texttt", " ").title():
        if c.isalpha():
            out.append(c)
        elif c in digits:
            out.append(digits[c])
    return "".join(out)


def parse_peak(path):
    """Sustained fp64 GFLOP/s from jobs/peak_fp64.sbatch."""
    for line in open(path):
        if line.strip().startswith("PEAK_FP64_GFLOPS:"):
            try:
                return float(line.split(":")[1])
            except (IndexError, ValueError):
                return None
    return None


# ---------------------------------------------------------------------------------------------
# The higher-order convective flux
# ---------------------------------------------------------------------------------------------

# The four convective schemes, and for each the three arms that let one ratio isolate one
# variable: the packed GENERATED kernel, the packed hand-written kernel, and the atomic
# hand-written kernel. generated/hand is a kernel ratio at fixed layout; hand/atomic is a layout
# ratio at fixed kernel. A single "packed" column mixing the two would state neither.
HO_NAME = {
    "first_order": "first-order upwind",
    "ho_unlimited": "deferred correction, unlimited",
    "ho_clip": r"${}+{}$ bounded-face clip",
    "ho_venkatakrishnan": r"${}+{}$ Venkatakrishnan",
    "ho_darwish_moukalled": r"${}+{}$ Darwish--Moukalled",
}

# arm -> (scheme, role). The packed row of each scheme's base arm is the generated kernel; the
# _scalar rows are the hand-written reference. Arms absent here are read but not tabulated:
# ho_unlim_simd is the hand-written vectorised attempt that lost, and the Rhie-Chow pair is
# quoted in the prose rather than given a column, since no other scheme has an RC row to sit
# beside it.
HO_SCALAR_ARM = {
    "ho_unlim_scalar": "ho_unlimited",
    "ho_clip_scalar": "ho_clip",
    "ho_venk_scalar": "ho_venkatakrishnan",
    "ho_dm_scalar": "ho_darwish_moukalled",
}
HO_EXTRA = ("ho_unlim_simd", "ho_unlim_rc", "ho_unlim_rc_scalar")


ConvHo = collections.namedtuple("ConvHo", "arm layout mdof dofs elems flops_elem checksum")


def parse_convho(path):
    """Read jobs/conv_ho_bench.sbatch's summary table.

    Two widths are accepted. The job printed five columns before it carried a work model and
    prints seven now, the two new ones being the element count and the modelled FLOPs per
    element -- which is what puts these arms on the roofline. An archived five-column file
    still parses, with those two fields empty, so a regeneration against older data produces
    the table and simply omits the points that need them.
    """
    known = set(HO_NAME) | set(HO_SCALAR_ARM) | set(HO_EXTRA)
    out = []
    for line in open(path):
        f = line.split()
        if not f or f[0] not in known or len(f) not in (5, 7):
            continue
        if f[1] not in ("atomic", "packed") or f[2] == "-":
            continue
        try:
            if len(f) == 5:
                out.append(ConvHo(f[0], f[1], float(f[2]), int(f[3]), None, None, f[4]))
            else:
                elems = int(f[4]) if f[4] != "-" else None
                fpe = float(f[5]) if f[5] != "-" else None
                out.append(ConvHo(f[0], f[1], float(f[2]), int(f[3]), elems, fpe, f[6]))
        except ValueError:
            continue
    return out


def _convho_index(rows):
    """{scheme: {"gen":x, "hand":x, "atomic":x}} plus the loose arms, by name."""
    by = {}
    loose = {}
    for arm, lay, mdof, _dofs, _e, _fp, _ck in rows:
        if arm in HO_SCALAR_ARM and lay == "packed":
            by.setdefault(HO_SCALAR_ARM[arm], {})["hand"] = mdof
        elif arm in HO_NAME:
            by.setdefault(arm, {})["gen" if lay == "packed" else "atomic"] = mdof
        elif arm in HO_EXTRA and lay == "packed":
            loose[arm] = mdof
    return by, loose


def table_convho(rows):
    """The convective schemes, packed against atomic, at the saturating size.

    Same shape as the completeness ladder: one row per variant, the two layouts side by side, and
    the ratio between them. First-order upwind is a row like the others rather than a separate
    presentation -- it is the scheme the higher-order arms correct, and the question asked of all
    five is the one the paper asks everywhere, which is what the layout is worth.

    Each column is that layout's own shipped kernel, which is the configuration a solver gets.

    The checksum is not printed but is still read: a higher-order row whose checksum equals the
    first-order one did not apply the correction, and its timing is first order measured twice.
    """
    if not rows:
        return None
    by, _loose = _convho_index(rows)
    out = [PREAMBLE, r"\small", r"\begin{tabular}{@{}lrrr@{}}", r"\toprule",
           r"convective scheme & packed & atomic & ratio \\",
           r"& \multicolumn{2}{c}{MDOF/s} & \\", r"\midrule"]
    for arm in ("first_order", "ho_unlimited", "ho_clip", "ho_venkatakrishnan",
                "ho_darwish_moukalled"):
        d = by.get(arm)
        if not d:
            continue
        pk, at = d.get("gen"), d.get("atomic")
        ratio = (r"$%.2f\times$" % (pk / at)) if (pk and at) else "---"
        out.append(r"%s & %s & %s & %s \\" % (HO_NAME[arm], _fmt0(pk), _fmt0(at), ratio))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def spmv_reference(rows, n=128):
    """The assembled SpMV at one size, for the reference lines on the throughput bar chart.

    Same source as F5, the campaign's bsr_apply rows, and taken at the size the convective arms
    were measured at, so the line and the bars describe the same problem rather than two.
    """
    out = {}
    for store in ("f64", "f32"):
        v = max((r["_mdof"] for r in rows
                 if r["operation"] == "bsr_apply" and r["bsr_storage"] == store
                 and r["_n"] == n), default=None)
        if v:
            out[store] = v
    return out


def fig_convho(rows, spmv=None):
    """The same five variants as a figure, so the trend across schemes reads at a glance.

    A symbolic x axis rather than a size sweep: the higher-order arms are measured at the
    saturating size only, and plotting them against sizes they were not swept over would invent
    data. The two SpMV rates are drawn across it as reference lines, in the colours F5 gives
    them, because what the reader wants from a rate is what it beats.
    """
    if not rows:
        return None
    by, _loose = _convho_index(rows)
    order = [a for a in ("first_order", "ho_unlimited", "ho_clip", "ho_venkatakrishnan",
                         "ho_darwish_moukalled") if a in by]
    if not order:
        return None
    short = {"first_order": "upwind", "ho_unlimited": "unlimited", "ho_clip": "clip",
             "ho_venkatakrishnan": "Venkat.", "ho_darwish_moukalled": "Darwish--M."}
    coords = ",".join(short[a] for a in order)

    def series(key):
        return " ".join("(%s,%.1f)" % (short[a], by[a][key])
                        for a in order if by[a].get(key))

    return PREAMBLE + "\n".join([
        r"\begin{tikzpicture}",
        r"\begin{axis}[width=\columnwidth, height=0.44\columnwidth,",
        r"  ybar, bar width=7pt, ymin=0, ylabel={MDOF/s},",
        # ONE swatch per bar entry. The ybar default draws a pair of bars in the legend, which
        # says nothing here -- each series is one bar per group, not two -- and doubles the width
        # of a legend that also has to hold two dashed reference lines. The SpMV entries below
        # give their own legend image code and are unaffected by this.
        r"  legend image code/.code={\draw[#1] (0cm,-0.09cm) rectangle (0.22cm,0.09cm);},",
        r"  symbolic x coords={%s}, xtick=data," % coords,
        r"  x tick label style={font=\tiny}, enlarge x limits=0.13,",
        r"  legend pos=north east, legend cell align=left,",
        r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
        r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},",
        r"  ymajorgrids, major grid style={black!12}]",
        r"\addplot[draw=PackA, fill=PackA] coordinates {%s};" % series("gen"),
        r"\addlegendentry{packed}",
        r"\addplot[draw=PackD, fill=PackD] coordinates {%s};" % series("atomic"),
        r"\addlegendentry{atomic}",
    ] + _convho_spmv_lines(spmv, short[order[0]]) + [
        r"\end{axis}",
        r"\end{tikzpicture}",
    ]) + "\n"


def _convho_spmv_lines(spmv, xref):
    """Horizontal rules at the SpMV rates, with their own legend entries.

    Drawn rather than plotted: the x axis is symbolic, so a rule has to take its x from the axis
    edges and only its y from the data, which is what the -| operator does. The legend image is
    added by hand for the same reason."""
    out = []
    for store, col, lab in (("f64", "PackE", r"BSR SpMV \texttt{f64}"),
                            ("f32", "PackC", r"BSR SpMV \texttt{f32}")):
        v = (spmv or {}).get(store)
        if not v:
            continue
        out.append(r"\draw[%s,dashed,thick] ({axis cs:%s,%.1f} -| {rel axis cs:0,0}) -- "
                   r"({axis cs:%s,%.1f} -| {rel axis cs:1,0});" % (col, xref, v, xref, v))
        # An explicit legend image: the default one for a line-only entry draws a marker box
        # here, which reads as a third kind of thing rather than as the rule it stands for.
        out.append(r"\addlegendimage{legend image code/.code={\draw[%s,dashed,thick] "
                   r"(0cm,0cm) -- (0.45cm,0cm);}}" % col)
        out.append(r"\addlegendentry{%s}" % lab)
    return out


def _fmt0(v):
    return "---" if not v else ("%.0f" % v)


def macros_convho(rows):
    """The figures the prose quotes: each variant's two layouts and the ratio between them."""
    by, _loose = _convho_index(rows)
    out = [PREAMBLE]
    for arm, tag in (("first_order", "First"), ("ho_unlimited", "Unlim"), ("ho_clip", "Clip"),
                     ("ho_venkatakrishnan", "Venk"), ("ho_darwish_moukalled", "Dm")):
        d = by.get(arm, {})
        pk, at = d.get("gen"), d.get("atomic")
        if pk:
            out.append(r"\newcommand{\ho%sPacked}{%.0f}" % (tag, pk))
        if at:
            out.append(r"\newcommand{\ho%sAtomic}{%.0f}" % (tag, at))
        if pk and at:
            out.append(r"\newcommand{\ho%sLayoutRatio}{%.2f}" % (tag, pk / at))
    # What the correction costs against first order WITHIN one layout, so the format is not in the
    # comparison and what is left is the scheme's own arithmetic.
    for lay, suffix in (("gen", "Packed"), ("atomic", "Atomic")):
        fo = by.get("first_order", {}).get(lay)
        for arm, tag in (("ho_unlimited", "Unlim"), ("ho_clip", "Clip"),
                         ("ho_venkatakrishnan", "Venk"), ("ho_darwish_moukalled", "Dm")):
            v = by.get(arm, {}).get(lay)
            if fo and v:
                out.append(r"\newcommand{\ho%sCost%s}{%.2f}" % (tag, suffix, fo / v))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# The nodal gradient reconstruction, timed on its own
# ---------------------------------------------------------------------------------------------

def parse_ngrad(path):
    """Read jobs/nodal_grad_bench.sbatch: {(nf, layout): (MDOF/s, MCOMP/s)}."""
    out = {}
    for line in open(path):
        f = line.split()
        if len(f) == 5 and f[1] in ("packed", "atomic") and f[2] != "-":
            try:
                out[(int(f[0]), f[1])] = (float(f[2]), float(f[3]))
            except ValueError:
                continue
    return out


def macros_ngrad(rows):
    """The reconstruction's rates and, the point of them, its layout ratios.

    Reported in MDOF/s like every other operator here, so the rows are comparable across the
    paper, and in node-components per second beside it, which is the quantity the kernel actually
    produces and the one that scales with the field count.
    """
    out = [PREAMBLE]
    name = {1: "Pgrad", 3: "Ugrad"}
    for nf, tag in name.items():
        for lay in ("packed", "atomic"):
            if (nf, lay) in rows:
                out.append(r"\newcommand{\ng%s%s}{%.0f}" % (tag, lay.capitalize(), rows[(nf, lay)][0]))
                out.append(r"\newcommand{\ng%s%sComp}{%.0f}"
                           % (tag, lay.capitalize(), rows[(nf, lay)][1]))
        if (nf, "packed") in rows and (nf, "atomic") in rows:
            out.append(r"\newcommand{\ng%sRatio}{%.1f}"
                       % (tag, rows[(nf, "packed")][0] / rows[(nf, "atomic")][0]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# The exact higher-order Jacobian action, against the lagged one
# ---------------------------------------------------------------------------------------------

def parse_hoexact(path):
    """Read jobs/ho_exact_jac.sbatch: {arm: MDOF/s}.

    The verification lines above the table are parsed too and returned separately: a throughput
    row for an operator whose finite-difference check did not run is not a result, and the macro
    writer refuses to emit one without it.
    """
    rates, checks, frac = {}, {}, {}
    for line in open(path):
        f = line.split()
        if len(f) in (3, 4) and f[0].startswith("jac_") and f[1] != "-":
            try:
                rates[f[0]] = float(f[1])
            except ValueError:
                pass
            # The reconstruction's share of the matvec it sits in, recorded by the driver from
            # the same pass that gave the rate. Older tables have three columns and no share.
            if len(f) == 4 and f[3] != "-":
                try:
                    frac[f[0]] = float(f[3])
                except ValueError:
                    pass
        elif len(f) >= 4 and f[0] == "limiter":
            try:
                checks[int(f[1])] = float(f[3])
            except (ValueError, IndexError):
                pass
    return rates, checks, frac


def macros_hoexact(rates, checks, frac=None):
    """What the prose quotes about the exact action: its cost, and what it is checked to."""
    out = [PREAMBLE]
    def put(name, key):
        if key in rates:
            out.append(r"\newcommand{\hox%s}{%.0f}" % (name, rates[key]))
    put("LaggedPacked", "jac_ho_lagged_packed")
    put("ExactPacked", "jac_ho_exact_packed")
    put("LaggedAtomic", "jac_ho_lagged_atomic")
    put("ExactAtomic", "jac_ho_exact_atomic")
    for name, a, b in (("CostPacked", "jac_ho_lagged_packed", "jac_ho_exact_packed"),
                       ("CostAtomic", "jac_ho_lagged_atomic", "jac_ho_exact_atomic")):
        if a in rates and b in rates:
            out.append(r"\newcommand{\hox%s}{%.2f}" % (name, rates[a] / rates[b]))
    # The layout ratio on each form. That it collapses is the result, so it is generated rather
    # than left to a reader to divide two numbers in a table.
    for name, lay in (("LayoutLagged", "lagged"), ("LayoutExact", "exact")):
        p, a = "jac_ho_%s_packed" % lay, "jac_ho_%s_atomic" % lay
        if p in rates and a in rates:
            out.append(r"\newcommand{\hox%s}{%.2f}" % (name, rates[p] / rates[a]))
    # The unlimited arm, for the sentence about what the limiter itself costs. It only became a
    # separate number once the limiter left the vector body: with a runtime select every arm paid
    # the same guard and the two read the same rate.
    if "jac_ho_exact_packed_unlim" in rates and "jac_ho_exact_packed" in rates:
        out.append(r"\newcommand{\hoxExactPackedUnlim}{%.0f}" % rates["jac_ho_exact_packed_unlim"])
        out.append(r"\newcommand{\hoxLimiterCost}{%.2f}"
                   % (rates["jac_ho_exact_packed_unlim"] / rates["jac_ho_exact_packed"]))
    # What share of the matvec the added reconstruction is, on each layout. The prose used to
    # carry these two as typed percentages; they move with the kernel, so they are generated.
    for name, key in (("FracPacked", "jac_ho_exact_packed"), ("FracAtomic", "jac_ho_exact_atomic")):
        if frac and key in frac:
            out.append(r"\newcommand{\hox%s}{%.0f}" % (name, 100.0 * frac[key]))
    if 0 in checks:
        out.append(r"\newcommand{\hoxFdUnlim}{%.0e}" % checks[0])
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# The like-for-like Jacobian comparison against the assembled matrix
# ---------------------------------------------------------------------------------------------

JF_NAME = {
    "jac_exact":  "Jacobian action, exact",
    "jac_lagged": "Jacobian action, lagged",
    "spmv_f64":   r"SpMV, lagged \texttt{f64}",
    "spmv_f32":   r"SpMV, lagged \texttt{f32}",
}


def parse_jacfair(path):
    out = []
    for line in open(path):
        f = line.split()
        if len(f) >= 4 and f[0] in JF_NAME and f[2] != "-":
            try:
                out.append((f[0], f[1], float(f[2])))
            except ValueError:
                continue
    return out


def table_jacfair(rows):
    """Matrix-free against the assembled matrix, with the operators made comparable.

    The exact row is what a Newton--Krylov solve should apply; the lagged row is the operator
    the assembled matrix can hold, and is the one to compare with the SpMV rows. Reporting only
    the exact row against the SpMV would understate the matrix-free side, because it would be
    doing strictly more work than the matrix encodes.
    """
    if not rows:
        return None
    by = {}
    for op, lay, v in rows:
        by.setdefault(op, {})[lay] = v
    out = [PREAMBLE, r"\small", r"\begin{tabular}{@{}lrrr@{}}", r"\toprule",
           r"operator & packed & atomic & vs.\ \texttt{f64} \\",
           r"& \multicolumn{2}{c}{MDOF/s} & \\", r"\midrule"]
    f64 = by.get("spmv_f64", {}).get("none")
    for op in ("jac_exact", "jac_lagged"):
        if op not in by:
            continue
        pk, at = by[op].get("packed"), by[op].get("atomic")
        rel = (r"$%.2f\times$" % (pk / f64)) if pk and f64 else "---"
        out.append(r"%s & %.0f & %.0f & %s \\" % (JF_NAME[op], pk or 0, at or 0, rel))
    out.append(r"\midrule")
    for op in ("spmv_f64", "spmv_f32"):
        v = by.get(op, {}).get("none")
        if v is None:
            continue
        rel = (r"$%.2f\times$" % (v / f64)) if f64 else "---"
        out.append(r"%s & \multicolumn{2}{c}{%.0f} & %s \\" % (JF_NAME[op], v, rel))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def macros_jacfair(rows):
    by = {}
    for op, lay, v in rows:
        by.setdefault(op, {})[lay] = v
    out = [PREAMBLE]
    ex = by.get("jac_exact", {}).get("packed")
    lg = by.get("jac_lagged", {}).get("packed")
    f64 = by.get("spmv_f64", {}).get("none")
    f32 = by.get("spmv_f32", {}).get("none")
    if ex and lg:
        out.append(r"\newcommand{\jfExactCost}{%.2f}" % (lg / ex))
    if lg and f64:
        out.append(r"\newcommand{\jfLaggedVsF}{%.2f}" % (lg / f64))
    if lg and f32:
        out.append(r"\newcommand{\jfLaggedVsS}{%.2f}" % (lg / f32))
    if ex and f64:
        # The ratio the UNFAIR comparison would have produced, quoted in the paper to show how
        # much the mismatch was worth rather than silently corrected.
        out.append(r"\newcommand{\jfExactVsF}{%.2f}" % (ex / f64))
    la = by.get("jac_lagged", {}).get("atomic")
    if la and f64:
        out.append(r"\newcommand{\jfLaggedAtomicVsF}{%.2f}" % (la / f64))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------

def build(out_dir, tab_dir):
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(tab_dir, exist_ok=True)
    written = []
    spmv_ref = {}
    convho_rows = []

    det = [f for f in sorted(os.listdir(DATA)) if f.startswith("det_layout_")] if os.path.isdir(DATA) else []
    if det:
        # The newest run wins; older ones stay on disk as provenance.
        rows, meta = parse_determinism(os.path.join(DATA, det[-1]))
        if rows:
            # No table: the finding is one sentence and the paper says it in prose. The macros
            # stay, because the prose quotes the counts and must not type them.
            with open(os.path.join(out_dir, "determinism_macros.tex"), "w") as fh:
                fh.write(macros_determinism(rows, meta))
            written += ["figures/determinism_macros.tex"]

    camp = [f for f in sorted(os.listdir(DATA)) if f.startswith("campaign_")] if os.path.isdir(DATA) else []
    if camp:
        path = os.path.join(DATA, camp[-1])
        # The mesh half of the footprint table is MEASURED, by the bench's --mesh-footprint
        # mode, which reports each array's own nbytes(). It replaced an arithmetic model that
        # had to guess the ghost and reduction-graph lengths and was about 20% out.
        fr = footprint_rows(path)
        try:
            camp_rows_fp, _h = read_campaign(path)
        except ValueError:
            camp_rows_fp = []
        mfp = [f for f in sorted(os.listdir(DATA)) if f.startswith("meshfoot_")]
        mesh = meshfoot_totals(parse_meshfoot(os.path.join(DATA, mfp[-1]))) if mfp else None
        t_fp = table_footprint(camp_rows_fp, mesh) if camp_rows_fp else None
        if t_fp:
            with open(os.path.join(tab_dir, "footprint.tex"), "w") as fh:
                fh.write(t_fp)
            written.append("tables/footprint.tex")
        if mfp:
            mm = macros_meshfoot(parse_meshfoot(os.path.join(DATA, mfp[-1])))
            if mm:
                with open(os.path.join(out_dir, "meshfoot_macros.tex"), "w") as fh:
                    fh.write(mm)
                written.append("figures/meshfoot_macros.tex")
        try:
            rows, host = read_campaign(path)
        except ValueError as exc:
            print("campaign not usable: %s" % exc)
            rows = []
        if rows:
            # A campaign file is the paper's own only if its name carries the job id that made
            # it, which jobs/camp_full.sbatch now stamps.
            prov = re.match(r"campaign_grace_\d+\.csv$", os.path.basename(path)) is None
            if prov:
                print("  NOTE: %s carries no job id -- figures marked provisional"
                      % os.path.basename(path))
            spmv_ref = spmv_reference(rows)
            with open(os.path.join(out_dir, "throughput_size.tex"), "w") as fh:
                fh.write(fig_throughput(rows, host))
            with open(os.path.join(out_dir, "campaign_macros.tex"), "w") as fh:
                fh.write(macros_throughput(rows, host, provisional=prov))
            written += ["figures/throughput_size.tex", "figures/campaign_macros.tex"]
            lad = table_ladder(rows)
            if lad:
                with open(os.path.join(tab_dir, "ladder.tex"), "w") as fh:
                    fh.write(lad)
                written.append("tables/ladder.tex")

    ts = [f for f in sorted(os.listdir(DATA)) if f.startswith("tscale_")] if os.path.isdir(DATA) else []
    if ts:
        series, meta = parse_scaling(os.path.join(DATA, ts[-1]))
        if series:
            with open(os.path.join(out_dir, "scaling_res.tex"), "w") as fh:
                fh.write(fig_scaling(series, meta, "res"))
            with open(os.path.join(out_dir, "scaling_macros.tex"), "w") as fh:
                fh.write(macros_scaling(series, meta))
            written += ["figures/scaling_res.tex", "figures/scaling_macros.tex"]

    st = [f for f in sorted(os.listdir(DATA)) if f.startswith("stream_")] if os.path.isdir(DATA) else []
    if st:
        rates = parse_stream(os.path.join(DATA, st[-1]))
        if rates:
            with open(os.path.join(out_dir, "stream_macros.tex"), "w") as fh:
                fh.write(macros_stream(rates))
            written.append("figures/stream_macros.tex")

    ps = [f for f in sorted(os.listdir(DATA)) if f.startswith("packsize_")] if os.path.isdir(DATA) else []
    if ps:
        sweep, order, meta = parse_packsize(os.path.join(DATA, ps[-1]))
        if sweep:
            with open(os.path.join(out_dir, "packsize.tex"), "w") as fh:
                fh.write(fig_packsize(sweep, meta))
            with open(os.path.join(out_dir, "packsize_macros.tex"), "w") as fh:
                fh.write(macros_packsize(sweep, order, meta))
            written += ["figures/packsize.tex", "figures/packsize_macros.tex"]
        ordt = table_ordering(order)
        if ordt:
            with open(os.path.join(tab_dir, "ordering.tex"), "w") as fh:
                fh.write(ordt)
            written.append("tables/ordering.tex")

    # Only the .out files: parse_convho reads the whitespace-aligned summary table, not the CSV
    # that sits beside it, and picking the wrong one silently yields an empty table.
    ho = ([f for f in sorted(os.listdir(DATA))
           if f.startswith("convho_") and f.endswith(".out")] if os.path.isdir(DATA) else [])
    if ho:
        hr = parse_convho(os.path.join(DATA, ho[-1]))
        convho_rows = hr
        t = table_convho(hr)
        fg = fig_convho(hr, spmv_ref)
        if fg:
            with open(os.path.join(out_dir, "convho.tex"), "w") as fh:
                fh.write(fg)
            written.append("figures/convho.tex")
        if t:
            with open(os.path.join(tab_dir, "convho.tex"), "w") as fh:
                fh.write(t)
            written.append("tables/convho.tex")
            # A higher-order arm that agrees with first order bit for bit did not run.
            with open(os.path.join(out_dir, "convho_macros.tex"), "w") as fh:
                fh.write(macros_convho(hr))
            written.append("figures/convho_macros.tex")
            for lay in ("atomic", "packed"):
                base = next((r for r in hr if r.arm == "first_order" and r.layout == lay), None)
                if not base:
                    continue
                same = [r.arm for r in hr
                        if r.arm != "first_order" and r.layout == lay
                        and r.checksum == base.checksum]
                if same:
                    print("  WARNING: %s checksum identical to first order -- correction not"
                          " applied in: %s" % (lay, ", ".join(same)))

    ng = [f for f in sorted(os.listdir(DATA)) if f.startswith("ngrad_")] if os.path.isdir(DATA) else []
    if ng:
        nr = parse_ngrad(os.path.join(DATA, ng[-1]))
        if nr:
            with open(os.path.join(out_dir, "ngrad_macros.tex"), "w") as fh:
                fh.write(macros_ngrad(nr))
            written.append("figures/ngrad_macros.tex")

    hx = [f for f in sorted(os.listdir(DATA)) if f.startswith("hoexact_")] if os.path.isdir(DATA) else []
    if hx:
        hr, hc, hf = parse_hoexact(os.path.join(DATA, hx[-1]))
        if hr:
            with open(os.path.join(out_dir, "hoexact_macros.tex"), "w") as fh:
                fh.write(macros_hoexact(hr, hc, hf))
            written.append("figures/hoexact_macros.tex")

    jf = [f for f in sorted(os.listdir(DATA)) if f.startswith("jacfair_")] if os.path.isdir(DATA) else []
    if jf:
        jr = parse_jacfair(os.path.join(DATA, jf[-1]))
        t = table_jacfair(jr)
        if t:
            with open(os.path.join(tab_dir, "jacfair.tex"), "w") as fh:
                fh.write(t)
            with open(os.path.join(out_dir, "jacfair_macros.tex"), "w") as fh:
                fh.write(macros_jacfair(jr))
            written += ["tables/jacfair.tex", "figures/jacfair_macros.tex"]

    # F8 needs three things from three different jobs: the campaign (points), STREAM (memory
    # roof) and the GEMM peak (compute roof). Emitted only when all three are present, so a
    # roofline is never drawn with a roof that was assumed.
    pk = [f for f in sorted(os.listdir(DATA)) if f.startswith("peak_")] if os.path.isdir(DATA) else []
    if camp and st and pk and rows:
        peak = parse_peak(os.path.join(DATA, pk[-1]))
        rates = parse_stream(os.path.join(DATA, st[-1]))
        bw = rates.get(max(rates)) if rates else None
        # Measured DRAM traffic per dof, if a differenced SCF capture is present. Preferred over
        # the model; see roofline_points.
        # EVERY dram_ file, not the newest: the captures were made by different jobs for
        # different operators, each file named for the jobs behind it, and taking one would
        # silently drop whichever operator was measured first.
        dm = [f for f in sorted(os.listdir(DATA)) if f.startswith("dram_")]
        measured_dram = {}
        for name in dm:
            measured_dram.update(parse_dram(os.path.join(DATA, name)))
        if peak and bw:
            pts = roofline_points(rows, n=128, measured_bytes=measured_dram)
            ho_path = roofline_ho_points(convho_rows, measured_dram)
            if pts:
                with open(os.path.join(out_dir, "roofline.tex"), "w") as fh:
                    fh.write(fig_roofline(pts, bw, peak, ho=ho_path))
                with open(os.path.join(out_dir, "roofline_macros.tex"), "w") as fh:
                    fh.write(PREAMBLE
                             + "\\newcommand{\\rlPeak}{%.0f}\n" % peak
                             + "\\newcommand{\\rlBw}{%.0f}\n" % bw
                             + "\\newcommand{\\rlRidge}{%.1f}\n" % (peak / bw)
                             + macros_roofline_ho(ho_path, measured_dram)
                             + "\\newcommand{\\rlSpecPeak}{%.2f}\n" % (SPEC_PEAK_GFLOPS / 1000.0)
                             + "\\newcommand{\\rlSpecBw}{%.0f}\n" % SPEC_BW_GBS
                             + "\\newcommand{\\rlSpecRidge}{%.1f}\n"
                               % (SPEC_PEAK_GFLOPS / SPEC_BW_GBS)
                             + "\\newcommand{\\rlPeakPctSpec}{%.0f}\n"
                               % (100.0 * peak / SPEC_PEAK_GFLOPS)
                             + "\\newcommand{\\rlBwPctSpec}{%.0f}\n"
                               % (100.0 * bw / SPEC_BW_GBS)
                             + "".join("\\newcommand{\\rl%s}{%.0f}\n" % (_macro_name(l), g)
                                       for l, a, g, _m in pts)
                             + "".join("\\newcommand{\\rl%sAi}{%.1f}\n" % (_macro_name(l), a)
                                       for l, a, g, _m in pts)
                             # Each point as a percentage of the roof BINDING AT ITS OWN
                             # intensity -- memory below the ridge, compute above. This is the
                             # comparison the figure invites and it is easy to state wrongly by
                             # dividing everything by the compute peak.
                             + "".join("\\newcommand{\\rl%sPct}{%.0f}\n"
                                       % (_macro_name(l), 100.0 * g / min(peak, bw * a))
                                       for l, a, g, _m in pts)
                             + "\\newcommand{\\rlTrafficSource}{%s}\n"
                               % ("measured" if any(m for _l, _a, _g, m in pts) else "modelled"))
                written += ["figures/roofline.tex", "figures/roofline_macros.tex"]
    return written


# ---------------------------------------------------------------------------------------------

def selftest():
    fails = []

    def check(ok, what, detail=""):
        print("%-62s %s%s" % (what, "OK" if ok else "FAIL", ("  " + detail) if detail and not ok else ""))
        if not ok:
            fails.append(what)

    import tempfile

    sample = (
        "### host nid000000  n=100  repeats=3 at 72t  thread sweep: 1 8 36 72\n"
        "### fingerprints are comparable only DOWN a column\n"
        "\n"
        "layout    op    A: repeats @72t              B: across threads\n"
        "atomic    res   3 distinct / 3 runs          4 distinct / 4 runs\n"
        "packed    res   1 distinct / 3 runs          1 distinct / 4 runs\n"
        "colored   jac   1 distinct / 3 runs          2 distinct / 4 runs\n"
    )
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "det_layout_1.out")
        open(p, "w").write(sample)
        rows, meta = parse_determinism(p)

        check(len(rows) == 3, "every data row is parsed, header lines are not", "got %d" % len(rows))
        check(meta.get("host") == "nid000000" and meta.get("n") == "100",
              "the header's host and problem size are recovered")
        check(meta.get("threads") == "1 8 36 72", "the thread sweep is recovered")
        check(rows[0] == ("atomic", "res", (3, 3), (4, 4)), "an irreproducible row parses",
              str(rows[0]))
        check(rows[1] == ("packed", "res", (1, 3), (1, 4)), "a reproducible row parses",
              str(rows[1]))

        # No table any more: the finding is one sentence of prose, so what has to hold is that
        # the macros the prose quotes carry the verdict -- one distinct output where the layout
        # is reproducible, more where it is not.
        mac = macros_determinism(rows, meta)
        check(r"\newcommand{\detPackedresRep}{1}" in mac and r"\newcommand{\detAtomicresThr}{4}" in mac,
              "the macros carry the verdict the prose quotes")
        check(r"\newcommand{\detHost}{nid000000}" in mac, "the host macro is emitted")
        check(r"\newcommand{\detAtomicresRep}{3}" in mac, "a per-row macro is emitted")
        # LaTeX command names cannot contain digits or underscores.
        bad = [m for m in re.findall(r"\\newcommand\{\\([A-Za-z0-9]*)\}", mac)
               if not m.isalpha()]
        check(not bad, "every emitted macro name is alphabetic", str(bad))

        # STREAM: the unit conversion and the "peak is not at full socket" case.
        sp = os.path.join(td, "stream_1.out")
        open(sp, "w").write("### host nidX\n### 72 threads\n  Triad:   450596.7  0.1 0.1 0.1\n"
                            "### 36 threads\n  Triad:   480349.8  0.1 0.1 0.1\n")
        rates = parse_stream(sp)
        check(rates == {72: 450.5967, 36: 480.3498}, "stream triad parses in GB/s", str(rates))
        sm = macros_stream(rates)
        check(r"\newcommand{\streamTriad}{451}" in sm,
              "the bound quoted is the one at the measured thread count")
        check(r"\newcommand{\streamPeak}{480}" in sm and
              r"\newcommand{\streamPeakThreads}{36}" in sm,
              "the peak is reported separately, with the count it occurred at")

        # Campaign: the multi-host refusal, the bare-kernel predicate and the ladder.
        cp = os.path.join(td, "campaign_x.csv")
        hdr = ("host,operation,layout,ran_layout,kernel,cube_n,nodes,elements,dofs,bsr_nnz,"
               "bsr_values_MiB,bsr_storage,MDOF_s,ran_rc,ran_boundary,transient,pgrad_per_apply")
        def row(host, op, lay, n, mdof, rc="off", bnd="off", tr="0", pg="0", store="n/a"):
            return ",".join([host, op, lay, lay, "sumfact", str(n), "10", "8", "40", "0",
                             "0", store, str(mdof), rc, bnd, tr, pg])
        open(cp, "w").write("\n".join([hdr,
            row("nidA", "residual", "packed", 128, 2600),
            row("nidA", "residual", "atomic", 128, 850),
            row("nidA", "residual", "packed", 128, 1300, rc="on"),
            row("nidA", "residual", "atomic", 128, 600, rc="on"),
            row("nidA", "bsr_apply", "packed", 128, 450, store="f64"),
        ]) + "\n")
        rws, hst = read_campaign(cp)
        check(hst == "nidA" and len(rws) == 5, "a single-host campaign reads")
        check(sum(1 for r in rws if _bare(r)) == 3, "the bare-kernel predicate selects only bare rows",
              str(sum(1 for r in rws if _bare(r))))
        lad = table_ladder(rws)
        check(lad is not None and r"3.06\times" in lad.replace("\\times", "\\times"),
              "the ladder reports the bare rung ratio")
        check(r"1300" in lad and r"600" in lad, "the ladder reports the coupled rung")
        mac = macros_throughput(rws, hst)
        check(r"\newcommand{\campHost}{nidA}" in mac, "the campaign host is emitted for provenance")
        check(r"\newcommand{\campResPacked}{2600}" in mac, "the bare packed headline is emitted")
        check(r"\newcommand{\campProvisional}{0}" in mac,
              "a campaign is not marked provisional unless asked")
        check(r"\newcommand{\campProvisional}{1}" in macros_throughput(rws, hst, provisional=True),
              "the provisional marker is emitted when the data carries no job id")

        open(cp, "a").write(row("nidB", "residual", "packed", 128, 9999) + "\n")
        try:
            read_campaign(cp)
            check(False, "a multi-host campaign is refused")
        except ValueError:
            check(True, "a multi-host campaign is refused")

        # ---- the measured mesh footprint --------------------------------------------------
        # The arithmetic here is small but every number in it reaches the paper, and the three
        # totals differ only by which arrays they include -- exactly the kind of accounting
        # that is easy to get subtly wrong and impossible to notice afterwards.
        mf_sample = (
            "### mesh footprint, some host\n"
            "@@@ pack_size 1024\n"
            "### mesh footprint  n_nodes=1000 n_elements=900 dofs=4000\n"
            "### n_packs=4 elements_per_pack=1024 packed_elements=900 "
            "ghost_entries=200 ghost_reduce_rows=150\n"
            "\n"
            "array                                 bytes        B/dof\n"
            "standard.topology_total                40000        10.000\n"
            "packed.elements                        20000         5.000\n"
            "packed.ghost_reduce_ptr                 4000         1.000\n"
            "packed.ghost_reduce_idx                 4000         1.000\n"
            "packed.node_map                         4000         1.000\n"
            "packed.topology_total                  32000         8.000\n"
            "shared.points                          12000         3.000\n"
            "\npacked/standard topology_only   0.8000\n"
        )
        with tempfile.TemporaryDirectory() as td3:
            mp = os.path.join(td3, "meshfoot_x.out")
            open(mp, "w").write(mf_sample)
            mf = parse_meshfoot(mp)
            check(list(mf) == [1024], "one pack-size block is parsed", "got %s" % list(mf))
            check(mf[1024]["ghost_entries"] == 200 and mf[1024]["ghost_reduce_rows"] == 150,
                  "the ghost and reduction-graph counts are read, not derived")
            t = meshfoot_totals(mf)
            check(abs(t["impl"] - 8.0) < 1e-9, "the implemented total is the reported one")
            check(abs(t["working"] - 7.0) < 1e-9,
                  "the working set drops node_map and nothing else")
            check(abs(t["floor"] - 6.0) < 1e-9,
                  "the floor halves both reduction offset arrays and nothing else")
            check(t["floor"] < t["working"] < t["impl"],
                  "the three totals are ordered, so none can silently be the flattering one")
            check(abs(t["std_pts"] - 13.0) < 1e-9 and abs(t["impl_pts"] - 11.0) < 1e-9,
                  "the coordinates are added to both representations, never to one")
            check(abs(t["r_impl"] - 0.8) < 1e-9,
                  "the implemented ratio matches what the bench itself printed")
            # A missing block must yield nothing rather than a partial total.
            check(meshfoot_totals(mf, 99999) is None,
                  "a pack size that was not measured yields no total")

        # ---- measured DRAM traffic --------------------------------------------------------
        # The differencing is the whole point of the two-capture format, and getting it wrong
        # would silently divide setup and warmup into the per-apply figure.
        with tempfile.TemporaryDirectory() as td4:
            dp = os.path.join(td4, "dram_x.out")
            open(dp, "w").write(
                "# comment\n"
                "residual  packed  10  40   1000   4000   100\n"
                "residual  atomic  10  40   2000   2300   100\n")
            dm = parse_dram(dp)
            # (4000-1000)/(40-10)/100 = 1.0 byte per dof per apply
            check(abs(dm[("residual", "packed")] - 1.0) < 1e-12,
                  "traffic is differenced across repeat count, not divided by it")
            check(abs(dm[("residual", "atomic")] - 0.1) < 1e-12,
                  "a second configuration is read independently")
            check(("residual", "colored") not in dm,
                  "a configuration absent from the capture yields no entry")

        # A point with measured traffic must report it as measured, and one without must not.
        camp_pts = [{"_n": 128, "_dofs": 400, "_mdof": 100.0, "operation": "residual",
                     "ran_layout": "packed", "GFLOP_s_model": "40", "elements": "100",
                     "nodes": "100", "ran_rc": "off", "ran_boundary": "off", "transient": "0"}]
        got = roofline_points(camp_pts, n=128, measured_bytes={("residual", "packed"): 2.0})
        check(bool(got) and got[0][3] is True and abs(got[0][1] - 200.0) < 1e-9,
              "measured traffic is used where present, and flagged")
        got = roofline_points(camp_pts, n=128, measured_bytes={})
        check(bool(got) and got[0][3] is False,
              "the model is used where no measurement exists, and flagged")

        # Missing data must be absent, not fabricated.
        with tempfile.TemporaryDirectory() as td2:
            written = build(os.path.join(td2, "f"), os.path.join(td2, "t"))
            check(isinstance(written, list), "build returns the list of files it wrote")

    print()
    if fails:
        print("%d check(s) FAILED" % len(fails))
        return 1
    print("all performance-figure checks passed")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=os.path.join(HERE, "..", "figures"))
    ap.add_argument("--tables", default=os.path.join(HERE, "..", "tables"))
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(selftest())

    written = build(args.out, args.tables)
    if not written:
        print("no measurements in %s yet -- see README.md for the programme" % os.path.abspath(DATA))
    for w in written:
        print("wrote %s" % w)


if __name__ == "__main__":
    main()
