#!/usr/bin/env python3
"""Figures and tables built from the measurements (paper F5-F8, T1-T3).

Stdlib only, and every emitter carries a selftest, following the repository's report
generators: the Alps uenv has no numpy or matplotlib, so anything that cannot run where the
measurements are taken will go stale.

Inputs live in ../data and are copied verbatim from the job that produced them, so the job id
is part of the filename and a number in the paper can be traced back to a run. Nothing here
edits a measurement; it only reshapes one.

Usage:
    python3 perf_figures.py --out ../figures --tables ../tables
    python3 perf_figures.py --selftest
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

# One row of the determinism table. Anchored on the two "<d> distinct / <n> runs" cells so
# that an appended marker such as "(INCOMPLETE)" cannot shift the fields.
_DET_ROW = re.compile(
    r"^(atomic|packed|colored|store)\s+(\w+)\s+"
    r"(\d+)\s+distinct\s*/\s*(\d+)\s+runs\S*\s+"
    r"(\d+)\s+distinct\s*/\s*(\d+)\s+runs")

PREAMBLE = ("%% Generated by wip/paper/python/perf_figures.py -- do not edit.\n"
            "%% Regenerate with: make figures\n")


# ---------------------------------------------------------------------------------------------
# T2: reproducibility by layout
# ---------------------------------------------------------------------------------------------

def parse_determinism(path):
    """Read jobs/det_layout.sbatch's output.

    The job prints one row per (layout, operation) as "<d> distinct / <n> runs" for two
    questions: repeats at a fixed thread count, and one run at each of several thread counts.
    Returns [(layout, op, (d_a, n_a), (d_b, n_b))] plus the header facts, so the caption can
    state the problem size and the thread counts rather than have them typed in.
    """
    rows, meta = [], {}
    for line in open(path):
        s = line.strip()
        if s.startswith("### host"):
            # "### host nid006545  n=100  repeats=3 at 72t  thread sweep: 1 8 36 72"
            parts = s.split()
            meta["host"] = parts[2]
            for tok in parts:
                if tok.startswith("n="):
                    meta["n"] = tok[2:]
                if tok.startswith("repeats="):
                    meta["repeats"] = tok[len("repeats="):]
            if "thread sweep:" in s:
                meta["threads"] = s.split("thread sweep:")[1].strip()
            continue
        # layout op <d> distinct / <n> runs   <d> distinct / <n> runs
        #
        # Matched rather than split on whitespace: the job appends "(INCOMPLETE)" to a cell
        # whose runs did not all produce a fingerprint, which shifts every later field and
        # silently mis-parsed the row when this counted tokens.
        m = _DET_ROW.match(s)
        if m:
            rows.append((m.group(1), m.group(2),
                         (int(m.group(3)), int(m.group(4))),
                         (int(m.group(5)), int(m.group(6)))))
    return rows, meta


OP_NAME = {"res": "residual", "jac": "Jacobian action"}


def table_determinism(rows, meta):
    """T2. The verdict column is the point: 1 distinct output means bit-reproducible.

    Rows are compared DOWN a column and never across, because packing renumbers the mesh and a
    fingerprint folds the output in node order -- so two layouts disagree by construction even
    when both are perfectly reproducible. The table says so in its own note rather than relying
    on the prose to carry it.
    """
    out = [PREAMBLE, r"\begin{tabular}{llcc}", r"\toprule",
           r"& & \multicolumn{2}{c}{distinct outputs} \\",
           r"\cmidrule(lr){3-4}",
           r"layout & operator & repeats & thread counts \\",
           r"\midrule"]
    for layout, op, a, b in rows:
        verdict = lambda d, n: (r"\textbf{%d} / %d" % (d, n)) if d == 1 else ("%d / %d" % (d, n))
        out.append(r"\texttt{%s} & %s & %s & %s \\"
                   % (layout, OP_NAME.get(op, op), verdict(*a), verdict(*b)))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def macros_determinism(rows, meta):
    """The facts the caption and prose quote, so no digit is typed twice."""
    out = [PREAMBLE]
    out.append(r"\newcommand{\detHost}{%s}" % meta.get("host", "?"))
    out.append(r"\newcommand{\detN}{%s}" % meta.get("n", "?"))
    out.append(r"\newcommand{\detRepeats}{%s}" % meta.get("repeats", "?"))
    out.append(r"\newcommand{\detThreads}{%s}" % meta.get("threads", "?").replace(" ", ", "))
    for layout, op, a, b in rows:
        key = (layout + op).capitalize()
        out.append(r"\newcommand{\det%sRep}{%d}" % (key, a[0]))
        out.append(r"\newcommand{\det%sThr}{%d}" % (key, b[0]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# T3: memory footprint
# ---------------------------------------------------------------------------------------------

# Widths the format fixes, named here so the arithmetic below can be read against the code.
PACK_IDX_BYTES = 2    # pack_idx_t is uint16_t; this is what bounds a pack's node count
GLOBAL_IDX_BYTES = 4  # idx_t in the flat connectivity and in the BSR column index
GEOM_BYTES = 4        # geom_t is float
NODES_PER_ELEM = 8    # HEX8
BLOCK = 4             # 4x4 blocks: three velocity components and pressure


def footprint_rows(csv_path):
    """Bytes per degree of freedom for the representations the paper compares.

    THIS IS NOT A TIMING, which is why it may be taken from an older campaign. Every quantity
    below is a deterministic function of the mesh size and the storage precision -- the row
    count, the block count, the index widths -- so it does not inherit the node-to-node
    variation that makes two campaigns' THROUGHPUTS incomparable. The distinction is worth
    making explicitly, because the rule against mixing campaigns is otherwise absolute.

    Counted on both sides: only what the apply must read to evaluate the operator. Solution
    and result vectors are excluded from both, since they are identical for every layout and
    including them would flatter the matrix.
    """
    rows = {}
    with open(csv_path) as fh:
        head = fh.readline().rstrip("\n").split(",")
        ix = {name: i for i, name in enumerate(head)}
        for line in fh:
            f = line.rstrip("\n").split(",")
            if len(f) != len(head) or f[ix["operation"]] != "bsr_apply":
                continue
            n = int(f[ix["cube_n"]])
            store = f[ix["bsr_storage"]]
            key = (n, store)
            if key in rows:
                continue
            dofs = int(f[ix["dofs"]])
            nodes = int(f[ix["nodes"]])
            elems = int(f[ix["elements"]])
            blocks = int(f[ix["bsr_nnz"]])
            vals = float(f[ix["bsr_values_MiB"]]) * 1024 * 1024
            # The matrix also carries its pattern: one column index per block, one row pointer
            # per block row. Omitting it would understate the matrix by ~3%.
            idx = blocks * GLOBAL_IDX_BYTES + (nodes + 1) * GLOBAL_IDX_BYTES
            # The matrix-free side reads the mesh: pack-local connectivity and coordinates.
            conn = elems * NODES_PER_ELEM * PACK_IDX_BYTES
            coords = nodes * 3 * GEOM_BYTES
            rows[key] = {
                "n": n, "store": store, "dofs": dofs,
                "bsr": (vals + idx) / dofs,
                "packed": (conn + coords) / dofs,
            }
    return [rows[k] for k in sorted(rows)]


def parse_meshfoot(path):
    """Read the bench's --mesh-footprint report: {pack_size: {array: bytes}} plus counts.

    This replaces an earlier arithmetic model of the same quantity, which is why there is no
    model left to compare against. The model had to guess the two numbers that decide the
    answer -- how many ghost entries the packs produce and how many rows the reduction graph
    has -- because neither has a closed form: they depend on how the pack boundaries happen to
    cut the mesh. It guessed both from the mean node count per pack and was wrong by about
    20%. The bench now reports every array's own nbytes(), so this parser reads measurements.
    """
    out, cur = {}, None
    for line in open(path):
        line = line.strip()
        if line.startswith("@@@ pack_size"):
            cur = int(line.split()[-1])
            out[cur] = {"arrays": {}}
        elif cur is None:
            continue
        elif line.startswith("### mesh footprint"):
            for k in ("n_nodes", "n_elements", "dofs"):
                m = re.search(k + r"=(\d+)", line)
                if m:
                    out[cur][k] = int(m.group(1))
        elif line.startswith("### n_packs"):
            for k in ("n_packs", "ghost_entries", "ghost_reduce_rows"):
                m = re.search(k + r"=(\d+)", line)
                if m:
                    out[cur][k] = int(m.group(1))
        else:
            f = line.split()
            if len(f) == 3 and ("." in f[0]) and f[1].isdigit():
                out[cur]["arrays"][f[0]] = int(f[1])
    return {k: v for k, v in out.items() if v.get("dofs") and v["arrays"]}


# The pack size the paper reports the footprint at: the shipped default, so the table describes
# the format as a user gets it. The alternative -- quoting the best-performing pack size -- would
# report a configuration nobody runs by default.
MESHFOOT_PACK = 1024
# The pack size the performance sweep favours, quoted alongside because the footprint improves
# in the same direction: bigger packs mean proportionally fewer ghosts.
MESHFOOT_PACK_BIG = 4096


def meshfoot_totals(mf, pack=MESHFOOT_PACK):
    """Three totals for the packed mesh's topology, because three different questions get asked.

    *as implemented* is every array the format allocates today. *working set* drops
    ``node_map``, the permutation between packed and unpacked numbering: the apply never reads
    it, and a solver whose fields live in packed numbering throughout does not either. *floor*
    additionally narrows the two reduction-graph offset arrays from 64 to 32 bits, which their
    own lengths permit with three orders of magnitude to spare -- the graph indexes fewer than a
    million entries and spends eight bytes per index doing it.

    All three are reported rather than the flattering one. The gap between the first and the
    third is not a property of the format; it is 64-bit offsets into a small array plus a
    permutation the operator does not read, and the paper says so.
    """
    d = mf.get(pack)
    if not d:
        return None
    a, dofs = d["arrays"], float(d["dofs"])
    impl = a["packed.topology_total"]
    node_map = a.get("packed.node_map", 0)
    # Halving the two offset arrays: ptrdiff_t -> a 32-bit count, which their lengths admit.
    reduce64 = a.get("packed.ghost_reduce_ptr", 0) + a.get("packed.ghost_reduce_idx", 0)
    std = a["standard.topology_total"]
    pts = a["shared.points"]
    working = impl - node_map
    floor = working - reduce64 // 2
    return {
        "pack": pack, "dofs": d["dofs"], "nodes": d["n_nodes"], "n_packs": d["n_packs"],
        "ghost_entries": d["ghost_entries"], "ghost_rows": d["ghost_reduce_rows"],
        "std": std / dofs, "pts": pts / dofs,
        "impl": impl / dofs, "working": working / dofs, "floor": floor / dofs,
        "node_map": node_map / dofs, "reduce_saving": (reduce64 // 2) / dofs,
        "conn": a["packed.elements"] / dofs,
        "r_impl": impl / std, "r_working": working / std, "r_floor": floor / std,
        "r_impl_pts": (impl + pts) / (std + pts),
        # The whole mesh, coordinates included. Reported separately because the coordinates are
        # byte-for-byte identical in both representations, so including them dilutes the ratio
        # without changing any quantity the format controls.
        "std_pts": (std + pts) / dofs, "impl_pts": (impl + pts) / dofs,
    }


def macros_meshfoot(mf):
    """Every footprint figure the prose quotes, at the default pack size and the larger one."""
    t = meshfoot_totals(mf)
    if not t:
        return None
    out = [PREAMBLE]
    for k, fmt in (("std", "%.2f"), ("impl", "%.2f"), ("working", "%.2f"), ("floor", "%.2f"),
                   ("node_map", "%.2f"), ("reduce_saving", "%.2f"), ("conn", "%.2f"),
                   ("std_pts", "%.1f"), ("impl_pts", "%.1f")):
        out.append(r"\newcommand{\fp%s}{%s}" % (k.title().replace("_", ""), fmt % t[k]))
    for k in ("r_impl", "r_working", "r_floor", "r_impl_pts"):
        out.append(r"\newcommand{\fp%sPct}{%.0f}"
                   % (k[2:].title().replace("_", ""), 100.0 * t[k]))
    out.append(r"\newcommand{\fpPack}{%d}" % t["pack"])
    out.append(r"\newcommand{\fpGhostPct}{%.0f}"
               % (100.0 * t["ghost_entries"] / float(t["nodes"])))
    big = meshfoot_totals(mf, MESHFOOT_PACK_BIG)
    if big:
        out.append(r"\newcommand{\fpPackBig}{%d}" % big["pack"])
        out.append(r"\newcommand{\fpFloorBigPct}{%.0f}" % (100.0 * big["r_floor"]))
        out.append(r"\newcommand{\fpImplBigPct}{%.0f}" % (100.0 * big["r_impl"]))
    return "\n".join(out) + "\n"


def table_footprint(rows, mesh=None, n=128):
    """T3. What each representation must read, per degree of freedom, at one size.

    One size rather than four: the per-dof figures move by under two per cent across the range,
    so repeating them four times spent a third of a column to say the same thing.

    ``mesh`` is the measured mesh footprint from meshfoot_totals(), not a model. The packed
    figure it contributes is the format AS IMPLEMENTED, including the two items the text then
    names as avoidable; putting the reduced figure here instead would quote the format at its
    best in the table and its worst in the prose.
    """
    at_n = [r for r in rows if r["_n"] == n and r["operation"] == "bsr_apply"]
    if not at_n:
        return None
    out = [PREAMBLE, r"\small", r"\begin{tabular}{@{}lrr@{}}", r"\toprule",
           r"representation & B/dof & vs.\ packed mesh \\", r"\midrule"]
    base = mesh["impl"] if mesh else None
    if mesh:
        out.append(r"packed mesh & %.1f & --- \\" % mesh["impl"])
        out.append(r"standard mesh & %.1f & $%.2f\times$ \\"
                   % (mesh["std"], mesh["std"] / base))
        out.append(r"\midrule")
    seen = set()
    for store in ("f32", "f64"):
        c = [r for r in at_n if r["bsr_storage"] == store]
        if not c or store in seen:
            continue
        seen.add(store)
        b = c[0]
        blocks, nodes = int(b["bsr_nnz"]), int(b["nodes"])
        vals = float(b["bsr_values_MiB"]) * 1024 * 1024
        idx = blocks * GLOBAL_IDX_BYTES + (nodes + 1) * GLOBAL_IDX_BYTES
        per = (vals + idx) / b["_dofs"]
        rel = (r"$%.0f\times$" % (per / base)) if base else "---"
        out.append(r"assembled matrix, \texttt{%s} & %.0f & %s \\" % (store, per, rel))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F6: thread scaling   (restored -- lost to an over-wide block replacement, see README)
# ---------------------------------------------------------------------------------------------

LAYOUT_STYLE = {
    "packed":  ("PackA", "*"),
    "atomic":  ("PackD", "square*"),
    "colored": ("PackC", "triangle*"),
}


def parse_scaling(path):
    """Read jobs/thread_scaling.sbatch's table.

    Returns {(layout, op): [(threads, mdof)]} plus meta. Rows whose throughput is a dash are
    dropped rather than read as zero: a missing measurement must not become a point at the
    origin, which would bend a scaling curve toward superlinearity.
    """
    series, meta = {}, {}
    for line in open(path):
        t = line.strip()
        if t.startswith("### host"):
            parts = t.split()
            meta["host"] = parts[2]
            for tok in parts:
                if tok.startswith("n="):
                    meta["n"] = tok[2:]
            continue
        f = t.split()
        if len(f) >= 4 and f[0] in LAYOUT_STYLE and f[1] in ("res", "jac"):
            if f[3] == "-":
                continue
            try:
                thr, mdof = int(f[2]), float(f[3])
            except ValueError:
                continue
            series.setdefault((f[0], f[1]), []).append((thr, mdof))
            if len(f) > 4 and f[4] != "-":
                meta["packs"] = f[4]
    for k in series:
        series[k].sort()
    return series, meta


def fig_scaling(series, meta, op="res"):
    """F6. Throughput against thread count, log-log with an ideal line.

    Log-log because the content is the DEPARTURE from ideal, and on linear axes the low thread
    counts are invisible.
    """
    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{loglogaxis}[",
           r"  width=\columnwidth, height=0.55\columnwidth,",
           r"  xlabel={OpenMP threads}, ylabel={MDOF/s},",
           r"  log basis x=2, xtick={1,2,4,8,18,36,72}, xticklabels={1,2,4,8,18,36,72},",
           r"  legend pos=north west, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    # The ideal line is anchored on the SLOWEST layout at one thread, so the reference is not
    # drawn from the layout being advocated.
    base = None
    for layout in ("atomic", "packed", "colored"):
        pts = series.get((layout, op))
        if pts and pts[0][0] == 1 and (base is None or pts[0][1] < base[1]):
            base = pts[0]
    if base:
        t0, m0 = base
        out.append(r"\addplot[black!45,dashed,no marks,forget plot] coordinates "
                   r"{(1,%.4f) (72,%.4f)};" % (m0, m0 * 72.0 / t0))
        out.append(r"\node[black!55,font=\tiny,rotate=37,anchor=south east] "
                   r"at (axis cs:36,%.1f) {ideal};" % (m0 * 30.0))
    for layout in ("packed", "atomic", "colored"):
        pts = series.get((layout, op))
        if not pts:
            continue
        col, mark = LAYOUT_STYLE[layout]
        out.append(r"\addplot[%s,mark=%s,mark size=1.4pt,thick] coordinates {%s};"
                   % (col, mark, " ".join("(%d,%.4f)" % q for q in pts)))
        out.append(r"\addlegendentry{\texttt{%s}}" % layout)
    out.append(r"\end{loglogaxis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def macros_scaling(series, meta):
    """Endpoints, speedups and efficiencies, so the prose quotes no typed digit."""
    out = [PREAMBLE]
    out.append(r"\newcommand{\scaleHost}{%s}" % meta.get("host", "?"))
    out.append(r"\newcommand{\scalePacks}{%s}" % meta.get("packs", "?"))
    names = {"res": "Res", "jac": "Jac"}
    for (layout, op), pts in sorted(series.items()):
        d = dict(pts)
        if not d:
            continue
        one, nthr = d.get(1), max(d)
        top = d.get(nthr)
        if not one or not top:
            continue
        key = layout.capitalize() + names.get(op, op)
        out.append(r"\newcommand{\scale%sOne}{%.1f}" % (key, one))
        out.append(r"\newcommand{\scale%sTop}{%.0f}" % (key, top))
        out.append(r"\newcommand{\scale%sSpeedup}{%.1f}" % (key, top / one))
        out.append(r"\newcommand{\scale%sEff}{%.0f}" % (key, 100.0 * (top / one) / nthr))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# M6: the machine's memory bound   (restored)
# ---------------------------------------------------------------------------------------------

def parse_stream(path):
    """Triad rate per thread count, in GB/s.

    STREAM reports MB/s in powers of ten, so the conversion is by 1000 and not 1024; getting
    that wrong overstates the bound by 7% and makes every roofline efficiency look worse.
    """
    rates, threads = {}, None
    for line in open(path):
        t = line.strip()
        if t.startswith("###") and "threads" in t:
            try:
                threads = int(t.split()[1])
            except (IndexError, ValueError):
                threads = None
            continue
        if t.startswith("Triad:") and threads is not None:
            rates[threads] = float(t.split()[1]) / 1000.0
    return rates


def macros_stream(rates):
    """The bound at the measured thread count, and the peak, which are not the same.

    Bandwidth saturates below the full socket, so the 72-thread figure -- the configuration
    every kernel here runs in -- is LOWER than the machine's best. Both are emitted and the
    paper quotes the one matching its configuration, not the flattering one.
    """
    if not rates:
        return PREAMBLE
    full = max(rates)
    best_t = max(rates, key=lambda k: rates[k])
    out = [PREAMBLE]
    out.append(r"\newcommand{\streamTriad}{%.0f}" % rates[full])
    out.append(r"\newcommand{\streamThreads}{%d}" % full)
    out.append(r"\newcommand{\streamPeak}{%.0f}" % rates[best_t])
    out.append(r"\newcommand{\streamPeakThreads}{%d}" % best_t)
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F5 / T1: throughput and the term-completeness ladder
# ---------------------------------------------------------------------------------------------

def read_campaign(path):
    """Rows of a layout-campaign CSV, as dicts, with the numeric fields converted.

    REFUSES A CSV SPANNING SEVERAL HOSTS. The tables below keep the best reading per
    configuration, so across two nodes a packed row and the atomic row it is divided by can come
    from different machines, which manufactures a layout ratio out of node-to-node variation
    (5-11% here). The campaign appends to its csv and the batch jobs once wrote into a fixed
    directory, so this is a situation that has actually arisen, not a hypothetical.
    """
    import csv as _csv
    with open(path) as fh:
        rows = list(_csv.DictReader(fh))
    hosts = sorted({r.get("host", "?") for r in rows})
    if len(hosts) > 1:
        raise ValueError("campaign spans %d hosts (%s); split it by host before plotting"
                         % (len(hosts), ", ".join(hosts)))
    out = []
    for r in rows:
        try:
            r["_n"] = int(r["cube_n"])
            r["_dofs"] = int(r["dofs"])
            r["_mdof"] = float(r["MDOF_s"])
        except (KeyError, ValueError):
            continue
        out.append(r)
    return out, (hosts[0] if hosts else "?")


def _bare(r):
    """The bare element kernel: no solver terms carried."""
    return (r.get("ran_rc") == "off" and r.get("ran_boundary") == "off"
            and r.get("transient") in ("0", "", None)
            and r.get("pgrad_per_apply") in ("0", "", None))


def best(rows, **eq):
    """Best observed rate among rows matching every keyword.

    Best rather than mean, because background load can only make a run slower -- the same
    convention the repository's own kernel report uses.
    """
    sel = [r for r in rows if all(r.get(k) == v for k, v in eq.items())]
    return max((r["_mdof"] for r in sel), default=None)


def fig_throughput(rows, host, op="residual"):
    """F5. Throughput against problem size for the three representations.

    The assembled matrix is drawn at both storage precisions because halving the value width is
    essentially the only lever a bandwidth-bound SpMV has, and it is the fairest version of the
    comparison.
    """
    sizes = sorted({r["_n"] for r in rows})
    series = []
    for layout, col, mark, lab in (("packed", "PackA", "*", r"packed"),
                                   ("atomic", "PackD", "square*", r"atomic")):
        pts = []
        for n in sizes:
            v = max((r["_mdof"] for r in rows
                     if r["operation"] == op and r["ran_layout"] == layout
                     and r["_n"] == n and _bare(r)), default=None)
            if v:
                pts.append((n, v))
        if pts:
            series.append((col, mark, lab, pts))
    for store, col, mark, lab in (("f64", "PackE", "triangle*", r"BSR SpMV \texttt{f64}"),
                                  ("f32", "PackC", "diamond*", r"BSR SpMV \texttt{f32}")):
        pts = []
        for n in sizes:
            v = max((r["_mdof"] for r in rows
                     if r["operation"] == "bsr_apply" and r["bsr_storage"] == store
                     and r["_n"] == n), default=None)
            if v:
                pts.append((n, v))
        if pts:
            series.append((col, mark, lab, pts))

    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{axis}[",
           r"  width=\columnwidth, height=0.55\columnwidth,",
           r"  xlabel={cube edge $n$}, ylabel={MDOF/s},",
           r"  xtick={%s}," % ",".join(str(n) for n in sizes),
           r"  ymin=0, legend pos=north east, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    for col, mark, lab, pts in series:
        out.append(r"\addplot[%s,mark=%s,mark size=1.6pt,thick] coordinates {%s};"
                   % (col, mark, " ".join("(%d,%.3f)" % p for p in pts)))
        out.append(r"\addlegendentry{%s}" % lab)
    out.append(r"\end{axis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


# The ladder, from bare element kernel to the operator a solver actually applies. Each rung adds
# ONE term, and both layouts pay for it, which is the whole reason the ladder is reported: a
# comparison made on the bare kernel overstates the margin a solver receives.
LADDER = [
    (r"element kernel", dict(ran_rc="off", ran_boundary="off", transient="0", pgrad_per_apply="0")),
    (r"${}+{}$ pressure--velocity coupling", dict(ran_rc="on", ran_boundary="off", transient="0", pgrad_per_apply="0")),
    (r"${}+{}$ boundary closure", dict(ran_rc="on", ran_boundary="on", transient="0", pgrad_per_apply="0")),
    (r"${}+{}$ transient term", dict(ran_rc="on", ran_boundary="on", transient="1", pgrad_per_apply="0")),
]


def table_ladder(rows, op="residual", n=128):
    at_n = [r for r in rows if r["_n"] == n and r["operation"] == op]
    out = [PREAMBLE, r"\begin{tabular}{lrrr}", r"\toprule",
           r"terms carried & packed & atomic & ratio \\",
           r"& \multicolumn{2}{c}{MDOF/s} & \\",
           r"\midrule"]
    any_row = False
    for label, sel in LADDER:
        p = best(at_n, ran_layout="packed", **sel)
        a = best(at_n, ran_layout="atomic", **sel)
        if p is None or a is None:
            continue
        any_row = True
        out.append(r"%s & %.0f & %.0f & $%.2f\times$ \\" % (label, p, a, p / a))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n" if any_row else None


def macros_throughput(rows, host, n=128, provisional=False):
    """Provenance and the headline figures, as macros.

    \\campProvisional is the safeguard that matters. A campaign CSV whose filename does not
    carry the job id that produced it did not come from a run this paper commissioned -- it is
    a file copied in to develop the plotting against -- and the caption then says so in the
    figure itself, rather than leaving the reader, or the author six weeks later, to check.
    Numbers from such a file validate the pipeline; they are never the paper's.
    """
    out = [PREAMBLE]
    out.append(r"\newcommand{\campProvisional}{%d}" % (1 if provisional else 0))
    out.append(r"\newcommand{\campHost}{%s}" % host)
    out.append(r"\newcommand{\campN}{%d}" % n)
    at_n = [r for r in rows if r["_n"] == n]
    dofs = max((r["_dofs"] for r in at_n), default=0)
    out.append(r"\newcommand{\campDofs}{%d}" % dofs)
    # The share of the exact-Rhie--Chow Jacobian matvec spent reconstructing the DIRECTION's
    # nodal pressure gradient. This is the second pass of a two-pass operator and the driver
    # times it separately precisely so it cannot be attributed to the element kernel.
    qg = [r for r in at_n if r["operation"] == "jac_action" and r.get("exact_rc") == "1"
          and r.get("ran_layout") == "packed" and r.get("frac_qgrad")]
    if qg:
        try:
            out.append(r"\newcommand{\campQgradPct}{%.0f}"
                       % (100.0 * max(float(r["frac_qgrad"]) for r in qg)))
        except ValueError:
            pass
    pairs = [("ResPacked", dict(operation="residual", ran_layout="packed")),
             ("ResAtomic", dict(operation="residual", ran_layout="atomic")),
             ("JacPacked", dict(operation="jac_action", ran_layout="packed")),
             ("JacAtomic", dict(operation="jac_action", ran_layout="atomic"))]
    for name, sel in pairs:
        v = max((r["_mdof"] for r in at_n
                 if all(r.get(k) == val for k, val in sel.items()) and _bare(r)), default=None)
        if v:
            out.append(r"\newcommand{\camp%s}{%.0f}" % (name, v))
    for name, store in (("SpmvF", "f64"), ("SpmvS", "f32")):
        v = max((r["_mdof"] for r in at_n
                 if r["operation"] == "bsr_apply" and r["bsr_storage"] == store), default=None)
        if v:
            out.append(r"\newcommand{\camp%s}{%.0f}" % (name, v))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F7 / T4: pack size, the index-type ceiling, and spatial ordering
# ---------------------------------------------------------------------------------------------

def parse_packsize(path):
    """Read jobs/packsize_paper.sbatch: the sweep rows and the ordering rows.

    Returns (sweep, order, meta) where sweep[n] is a list of dicts with the pack size, the pack
    count, packs per thread, mean nodes per pack and both throughputs.
    """
    sweep, order, meta, section = {}, [], {}, None
    for line in open(path):
        s = line.strip()
        if s.startswith("### host"):
            meta["host"] = s.split()[2]
            continue
        if s.startswith("### pack-size sweep"):
            section = "sweep"; continue
        if s.startswith("### spatial ordering"):
            section = "order"; continue
        if s.startswith("#") or not s:
            continue
        f = s.split()
        if section == "sweep" and len(f) == 8 and f[0].isdigit():
            try:
                sweep.setdefault(int(f[0]), []).append({
                    "pack": int(f[1]), "packs": int(f[3]), "ppt": float(f[4]),
                    "mean": int(f[5]), "res": float(f[6]), "jac": float(f[7])})
            except ValueError:
                pass
        elif section == "order" and len(f) == 6 and f[0].isdigit():
            try:
                order.append({"n": int(f[0]), "pack": int(f[1]), "order": f[2],
                              "mean": int(f[3]), "res": float(f[4]), "jac": float(f[5])})
            except ValueError:
                pass
    return sweep, order, meta


def fig_packsize(sweep, meta):
    """F7. Throughput against pack size, one series per problem size.

    The x axis is packs per thread rather than the pack size itself. The pack size is the knob,
    but the quantity that explains the collapse is how many units of parallel work it leaves
    for the cores, and plotting the knob hides that the two problem sizes fail at the same
    place on this axis while failing at different pack sizes.
    """
    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{semilogxaxis}[",
           r"  width=\columnwidth, height=0.55\columnwidth,",
           r"  xlabel={packs per thread}, ylabel={MDOF/s},",
           r"  log basis x=2, ymin=0,",
           r"  legend pos=south east, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    cols = {64: ("PackC", "triangle*"), 128: ("PackA", "*")}
    for n in sorted(sweep):
        col, mark = cols.get(n, ("PackE", "square*"))
        pts = sorted((r["ppt"], r["jac"]) for r in sweep[n])
        out.append(r"\addplot[%s,mark=%s,mark size=1.6pt,thick] coordinates {%s};"
                   % (col, mark, " ".join("(%.2f,%.3f)" % p for p in pts)))
        out.append(r"\addlegendentry{$n=%d$}" % n)
    # One pack per thread: below this line a core can be left with nothing at all.
    out.append(r"\draw[black!50,dashed] (axis cs:1,0) -- (axis cs:1,\pgfkeysvalueof{/pgfplots/ymax});")
    out.append(r"\node[black!55,font=\scriptsize,anchor=south west,rotate=90] "
               r"at (axis cs:1,0) {\ one pack per thread};")
    out.append(r"\end{semilogxaxis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def table_ordering(order):
    """T4. Space-filling against lexicographic element order at one pack size."""
    if not order:
        return None
    out = [PREAMBLE, r"\begin{tabular}{rlrrr}", r"\toprule",
           r"$n$ & element order & nodes/pack & residual & Jacobian \\",
           r"& & & \multicolumn{2}{c}{MDOF/s} \\", r"\midrule"]
    for r in order:
        name = "space-filling" if r["order"] == "sfc" else "lexicographic"
        out.append(r"%d & %s & %d & %.0f & %.0f \\"
                   % (r["n"], name, r["mean"], r["res"], r["jac"]))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def macros_packsize(sweep, order, meta):
    out = [PREAMBLE]
    out.append(r"\newcommand{\packHost}{%s}" % meta.get("host", "?"))
    for n, rows in sweep.items():
        tag = "Small" if n == min(sweep) else "Large"
        best = max(rows, key=lambda r: r["jac"])
        ceil = max(rows, key=lambda r: r["pack"])
        out.append(r"\newcommand{\pack%sN}{%d}" % (tag, n))
        out.append(r"\newcommand{\pack%sBest}{%d}" % (tag, best["pack"]))
        out.append(r"\newcommand{\pack%sBestJac}{%.0f}" % (tag, best["jac"]))
        out.append(r"\newcommand{\pack%sCeil}{%d}" % (tag, ceil["pack"]))
        out.append(r"\newcommand{\pack%sCeilJac}{%.0f}" % (tag, ceil["jac"]))
        out.append(r"\newcommand{\pack%sCeilPacks}{%d}" % (tag, ceil["packs"]))
        out.append(r"\newcommand{\pack%sCeilPpt}{%.1f}" % (tag, ceil["ppt"]))
        out.append(r"\newcommand{\pack%sCeilLoss}{%.1f}" % (tag, best["jac"] / ceil["jac"]))
    for r in order:
        if r["n"] == max(x["n"] for x in order):
            tag = "Sfc" if r["order"] == "sfc" else "Lex"
            out.append(r"\newcommand{\ord%sMean}{%d}" % (tag, r["mean"]))
            out.append(r"\newcommand{\ord%sJac}{%.0f}" % (tag, r["jac"]))
            out.append(r"\newcommand{\ord%sRes}{%.0f}" % (tag, r["res"]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# F8: roofline
# ---------------------------------------------------------------------------------------------

# Compulsory traffic per degree of freedom for one matrix-free apply, in bytes.
#
# MODELLED, NOT MEASURED, and the paper says so. The benchmark reports flops but not bytes, so
# this is a lower bound on traffic and therefore an UPPER bound on operational intensity: a
# point drawn with it sits at or to the right of where the kernel really is, which is the
# conservative direction for a claim that the kernel is near the memory roof.
#
# What is counted, per dof:
#   * the input field, read once                                              8 B
#   * the output field, written once                                          8 B
#   * the mesh the sweep must traverse -- pack-local connectivity and the
#     coordinates -- taken from the footprint model in footprint_rows()      ~6.9 B
# What is NOT counted: re-reads of a node's input by elements in other packs, which the format
# exists to avoid but does not eliminate at pack boundaries; and any spill. Both would raise
# traffic and lower intensity, which is why this is a bound rather than an estimate.
VECTOR_BYTES_PER_DOF = 16.0


def roofline_points(rows, mesh_bytes_per_dof, n=128):
    """(label, intensity FLOP/byte, achieved GFLOP/s) for the representations compared.

    The assembled SpMV is handled separately: its traffic is the matrix, not the mesh, and its
    flop count is two per nonzero scalar entry.
    """
    at_n = [r for r in rows if r["_n"] == n]
    pts = []
    for op, lay, label in (("residual", "packed", "residual, packed"),
                           ("residual", "atomic", "residual, atomic"),
                           ("jac_action", "packed", "Jacobian, packed"),
                           ("jac_action", "atomic", "Jacobian, atomic")):
        cand = [r for r in at_n if r["operation"] == op and r["ran_layout"] == lay and _bare(r)]
        if not cand:
            continue
        b = max(cand, key=lambda r: r["_mdof"])
        try:
            gflops = float(b["GFLOP_s_model"])
        except (KeyError, ValueError):
            continue
        if b["_mdof"] <= 0:
            continue
        flop_per_dof = gflops * 1e9 / (b["_mdof"] * 1e6)
        ai = flop_per_dof / (VECTOR_BYTES_PER_DOF + mesh_bytes_per_dof)
        pts.append((label, ai, gflops))
    for store, label in (("f64", r"SpMV \texttt{f64}"), ("f32", r"SpMV \texttt{f32}")):
        cand = [r for r in at_n if r["operation"] == "bsr_apply" and r["bsr_storage"] == store]
        if not cand:
            continue
        b = max(cand, key=lambda r: r["_mdof"])
        try:
            blocks, dofs = int(b["bsr_nnz"]), b["_dofs"]
            vals = float(b["bsr_values_MiB"]) * 1024 * 1024
        except (KeyError, ValueError):
            continue
        # Two flops per scalar entry of the 4x4 blocks; traffic is the matrix plus the vectors.
        flop = 2.0 * blocks * BLOCK * BLOCK
        byts = vals + blocks * GLOBAL_IDX_BYTES + dofs * VECTOR_BYTES_PER_DOF
        ai = flop / byts
        pts.append((label, ai, b["_mdof"] * 1e6 * (flop / dofs) * 1e-9))
    return pts


def fig_roofline(pts, bandwidth_gbs, peak_gflops):
    """F8. Both roofs measured on the same node as the points."""
    ridge = peak_gflops / bandwidth_gbs
    out = [PREAMBLE,
           r"\begin{tikzpicture}",
           r"\begin{loglogaxis}[",
           r"  width=\columnwidth, height=0.55\columnwidth,",
           r"  xlabel={operational intensity [FLOP/byte]}, ylabel={GFLOP/s},",
           r"  xmin=0.3, xmax=64, ymin=20, ymax=%.0f," % (peak_gflops * 1.8),
           r"  legend pos=south east, legend cell align=left,",
           r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
           r"  grid=both, major grid style={black!12}, minor grid style={black!6},",
           r"  tick label style={font=\tiny}, label style={font=\scriptsize},",
           r"]"]
    # The two roofs: bandwidth-limited below the ridge, compute-limited above.
    out.append(r"\addplot[black,thick,no marks,forget plot] coordinates "
               r"{(0.3,%.2f) (%.3f,%.1f) (64,%.1f)};"
               % (0.3 * bandwidth_gbs, ridge, peak_gflops, peak_gflops))
    out.append(r"\node[black!70,font=\scriptsize,anchor=south east,rotate=45] "
               r"at (axis cs:1.2,%.1f) {\ %.0f GB/s};" % (1.2 * bandwidth_gbs, bandwidth_gbs))
    out.append(r"\node[black!70,font=\scriptsize,anchor=south east] "
               r"at (axis cs:48,%.1f) {%.1f TFLOP/s\ };" % (peak_gflops * 1.06, peak_gflops / 1000.0))
    marks = ["*", "square*", "triangle*", "diamond*", "pentagon*", "otimes*"]
    cols = ["PackA", "PackD", "PackC", "PackE", "PackB", "PackF"]
    for i, (label, ai, gf) in enumerate(pts):
        out.append(r"\addplot[%s,mark=%s,mark size=2.1pt,only marks] coordinates {(%.3f,%.1f)};"
                   % (cols[i % len(cols)], marks[i % len(marks)], ai, gf))
        out.append(r"\addlegendentry{%s}" % label)
    out.append(r"\end{loglogaxis}")
    out.append(r"\end{tikzpicture}")
    return "\n".join(out) + "\n"


def _macro_name(label):
    """A LaTeX-safe, UNIQUE macro suffix for a roofline label.

    LaTeX command names may not contain digits, so the obvious "strip non-alpha" rule maps
    "SpMV f64" and "SpMV f32" onto the same name and emits \\newcommand twice for it, which is
    an error. Digits are spelled out instead, which keeps the names distinct and readable.
    """
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    out = []
    for c in label.replace("\\texttt", " ").title():
        if c.isalpha():
            out.append(c)
        elif c in digits:
            out.append(digits[c])
    return "".join(out)


def parse_peak(path):
    """Sustained fp64 GFLOP/s from jobs/peak_fp64.sbatch."""
    for line in open(path):
        if line.strip().startswith("PEAK_FP64_GFLOPS:"):
            try:
                return float(line.split(":")[1])
            except (IndexError, ValueError):
                return None
    return None


# ---------------------------------------------------------------------------------------------
# The higher-order convective flux
# ---------------------------------------------------------------------------------------------

# The four convective schemes, and for each the three arms that let one ratio isolate one
# variable: the packed GENERATED kernel, the packed hand-written kernel, and the atomic
# hand-written kernel. generated/hand is a kernel ratio at fixed layout; hand/atomic is a layout
# ratio at fixed kernel. A single "packed" column mixing the two would state neither.
HO_NAME = {
    "first_order": "first-order upwind",
    "ho_unlimited": "deferred correction, unlimited",
    "ho_clip": r"${}+{}$ bounded-face clip",
    "ho_venkatakrishnan": r"${}+{}$ Venkatakrishnan",
    "ho_darwish_moukalled": r"${}+{}$ Darwish--Moukalled",
}

# arm -> (scheme, role). The packed row of each scheme's base arm is the generated kernel; the
# _scalar rows are the hand-written reference. Arms absent here are read but not tabulated:
# ho_unlim_simd is the hand-written vectorised attempt that lost, and the Rhie-Chow pair is
# quoted in the prose rather than given a column, since no other scheme has an RC row to sit
# beside it.
HO_SCALAR_ARM = {
    "ho_unlim_scalar": "ho_unlimited",
    "ho_clip_scalar": "ho_clip",
    "ho_venk_scalar": "ho_venkatakrishnan",
    "ho_dm_scalar": "ho_darwish_moukalled",
}
HO_EXTRA = ("ho_unlim_simd", "ho_unlim_rc", "ho_unlim_rc_scalar")


def parse_convho(path):
    """Read jobs/conv_ho_bench.sbatch: (arm, layout, MDOF/s, dofs, checksum)."""
    known = set(HO_NAME) | set(HO_SCALAR_ARM) | set(HO_EXTRA)
    out = []
    for line in open(path):
        f = line.split()
        if len(f) == 5 and f[0] in known and f[1] in ("atomic", "packed") and f[2] != "-":
            try:
                out.append((f[0], f[1], float(f[2]), int(f[3]), f[4]))
            except ValueError:
                continue
    return out


def _convho_index(rows):
    """{scheme: {"gen":x, "hand":x, "atomic":x}} plus the loose arms, by name."""
    by = {}
    loose = {}
    for arm, lay, mdof, _dofs, _ck in rows:
        if arm in HO_SCALAR_ARM and lay == "packed":
            by.setdefault(HO_SCALAR_ARM[arm], {})["hand"] = mdof
        elif arm in HO_NAME:
            by.setdefault(arm, {})["gen" if lay == "packed" else "atomic"] = mdof
        elif arm in HO_EXTRA and lay == "packed":
            loose[arm] = mdof
    return by, loose


def table_convho(rows):
    """The convective schemes, packed against atomic, at the saturating size.

    Same shape as the completeness ladder: one row per variant, the two layouts side by side, and
    the ratio between them. First-order upwind is a row like the others rather than a separate
    presentation -- it is the scheme the higher-order arms correct, and the question asked of all
    five is the one the paper asks everywhere, which is what the layout is worth.

    Each column is that layout's own shipped kernel, which is the configuration a solver gets.

    The checksum is not printed but is still read: a higher-order row whose checksum equals the
    first-order one did not apply the correction, and its timing is first order measured twice.
    """
    if not rows:
        return None
    by, _loose = _convho_index(rows)
    out = [PREAMBLE, r"\small", r"\begin{tabular}{@{}lrrr@{}}", r"\toprule",
           r"convective scheme & packed & atomic & ratio \\",
           r"& \multicolumn{2}{c}{MDOF/s} & \\", r"\midrule"]
    for arm in ("first_order", "ho_unlimited", "ho_clip", "ho_venkatakrishnan",
                "ho_darwish_moukalled"):
        d = by.get(arm)
        if not d:
            continue
        pk, at = d.get("gen"), d.get("atomic")
        ratio = (r"$%.2f\times$" % (pk / at)) if (pk and at) else "---"
        out.append(r"%s & %s & %s & %s \\" % (HO_NAME[arm], _fmt0(pk), _fmt0(at), ratio))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def fig_convho(rows):
    """The same five variants as a figure, so the trend across schemes reads at a glance.

    A symbolic x axis rather than a size sweep: the higher-order arms are measured at the
    saturating size only, and plotting them against sizes they were not swept over would invent
    data.
    """
    if not rows:
        return None
    by, _loose = _convho_index(rows)
    order = [a for a in ("first_order", "ho_unlimited", "ho_clip", "ho_venkatakrishnan",
                         "ho_darwish_moukalled") if a in by]
    if not order:
        return None
    short = {"first_order": "upwind", "ho_unlimited": "unlimited", "ho_clip": "clip",
             "ho_venkatakrishnan": "Venkat.", "ho_darwish_moukalled": "Darwish--M."}
    coords = ",".join(short[a] for a in order)

    def series(key):
        return " ".join("(%s,%.1f)" % (short[a], by[a][key])
                        for a in order if by[a].get(key))

    return PREAMBLE + "\n".join([
        r"\begin{tikzpicture}",
        r"\begin{axis}[width=\columnwidth, height=0.44\columnwidth,",
        r"  ybar, bar width=7pt, ymin=0, ylabel={MDOF/s},",
        r"  symbolic x coords={%s}, xtick=data," % coords,
        r"  x tick label style={font=\tiny}, enlarge x limits=0.13,",
        r"  legend pos=north east, legend cell align=left,",
        r"  legend style={font=\tiny, draw=none, fill=none, inner sep=1pt},",
        r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},",
        r"  ymajorgrids, major grid style={black!12}]",
        r"\addplot[draw=PackA, fill=PackA] coordinates {%s};" % series("gen"),
        r"\addlegendentry{packed}",
        r"\addplot[draw=PackD, fill=PackD] coordinates {%s};" % series("atomic"),
        r"\addlegendentry{atomic}",
        r"\end{axis}",
        r"\end{tikzpicture}",
    ]) + "\n"


def _fmt0(v):
    return "---" if not v else ("%.0f" % v)


def macros_convho(rows):
    """The figures the prose quotes: each variant's two layouts and the ratio between them."""
    by, _loose = _convho_index(rows)
    out = [PREAMBLE]
    for arm, tag in (("first_order", "First"), ("ho_unlimited", "Unlim"), ("ho_clip", "Clip"),
                     ("ho_venkatakrishnan", "Venk"), ("ho_darwish_moukalled", "Dm")):
        d = by.get(arm, {})
        pk, at = d.get("gen"), d.get("atomic")
        if pk:
            out.append(r"\newcommand{\ho%sPacked}{%.0f}" % (tag, pk))
        if at:
            out.append(r"\newcommand{\ho%sAtomic}{%.0f}" % (tag, at))
        if pk and at:
            out.append(r"\newcommand{\ho%sLayoutRatio}{%.2f}" % (tag, pk / at))
    # What the correction costs against first order WITHIN one layout, so the format is not in the
    # comparison and what is left is the scheme's own arithmetic.
    for lay, suffix in (("gen", "Packed"), ("atomic", "Atomic")):
        fo = by.get("first_order", {}).get(lay)
        for arm, tag in (("ho_unlimited", "Unlim"), ("ho_clip", "Clip"),
                         ("ho_venkatakrishnan", "Venk"), ("ho_darwish_moukalled", "Dm")):
            v = by.get(arm, {}).get(lay)
            if fo and v:
                out.append(r"\newcommand{\ho%sCost%s}{%.2f}" % (tag, suffix, fo / v))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# The like-for-like Jacobian comparison against the assembled matrix
# ---------------------------------------------------------------------------------------------

JF_NAME = {
    "jac_exact":  "Jacobian action, exact",
    "jac_lagged": "Jacobian action, lagged",
    "spmv_f64":   r"SpMV, assembled \texttt{f64}",
    "spmv_f32":   r"SpMV, assembled \texttt{f32}",
}


def parse_jacfair(path):
    out = []
    for line in open(path):
        f = line.split()
        if len(f) >= 4 and f[0] in JF_NAME and f[2] != "-":
            try:
                out.append((f[0], f[1], float(f[2])))
            except ValueError:
                continue
    return out


def table_jacfair(rows):
    """Matrix-free against the assembled matrix, with the operators made comparable.

    The exact row is what a Newton--Krylov solve should apply; the lagged row is the operator
    the assembled matrix can hold, and is the one to compare with the SpMV rows. Reporting only
    the exact row against the SpMV would understate the matrix-free side, because it would be
    doing strictly more work than the matrix encodes.
    """
    if not rows:
        return None
    by = {}
    for op, lay, v in rows:
        by.setdefault(op, {})[lay] = v
    out = [PREAMBLE, r"\small", r"\begin{tabular}{@{}lrrr@{}}", r"\toprule",
           r"operator & packed & atomic & vs.\ \texttt{f64} \\",
           r"& \multicolumn{2}{c}{MDOF/s} & \\", r"\midrule"]
    f64 = by.get("spmv_f64", {}).get("none")
    for op in ("jac_exact", "jac_lagged"):
        if op not in by:
            continue
        pk, at = by[op].get("packed"), by[op].get("atomic")
        rel = (r"$%.2f\times$" % (pk / f64)) if pk and f64 else "---"
        out.append(r"%s & %.0f & %.0f & %s \\" % (JF_NAME[op], pk or 0, at or 0, rel))
    out.append(r"\midrule")
    for op in ("spmv_f64", "spmv_f32"):
        v = by.get(op, {}).get("none")
        if v is None:
            continue
        rel = (r"$%.2f\times$" % (v / f64)) if f64 else "---"
        out.append(r"%s & \multicolumn{2}{c}{%.0f} & %s \\" % (JF_NAME[op], v, rel))
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def macros_jacfair(rows):
    by = {}
    for op, lay, v in rows:
        by.setdefault(op, {})[lay] = v
    out = [PREAMBLE]
    ex = by.get("jac_exact", {}).get("packed")
    lg = by.get("jac_lagged", {}).get("packed")
    f64 = by.get("spmv_f64", {}).get("none")
    f32 = by.get("spmv_f32", {}).get("none")
    if ex and lg:
        out.append(r"\newcommand{\jfExactCost}{%.2f}" % (lg / ex))
    if lg and f64:
        out.append(r"\newcommand{\jfLaggedVsF}{%.2f}" % (lg / f64))
    if lg and f32:
        out.append(r"\newcommand{\jfLaggedVsS}{%.2f}" % (lg / f32))
    if ex and f64:
        # The ratio the UNFAIR comparison would have produced, quoted in the paper to show how
        # much the mismatch was worth rather than silently corrected.
        out.append(r"\newcommand{\jfExactVsF}{%.2f}" % (ex / f64))
    la = by.get("jac_lagged", {}).get("atomic")
    if la and f64:
        out.append(r"\newcommand{\jfLaggedAtomicVsF}{%.2f}" % (la / f64))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------

def build(out_dir, tab_dir):
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(tab_dir, exist_ok=True)
    written = []

    det = [f for f in sorted(os.listdir(DATA)) if f.startswith("det_layout_")] if os.path.isdir(DATA) else []
    if det:
        # The newest run wins; older ones stay on disk as provenance.
        rows, meta = parse_determinism(os.path.join(DATA, det[-1]))
        if rows:
            with open(os.path.join(tab_dir, "determinism.tex"), "w") as fh:
                fh.write(table_determinism(rows, meta))
            with open(os.path.join(out_dir, "determinism_macros.tex"), "w") as fh:
                fh.write(macros_determinism(rows, meta))
            written += ["tables/determinism.tex", "figures/determinism_macros.tex"]

    camp = [f for f in sorted(os.listdir(DATA)) if f.startswith("campaign_")] if os.path.isdir(DATA) else []
    if camp:
        path = os.path.join(DATA, camp[-1])
        # The mesh half of the footprint table is MEASURED, by the bench's --mesh-footprint
        # mode, which reports each array's own nbytes(). It replaced an arithmetic model that
        # had to guess the ghost and reduction-graph lengths and was about 20% out.
        fr = footprint_rows(path)
        try:
            camp_rows_fp, _h = read_campaign(path)
        except ValueError:
            camp_rows_fp = []
        mfp = [f for f in sorted(os.listdir(DATA)) if f.startswith("meshfoot_")]
        mesh = meshfoot_totals(parse_meshfoot(os.path.join(DATA, mfp[-1]))) if mfp else None
        t_fp = table_footprint(camp_rows_fp, mesh) if camp_rows_fp else None
        if t_fp:
            with open(os.path.join(tab_dir, "footprint.tex"), "w") as fh:
                fh.write(t_fp)
            written.append("tables/footprint.tex")
        if mfp:
            mm = macros_meshfoot(parse_meshfoot(os.path.join(DATA, mfp[-1])))
            if mm:
                with open(os.path.join(out_dir, "meshfoot_macros.tex"), "w") as fh:
                    fh.write(mm)
                written.append("figures/meshfoot_macros.tex")
        try:
            rows, host = read_campaign(path)
        except ValueError as exc:
            print("campaign not usable: %s" % exc)
            rows = []
        if rows:
            # A campaign file is the paper's own only if its name carries the job id that made
            # it, which jobs/camp_full.sbatch now stamps.
            prov = re.match(r"campaign_grace_\d+\.csv$", os.path.basename(path)) is None
            if prov:
                print("  NOTE: %s carries no job id -- figures marked provisional"
                      % os.path.basename(path))
            with open(os.path.join(out_dir, "throughput_size.tex"), "w") as fh:
                fh.write(fig_throughput(rows, host))
            with open(os.path.join(out_dir, "campaign_macros.tex"), "w") as fh:
                fh.write(macros_throughput(rows, host, provisional=prov))
            written += ["figures/throughput_size.tex", "figures/campaign_macros.tex"]
            lad = table_ladder(rows)
            if lad:
                with open(os.path.join(tab_dir, "ladder.tex"), "w") as fh:
                    fh.write(lad)
                written.append("tables/ladder.tex")

    ts = [f for f in sorted(os.listdir(DATA)) if f.startswith("tscale_")] if os.path.isdir(DATA) else []
    if ts:
        series, meta = parse_scaling(os.path.join(DATA, ts[-1]))
        if series:
            with open(os.path.join(out_dir, "scaling_res.tex"), "w") as fh:
                fh.write(fig_scaling(series, meta, "res"))
            with open(os.path.join(out_dir, "scaling_macros.tex"), "w") as fh:
                fh.write(macros_scaling(series, meta))
            written += ["figures/scaling_res.tex", "figures/scaling_macros.tex"]

    st = [f for f in sorted(os.listdir(DATA)) if f.startswith("stream_")] if os.path.isdir(DATA) else []
    if st:
        rates = parse_stream(os.path.join(DATA, st[-1]))
        if rates:
            with open(os.path.join(out_dir, "stream_macros.tex"), "w") as fh:
                fh.write(macros_stream(rates))
            written.append("figures/stream_macros.tex")

    ps = [f for f in sorted(os.listdir(DATA)) if f.startswith("packsize_")] if os.path.isdir(DATA) else []
    if ps:
        sweep, order, meta = parse_packsize(os.path.join(DATA, ps[-1]))
        if sweep:
            with open(os.path.join(out_dir, "packsize.tex"), "w") as fh:
                fh.write(fig_packsize(sweep, meta))
            with open(os.path.join(out_dir, "packsize_macros.tex"), "w") as fh:
                fh.write(macros_packsize(sweep, order, meta))
            written += ["figures/packsize.tex", "figures/packsize_macros.tex"]
        ordt = table_ordering(order)
        if ordt:
            with open(os.path.join(tab_dir, "ordering.tex"), "w") as fh:
                fh.write(ordt)
            written.append("tables/ordering.tex")

    # Only the .out files: parse_convho reads the whitespace-aligned summary table, not the CSV
    # that sits beside it, and picking the wrong one silently yields an empty table.
    ho = ([f for f in sorted(os.listdir(DATA))
           if f.startswith("convho_") and f.endswith(".out")] if os.path.isdir(DATA) else [])
    if ho:
        hr = parse_convho(os.path.join(DATA, ho[-1]))
        t = table_convho(hr)
        fg = fig_convho(hr)
        if fg:
            with open(os.path.join(out_dir, "convho.tex"), "w") as fh:
                fh.write(fg)
            written.append("figures/convho.tex")
        if t:
            with open(os.path.join(tab_dir, "convho.tex"), "w") as fh:
                fh.write(t)
            written.append("tables/convho.tex")
            # A higher-order arm that agrees with first order bit for bit did not run.
            with open(os.path.join(out_dir, "convho_macros.tex"), "w") as fh:
                fh.write(macros_convho(hr))
            written.append("figures/convho_macros.tex")
            for lay in ("atomic", "packed"):
                base = next((r for r in hr if r[0] == "first_order" and r[1] == lay), None)
                if not base:
                    continue
                same = [r[0] for r in hr
                        if r[0] != "first_order" and r[1] == lay and r[4] == base[4]]
                if same:
                    print("  WARNING: %s checksum identical to first order -- correction not"
                          " applied in: %s" % (lay, ", ".join(same)))

    jf = [f for f in sorted(os.listdir(DATA)) if f.startswith("jacfair_")] if os.path.isdir(DATA) else []
    if jf:
        jr = parse_jacfair(os.path.join(DATA, jf[-1]))
        t = table_jacfair(jr)
        if t:
            with open(os.path.join(tab_dir, "jacfair.tex"), "w") as fh:
                fh.write(t)
            with open(os.path.join(out_dir, "jacfair_macros.tex"), "w") as fh:
                fh.write(macros_jacfair(jr))
            written += ["tables/jacfair.tex", "figures/jacfair_macros.tex"]

    # F8 needs three things from three different jobs: the campaign (points), STREAM (memory
    # roof) and the GEMM peak (compute roof). Emitted only when all three are present, so a
    # roofline is never drawn with a roof that was assumed.
    pk = [f for f in sorted(os.listdir(DATA)) if f.startswith("peak_")] if os.path.isdir(DATA) else []
    if camp and st and pk and rows:
        peak = parse_peak(os.path.join(DATA, pk[-1]))
        rates = parse_stream(os.path.join(DATA, st[-1]))
        bw = rates.get(max(rates)) if rates else None
        fr = footprint_rows(os.path.join(DATA, camp[-1]))
        mesh_b = fr[0]["packed"] if fr else 0.0
        if peak and bw:
            pts = roofline_points(rows, mesh_b)
            if pts:
                with open(os.path.join(out_dir, "roofline.tex"), "w") as fh:
                    fh.write(fig_roofline(pts, bw, peak))
                with open(os.path.join(out_dir, "roofline_macros.tex"), "w") as fh:
                    fh.write(PREAMBLE
                             + "\\newcommand{\\rlPeak}{%.0f}\n" % peak
                             + "\\newcommand{\\rlBw}{%.0f}\n" % bw
                             + "\\newcommand{\\rlRidge}{%.1f}\n" % (peak / bw)
                             + "\\newcommand{\\rlMeshBytes}{%.1f}\n" % mesh_b
                             + "".join("\\newcommand{\\rl%s}{%.0f}\n" % (_macro_name(l), g)
                                       for l, a, g in pts)
                             + "".join("\\newcommand{\\rl%sAi}{%.1f}\n" % (_macro_name(l), a)
                                       for l, a, g in pts)
                             # Each point as a percentage of the roof BINDING AT ITS OWN
                             # intensity -- memory below the ridge, compute above. This is the
                             # comparison the figure invites and it is easy to state wrongly by
                             # dividing everything by the compute peak.
                             + "".join("\\newcommand{\\rl%sPct}{%.0f}\n"
                                       % (_macro_name(l), 100.0 * g / min(peak, bw * a))
                                       for l, a, g in pts))
                written += ["figures/roofline.tex", "figures/roofline_macros.tex"]
    return written


# ---------------------------------------------------------------------------------------------

def selftest():
    fails = []

    def check(ok, what, detail=""):
        print("%-62s %s%s" % (what, "OK" if ok else "FAIL", ("  " + detail) if detail and not ok else ""))
        if not ok:
            fails.append(what)

    import tempfile

    sample = (
        "### host nid000000  n=100  repeats=3 at 72t  thread sweep: 1 8 36 72\n"
        "### fingerprints are comparable only DOWN a column\n"
        "\n"
        "layout    op    A: repeats @72t              B: across threads\n"
        "atomic    res   3 distinct / 3 runs          4 distinct / 4 runs\n"
        "packed    res   1 distinct / 3 runs          1 distinct / 4 runs\n"
        "colored   jac   1 distinct / 3 runs          2 distinct / 4 runs\n"
    )
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "det_layout_1.out")
        open(p, "w").write(sample)
        rows, meta = parse_determinism(p)

        check(len(rows) == 3, "every data row is parsed, header lines are not", "got %d" % len(rows))
        check(meta.get("host") == "nid000000" and meta.get("n") == "100",
              "the header's host and problem size are recovered")
        check(meta.get("threads") == "1 8 36 72", "the thread sweep is recovered")
        check(rows[0] == ("atomic", "res", (3, 3), (4, 4)), "an irreproducible row parses",
              str(rows[0]))
        check(rows[1] == ("packed", "res", (1, 3), (1, 4)), "a reproducible row parses",
              str(rows[1]))

        tex = table_determinism(rows, meta)
        # The verdict must be visible as emphasis, and only for the reproducible rows --
        # a table that bolds everything says nothing.
        check(tex.count(r"\textbf{1}") == 3, "exactly the reproducible cells are emphasised",
              "%d" % tex.count(r"\textbf{1}"))
        check(r"3 / 3" in tex and r"4 / 4" in tex, "irreproducible cells are plain")
        check(tex.count(r"\\") >= 4 and r"\toprule" in tex, "the table is well formed")

        mac = macros_determinism(rows, meta)
        check(r"\newcommand{\detHost}{nid000000}" in mac, "the host macro is emitted")
        check(r"\newcommand{\detAtomicresRep}{3}" in mac, "a per-row macro is emitted")
        # LaTeX command names cannot contain digits or underscores.
        bad = [m for m in re.findall(r"\\newcommand\{\\([A-Za-z0-9]*)\}", mac)
               if not m.isalpha()]
        check(not bad, "every emitted macro name is alphabetic", str(bad))

        # STREAM: the unit conversion and the "peak is not at full socket" case.
        sp = os.path.join(td, "stream_1.out")
        open(sp, "w").write("### host nidX\n### 72 threads\n  Triad:   450596.7  0.1 0.1 0.1\n"
                            "### 36 threads\n  Triad:   480349.8  0.1 0.1 0.1\n")
        rates = parse_stream(sp)
        check(rates == {72: 450.5967, 36: 480.3498}, "stream triad parses in GB/s", str(rates))
        sm = macros_stream(rates)
        check(r"\newcommand{\streamTriad}{451}" in sm,
              "the bound quoted is the one at the measured thread count")
        check(r"\newcommand{\streamPeak}{480}" in sm and
              r"\newcommand{\streamPeakThreads}{36}" in sm,
              "the peak is reported separately, with the count it occurred at")

        # Campaign: the multi-host refusal, the bare-kernel predicate and the ladder.
        cp = os.path.join(td, "campaign_x.csv")
        hdr = ("host,operation,layout,ran_layout,kernel,cube_n,nodes,elements,dofs,bsr_nnz,"
               "bsr_values_MiB,bsr_storage,MDOF_s,ran_rc,ran_boundary,transient,pgrad_per_apply")
        def row(host, op, lay, n, mdof, rc="off", bnd="off", tr="0", pg="0", store="n/a"):
            return ",".join([host, op, lay, lay, "sumfact", str(n), "10", "8", "40", "0",
                             "0", store, str(mdof), rc, bnd, tr, pg])
        open(cp, "w").write("\n".join([hdr,
            row("nidA", "residual", "packed", 128, 2600),
            row("nidA", "residual", "atomic", 128, 850),
            row("nidA", "residual", "packed", 128, 1300, rc="on"),
            row("nidA", "residual", "atomic", 128, 600, rc="on"),
            row("nidA", "bsr_apply", "packed", 128, 450, store="f64"),
        ]) + "\n")
        rws, hst = read_campaign(cp)
        check(hst == "nidA" and len(rws) == 5, "a single-host campaign reads")
        check(sum(1 for r in rws if _bare(r)) == 3, "the bare-kernel predicate selects only bare rows",
              str(sum(1 for r in rws if _bare(r))))
        lad = table_ladder(rws)
        check(lad is not None and r"3.06\times" in lad.replace("\\times", "\\times"),
              "the ladder reports the bare rung ratio")
        check(r"1300" in lad and r"600" in lad, "the ladder reports the coupled rung")
        mac = macros_throughput(rws, hst)
        check(r"\newcommand{\campHost}{nidA}" in mac, "the campaign host is emitted for provenance")
        check(r"\newcommand{\campResPacked}{2600}" in mac, "the bare packed headline is emitted")
        check(r"\newcommand{\campProvisional}{0}" in mac,
              "a campaign is not marked provisional unless asked")
        check(r"\newcommand{\campProvisional}{1}" in macros_throughput(rws, hst, provisional=True),
              "the provisional marker is emitted when the data carries no job id")

        open(cp, "a").write(row("nidB", "residual", "packed", 128, 9999) + "\n")
        try:
            read_campaign(cp)
            check(False, "a multi-host campaign is refused")
        except ValueError:
            check(True, "a multi-host campaign is refused")

        # ---- the measured mesh footprint --------------------------------------------------
        # The arithmetic here is small but every number in it reaches the paper, and the three
        # totals differ only by which arrays they include -- exactly the kind of accounting
        # that is easy to get subtly wrong and impossible to notice afterwards.
        mf_sample = (
            "### mesh footprint, some host\n"
            "@@@ pack_size 1024\n"
            "### mesh footprint  n_nodes=1000 n_elements=900 dofs=4000\n"
            "### n_packs=4 elements_per_pack=1024 packed_elements=900 "
            "ghost_entries=200 ghost_reduce_rows=150\n"
            "\n"
            "array                                 bytes        B/dof\n"
            "standard.topology_total                40000        10.000\n"
            "packed.elements                        20000         5.000\n"
            "packed.ghost_reduce_ptr                 4000         1.000\n"
            "packed.ghost_reduce_idx                 4000         1.000\n"
            "packed.node_map                         4000         1.000\n"
            "packed.topology_total                  32000         8.000\n"
            "shared.points                          12000         3.000\n"
            "\npacked/standard topology_only   0.8000\n"
        )
        with tempfile.TemporaryDirectory() as td3:
            mp = os.path.join(td3, "meshfoot_x.out")
            open(mp, "w").write(mf_sample)
            mf = parse_meshfoot(mp)
            check(list(mf) == [1024], "one pack-size block is parsed", "got %s" % list(mf))
            check(mf[1024]["ghost_entries"] == 200 and mf[1024]["ghost_reduce_rows"] == 150,
                  "the ghost and reduction-graph counts are read, not derived")
            t = meshfoot_totals(mf)
            check(abs(t["impl"] - 8.0) < 1e-9, "the implemented total is the reported one")
            check(abs(t["working"] - 7.0) < 1e-9,
                  "the working set drops node_map and nothing else")
            check(abs(t["floor"] - 6.0) < 1e-9,
                  "the floor halves both reduction offset arrays and nothing else")
            check(t["floor"] < t["working"] < t["impl"],
                  "the three totals are ordered, so none can silently be the flattering one")
            check(abs(t["std_pts"] - 13.0) < 1e-9 and abs(t["impl_pts"] - 11.0) < 1e-9,
                  "the coordinates are added to both representations, never to one")
            check(abs(t["r_impl"] - 0.8) < 1e-9,
                  "the implemented ratio matches what the bench itself printed")
            # A missing block must yield nothing rather than a partial total.
            check(meshfoot_totals(mf, 99999) is None,
                  "a pack size that was not measured yields no total")

        # Missing data must be absent, not fabricated.
        with tempfile.TemporaryDirectory() as td2:
            written = build(os.path.join(td2, "f"), os.path.join(td2, "t"))
            check(isinstance(written, list), "build returns the list of files it wrote")

    print()
    if fails:
        print("%d check(s) FAILED" % len(fails))
        return 1
    print("all performance-figure checks passed")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=os.path.join(HERE, "..", "figures"))
    ap.add_argument("--tables", default=os.path.join(HERE, "..", "tables"))
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(selftest())

    written = build(args.out, args.tables)
    if not written:
        print("no measurements in %s yet -- see README.md for the programme" % os.path.abspath(DATA))
    for w in written:
        print("wrote %s" % w)


if __name__ == "__main__":
    main()
